// Code generated by capnpc-go. DO NOT EDIT.

package grammar

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
)

type Parser capnp.Client

// Parser_TypeID is the unique identifier for the type Parser.
const Parser_TypeID = 0xff827663f94ae914

func (c Parser) Prompt(ctx context.Context, params func(Parser_prompt_Params) error) (Parser_prompt_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xff827663f94ae914,
			MethodID:      0,
			InterfaceName: "pkg/logic/grammar/parser.capnp:Parser",
			MethodName:    "prompt",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Parser_prompt_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Parser_prompt_Results_Future{Future: ans.Future()}, release

}

func (c Parser) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Parser) String() string {
	return "Parser(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Parser) AddRef() Parser {
	return Parser(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Parser) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Parser) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Parser) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Parser) DecodeFromPtr(p capnp.Ptr) Parser {
	return Parser(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Parser) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Parser) IsSame(other Parser) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Parser) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Parser) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Parser_Server is a Parser with a local implementation.
type Parser_Server interface {
	Prompt(context.Context, Parser_prompt) error
}

// Parser_NewServer creates a new Server from an implementation of Parser_Server.
func Parser_NewServer(s Parser_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Parser_Methods(nil, s), s, c)
}

// Parser_ServerToClient creates a new Client from an implementation of Parser_Server.
// The caller is responsible for calling Release on the returned Client.
func Parser_ServerToClient(s Parser_Server) Parser {
	return Parser(capnp.NewClient(Parser_NewServer(s)))
}

// Parser_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Parser_Methods(methods []server.Method, s Parser_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 1)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xff827663f94ae914,
			MethodID:      0,
			InterfaceName: "pkg/logic/grammar/parser.capnp:Parser",
			MethodName:    "prompt",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Prompt(ctx, Parser_prompt{call})
		},
	})

	return methods
}

// Parser_prompt holds the state for a server call to Parser.prompt.
// See server.Call for documentation.
type Parser_prompt struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Parser_prompt) Args() Parser_prompt_Params {
	return Parser_prompt_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Parser_prompt) AllocResults() (Parser_prompt_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Parser_prompt_Results(r), err
}

// Parser_List is a list of Parser.
type Parser_List = capnp.CapList[Parser]

// NewParser_List creates a new list of Parser.
func NewParser_List(s *capnp.Segment, sz int32) (Parser_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Parser](l), err
}

type Parser_prompt_Params capnp.Struct

// Parser_prompt_Params_TypeID is the unique identifier for the type Parser_prompt_Params.
const Parser_prompt_Params_TypeID = 0x964842a481ade035

func NewParser_prompt_Params(s *capnp.Segment) (Parser_prompt_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Parser_prompt_Params(st), err
}

func NewRootParser_prompt_Params(s *capnp.Segment) (Parser_prompt_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Parser_prompt_Params(st), err
}

func ReadRootParser_prompt_Params(msg *capnp.Message) (Parser_prompt_Params, error) {
	root, err := msg.Root()
	return Parser_prompt_Params(root.Struct()), err
}

func (s Parser_prompt_Params) String() string {
	str, _ := text.Marshal(0x964842a481ade035, capnp.Struct(s))
	return str
}

func (s Parser_prompt_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Parser_prompt_Params) DecodeFromPtr(p capnp.Ptr) Parser_prompt_Params {
	return Parser_prompt_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Parser_prompt_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Parser_prompt_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Parser_prompt_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Parser_prompt_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Parser_prompt_Params) Msg() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Parser_prompt_Params) HasMsg() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Parser_prompt_Params) MsgBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Parser_prompt_Params) SetMsg(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// Parser_prompt_Params_List is a list of Parser_prompt_Params.
type Parser_prompt_Params_List = capnp.StructList[Parser_prompt_Params]

// NewParser_prompt_Params creates a new list of Parser_prompt_Params.
func NewParser_prompt_Params_List(s *capnp.Segment, sz int32) (Parser_prompt_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Parser_prompt_Params](l), err
}

// Parser_prompt_Params_Future is a wrapper for a Parser_prompt_Params promised by a client call.
type Parser_prompt_Params_Future struct{ *capnp.Future }

func (f Parser_prompt_Params_Future) Struct() (Parser_prompt_Params, error) {
	p, err := f.Future.Ptr()
	return Parser_prompt_Params(p.Struct()), err
}

type Parser_prompt_Results capnp.Struct

// Parser_prompt_Results_TypeID is the unique identifier for the type Parser_prompt_Results.
const Parser_prompt_Results_TypeID = 0xcbb78e278fdde226

func NewParser_prompt_Results(s *capnp.Segment) (Parser_prompt_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Parser_prompt_Results(st), err
}

func NewRootParser_prompt_Results(s *capnp.Segment) (Parser_prompt_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Parser_prompt_Results(st), err
}

func ReadRootParser_prompt_Results(msg *capnp.Message) (Parser_prompt_Results, error) {
	root, err := msg.Root()
	return Parser_prompt_Results(root.Struct()), err
}

func (s Parser_prompt_Results) String() string {
	str, _ := text.Marshal(0xcbb78e278fdde226, capnp.Struct(s))
	return str
}

func (s Parser_prompt_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Parser_prompt_Results) DecodeFromPtr(p capnp.Ptr) Parser_prompt_Results {
	return Parser_prompt_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Parser_prompt_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Parser_prompt_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Parser_prompt_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Parser_prompt_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Parser_prompt_Results) Result() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Parser_prompt_Results) HasResult() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Parser_prompt_Results) ResultBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Parser_prompt_Results) SetResult(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// Parser_prompt_Results_List is a list of Parser_prompt_Results.
type Parser_prompt_Results_List = capnp.StructList[Parser_prompt_Results]

// NewParser_prompt_Results creates a new list of Parser_prompt_Results.
func NewParser_prompt_Results_List(s *capnp.Segment, sz int32) (Parser_prompt_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Parser_prompt_Results](l), err
}

// Parser_prompt_Results_Future is a wrapper for a Parser_prompt_Results promised by a client call.
type Parser_prompt_Results_Future struct{ *capnp.Future }

func (f Parser_prompt_Results_Future) Struct() (Parser_prompt_Results, error) {
	p, err := f.Future.Ptr()
	return Parser_prompt_Results(p.Struct()), err
}

const schema_ad058c9d70413d68 = "x\xda\x12\x98\xec\xc0b\xc8\x9b\xcf\xc4\xc0\x14(\xc3\xca" +
	"\xf6\xdf\xf4\xc1\xda\xc6%N\x1e\xd3\x18\x04\xd5\x18\x19\x18" +
	"X\x19\xd9\x19\x18\x8ce\x19\x17120\x0a\xeb2\xda" +
	"30\xfeW{t\xb7_\xbdo\xfbid\x05\xbe\x8c" +
	"\xab@\x0ab\xc1\x0aD^z\xfdL.k\xfa\xcf " +
	"(\xcf\xfc?\xc3\xd6\xb1`n\x0f\xebZ\x06\x06F\xe3" +
	"ZF#F\xe1^\x90\x06\xe1NFw\xe1\x8d\x8c\xec" +
	"\x0c:\xff\x0b\xb2\xd3\xf5s\xf2\xd33Y\x93\xf5\xd3\x8b" +
	"\x12ss\x13\x8b\xf4\x0b\x12\x8b\x8aS\x8b\xf4\x92\x13\x0b" +
	"\xf2\x0a\xac\x02 \x9c\x82\xa2\xfc\xdc\x82\x12\x95\x80\xc4\"" +
	"\xf6\xc4\xdc\xe2@\x16f\x16\x06\x06\x16F\x06\x06A^" +
	"%\x06\x86@\x0ef\xc6@\x11&F\xf6\xdc\xe2tF" +
	"\x1e\x06&F\x1e\x06F\x12\x0d\x0eJ-\xe6/\xcd)" +
	"A1\xd9\x0aa\xb2}QjqiN\x09\x86\xe1\xcc" +
	"\xb8\x0c\x97\x07\xf3\x02\x18\x19\x03Y\x98Y\x19\x18\xe0\xc1" +
	"\xca\x08\x0b>AA+\x06&AVv{\x88\x03\x1c" +
	"\x18\x03\x18\x19\x01\x01\x00\x00\xff\xff\xb4\x86l\xc3"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_ad058c9d70413d68,
		Nodes: []uint64{
			0x964842a481ade035,
			0xcbb78e278fdde226,
			0xff827663f94ae914,
		},
		Compressed: true,
	})
}
