// Code generated by capnpc-go. DO NOT EDIT.

package reader

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
	primitive "github.com/theapemachine/six/pkg/logic/lang/primitive"
)

type Head capnp.Struct

// Head_TypeID is the unique identifier for the type Head.
const Head_TypeID = 0xcc42f99248245ccc

func NewHead(s *capnp.Segment) (Head, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return Head(st), err
}

func NewRootHead(s *capnp.Segment) (Head, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return Head(st), err
}

func ReadRootHead(msg *capnp.Message) (Head, error) {
	root, err := msg.Root()
	return Head(root.Struct()), err
}

func (s Head) String() string {
	str, _ := text.Marshal(0xcc42f99248245ccc, capnp.Struct(s))
	return str
}

func (s Head) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Head) DecodeFromPtr(p capnp.Ptr) Head {
	return Head(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Head) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Head) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Head) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Head) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Head) Input() (primitive.Value, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return primitive.Value(p.Struct()), err
}

func (s Head) HasInput() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Head) SetInput(v primitive.Value) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewInput sets the input field to a newly
// allocated primitive.Value struct, preferring placement in s's segment.
func (s Head) NewInput() (primitive.Value, error) {
	ss, err := primitive.NewValue(capnp.Struct(s).Segment())
	if err != nil {
		return primitive.Value{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Head) Output() (primitive.Value, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return primitive.Value(p.Struct()), err
}

func (s Head) HasOutput() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Head) SetOutput(v primitive.Value) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewOutput sets the output field to a newly
// allocated primitive.Value struct, preferring placement in s's segment.
func (s Head) NewOutput() (primitive.Value, error) {
	ss, err := primitive.NewValue(capnp.Struct(s).Segment())
	if err != nil {
		return primitive.Value{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Head) Operation() (primitive.Value, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return primitive.Value(p.Struct()), err
}

func (s Head) HasOperation() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Head) SetOperation(v primitive.Value) error {
	return capnp.Struct(s).SetPtr(2, capnp.Struct(v).ToPtr())
}

// NewOperation sets the operation field to a newly
// allocated primitive.Value struct, preferring placement in s's segment.
func (s Head) NewOperation() (primitive.Value, error) {
	ss, err := primitive.NewValue(capnp.Struct(s).Segment())
	if err != nil {
		return primitive.Value{}, err
	}
	err = capnp.Struct(s).SetPtr(2, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Head_List is a list of Head.
type Head_List = capnp.StructList[Head]

// NewHead creates a new list of Head.
func NewHead_List(s *capnp.Segment, sz int32) (Head_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3}, sz)
	return capnp.StructList[Head](l), err
}

// Head_Future is a wrapper for a Head promised by a client call.
type Head_Future struct{ *capnp.Future }

func (f Head_Future) Struct() (Head, error) {
	p, err := f.Future.Ptr()
	return Head(p.Struct()), err
}
func (p Head_Future) Input() primitive.Value_Future {
	return primitive.Value_Future{Future: p.Future.Field(0, nil)}
}
func (p Head_Future) Output() primitive.Value_Future {
	return primitive.Value_Future{Future: p.Future.Field(1, nil)}
}
func (p Head_Future) Operation() primitive.Value_Future {
	return primitive.Value_Future{Future: p.Future.Field(2, nil)}
}

type DoneResult capnp.Struct

// DoneResult_TypeID is the unique identifier for the type DoneResult.
const DoneResult_TypeID = 0xf2cb410014a05dc6

func NewDoneResult(s *capnp.Segment) (DoneResult, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return DoneResult(st), err
}

func NewRootDoneResult(s *capnp.Segment) (DoneResult, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return DoneResult(st), err
}

func ReadRootDoneResult(msg *capnp.Message) (DoneResult, error) {
	root, err := msg.Root()
	return DoneResult(root.Struct()), err
}

func (s DoneResult) String() string {
	str, _ := text.Marshal(0xf2cb410014a05dc6, capnp.Struct(s))
	return str
}

func (s DoneResult) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (DoneResult) DecodeFromPtr(p capnp.Ptr) DoneResult {
	return DoneResult(capnp.Struct{}.DecodeFromPtr(p))
}

func (s DoneResult) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s DoneResult) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s DoneResult) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s DoneResult) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s DoneResult) Count() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s DoneResult) SetCount(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s DoneResult) Status() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s DoneResult) HasStatus() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s DoneResult) StatusBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s DoneResult) SetStatus(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s DoneResult) Detail() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s DoneResult) HasDetail() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s DoneResult) DetailBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s DoneResult) SetDetail(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// DoneResult_List is a list of DoneResult.
type DoneResult_List = capnp.StructList[DoneResult]

// NewDoneResult creates a new list of DoneResult.
func NewDoneResult_List(s *capnp.Segment, sz int32) (DoneResult_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[DoneResult](l), err
}

// DoneResult_Future is a wrapper for a DoneResult promised by a client call.
type DoneResult_Future struct{ *capnp.Future }

func (f DoneResult_Future) Struct() (DoneResult, error) {
	p, err := f.Future.Ptr()
	return DoneResult(p.Struct()), err
}

type Reader capnp.Client

// Reader_TypeID is the unique identifier for the type Reader.
const Reader_TypeID = 0xaa96eb7918ebde7a

func (c Reader) Write(ctx context.Context, params func(Reader_write_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xaa96eb7918ebde7a,
			MethodID:      0,
			InterfaceName: "pkg/logic/reader/head.capnp:Reader",
			MethodName:    "write",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Reader_write_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c Reader) Done(ctx context.Context, params func(Reader_done_Params) error) (Reader_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xaa96eb7918ebde7a,
			MethodID:      1,
			InterfaceName: "pkg/logic/reader/head.capnp:Reader",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Reader_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Reader_done_Results_Future{Future: ans.Future()}, release

}

func (c Reader) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Reader) String() string {
	return "Reader(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Reader) AddRef() Reader {
	return Reader(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Reader) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Reader) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Reader) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Reader) DecodeFromPtr(p capnp.Ptr) Reader {
	return Reader(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Reader) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Reader) IsSame(other Reader) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Reader) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Reader) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Reader_Server is a Reader with a local implementation.
type Reader_Server interface {
	Write(context.Context, Reader_write) error

	Done(context.Context, Reader_done) error
}

// Reader_NewServer creates a new Server from an implementation of Reader_Server.
func Reader_NewServer(s Reader_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Reader_Methods(nil, s), s, c)
}

// Reader_ServerToClient creates a new Client from an implementation of Reader_Server.
// The caller is responsible for calling Release on the returned Client.
func Reader_ServerToClient(s Reader_Server) Reader {
	return Reader(capnp.NewClient(Reader_NewServer(s)))
}

// Reader_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Reader_Methods(methods []server.Method, s Reader_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xaa96eb7918ebde7a,
			MethodID:      0,
			InterfaceName: "pkg/logic/reader/head.capnp:Reader",
			MethodName:    "write",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Write(ctx, Reader_write{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xaa96eb7918ebde7a,
			MethodID:      1,
			InterfaceName: "pkg/logic/reader/head.capnp:Reader",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, Reader_done{call})
		},
	})

	return methods
}

// Reader_write holds the state for a server call to Reader.write.
// See server.Call for documentation.
type Reader_write struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Reader_write) Args() Reader_write_Params {
	return Reader_write_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Reader_write) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// Reader_done holds the state for a server call to Reader.done.
// See server.Call for documentation.
type Reader_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Reader_done) Args() Reader_done_Params {
	return Reader_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Reader_done) AllocResults() (Reader_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Reader_done_Results(r), err
}

// Reader_List is a list of Reader.
type Reader_List = capnp.CapList[Reader]

// NewReader_List creates a new list of Reader.
func NewReader_List(s *capnp.Segment, sz int32) (Reader_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Reader](l), err
}

type Reader_write_Params capnp.Struct

// Reader_write_Params_TypeID is the unique identifier for the type Reader_write_Params.
const Reader_write_Params_TypeID = 0xa90cc4fc96973a23

func NewReader_write_Params(s *capnp.Segment) (Reader_write_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Reader_write_Params(st), err
}

func NewRootReader_write_Params(s *capnp.Segment) (Reader_write_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Reader_write_Params(st), err
}

func ReadRootReader_write_Params(msg *capnp.Message) (Reader_write_Params, error) {
	root, err := msg.Root()
	return Reader_write_Params(root.Struct()), err
}

func (s Reader_write_Params) String() string {
	str, _ := text.Marshal(0xa90cc4fc96973a23, capnp.Struct(s))
	return str
}

func (s Reader_write_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Reader_write_Params) DecodeFromPtr(p capnp.Ptr) Reader_write_Params {
	return Reader_write_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Reader_write_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Reader_write_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Reader_write_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Reader_write_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Reader_write_Params) Values() (primitive.Value_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return primitive.Value_List(p.List()), err
}

func (s Reader_write_Params) HasValues() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Reader_write_Params) SetValues(v primitive.Value_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewValues sets the values field to a newly
// allocated primitive.Value_List, preferring placement in s's segment.
func (s Reader_write_Params) NewValues(n int32) (primitive.Value_List, error) {
	l, err := primitive.NewValue_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return primitive.Value_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// Reader_write_Params_List is a list of Reader_write_Params.
type Reader_write_Params_List = capnp.StructList[Reader_write_Params]

// NewReader_write_Params creates a new list of Reader_write_Params.
func NewReader_write_Params_List(s *capnp.Segment, sz int32) (Reader_write_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Reader_write_Params](l), err
}

// Reader_write_Params_Future is a wrapper for a Reader_write_Params promised by a client call.
type Reader_write_Params_Future struct{ *capnp.Future }

func (f Reader_write_Params_Future) Struct() (Reader_write_Params, error) {
	p, err := f.Future.Ptr()
	return Reader_write_Params(p.Struct()), err
}

type Reader_done_Params capnp.Struct

// Reader_done_Params_TypeID is the unique identifier for the type Reader_done_Params.
const Reader_done_Params_TypeID = 0xa604422faf3bc4af

func NewReader_done_Params(s *capnp.Segment) (Reader_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Reader_done_Params(st), err
}

func NewRootReader_done_Params(s *capnp.Segment) (Reader_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Reader_done_Params(st), err
}

func ReadRootReader_done_Params(msg *capnp.Message) (Reader_done_Params, error) {
	root, err := msg.Root()
	return Reader_done_Params(root.Struct()), err
}

func (s Reader_done_Params) String() string {
	str, _ := text.Marshal(0xa604422faf3bc4af, capnp.Struct(s))
	return str
}

func (s Reader_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Reader_done_Params) DecodeFromPtr(p capnp.Ptr) Reader_done_Params {
	return Reader_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Reader_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Reader_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Reader_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Reader_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Reader_done_Params_List is a list of Reader_done_Params.
type Reader_done_Params_List = capnp.StructList[Reader_done_Params]

// NewReader_done_Params creates a new list of Reader_done_Params.
func NewReader_done_Params_List(s *capnp.Segment, sz int32) (Reader_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Reader_done_Params](l), err
}

// Reader_done_Params_Future is a wrapper for a Reader_done_Params promised by a client call.
type Reader_done_Params_Future struct{ *capnp.Future }

func (f Reader_done_Params_Future) Struct() (Reader_done_Params, error) {
	p, err := f.Future.Ptr()
	return Reader_done_Params(p.Struct()), err
}

type Reader_done_Results capnp.Struct

// Reader_done_Results_TypeID is the unique identifier for the type Reader_done_Results.
const Reader_done_Results_TypeID = 0x91abfb38cbe6befe

func NewReader_done_Results(s *capnp.Segment) (Reader_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Reader_done_Results(st), err
}

func NewRootReader_done_Results(s *capnp.Segment) (Reader_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Reader_done_Results(st), err
}

func ReadRootReader_done_Results(msg *capnp.Message) (Reader_done_Results, error) {
	root, err := msg.Root()
	return Reader_done_Results(root.Struct()), err
}

func (s Reader_done_Results) String() string {
	str, _ := text.Marshal(0x91abfb38cbe6befe, capnp.Struct(s))
	return str
}

func (s Reader_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Reader_done_Results) DecodeFromPtr(p capnp.Ptr) Reader_done_Results {
	return Reader_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Reader_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Reader_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Reader_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Reader_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Reader_done_Results) Result() (DoneResult, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return DoneResult(p.Struct()), err
}

func (s Reader_done_Results) HasResult() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Reader_done_Results) SetResult(v DoneResult) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewResult sets the result field to a newly
// allocated DoneResult struct, preferring placement in s's segment.
func (s Reader_done_Results) NewResult() (DoneResult, error) {
	ss, err := NewDoneResult(capnp.Struct(s).Segment())
	if err != nil {
		return DoneResult{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Reader_done_Results_List is a list of Reader_done_Results.
type Reader_done_Results_List = capnp.StructList[Reader_done_Results]

// NewReader_done_Results creates a new list of Reader_done_Results.
func NewReader_done_Results_List(s *capnp.Segment, sz int32) (Reader_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Reader_done_Results](l), err
}

// Reader_done_Results_Future is a wrapper for a Reader_done_Results promised by a client call.
type Reader_done_Results_Future struct{ *capnp.Future }

func (f Reader_done_Results_Future) Struct() (Reader_done_Results, error) {
	p, err := f.Future.Ptr()
	return Reader_done_Results(p.Struct()), err
}
func (p Reader_done_Results_Future) Result() DoneResult_Future {
	return DoneResult_Future{Future: p.Future.Field(0, nil)}
}

const schema_ad058c9d70423d67 = "x\xda\x8cR?h\x13o\x18~\x9f\xef\xbb\xfb\xa5\xf9" +
	"\x91h\x8e\xcb\xa0%\x90\xa1qqhl\xb3HD." +
	"\x0d\x15\xa2\xb4\x92/8((r$\x9f1\x18\xef\xce" +
	"\xfbc1\xa3K\x17\x17\x1d*\x0a\x82\x93PE\x82\x83" +
	"\xab(\x16\x97\xd6\xd1\xd5Q\x90\x0e\x82\xe0P\xff\x9d\xdc" +
	"\xc5\xa4ER\xebv\xf7>\xcf\xf3>\xcf\xc3\xf7\x1e\xb9" +
	"\x86\x8a2\x93^V\x89\x89\x8a\xfa_\xf8\xf3\xc5\x87\xf5" +
	"\xa3\xdf\x9e\xdc&m\x0aD*\x12D\xa5Uv\x13\x04" +
	"\xfd93\x08a\x7f\xedX\xbfXU\x1e\x0d\x08J\x84" +
	"\xbfc=\x90\x12N\x95\xef\xae|_K\xad\xee\x94\xbe" +
	"\x1aH\xdf\xc6\xd2\xde\xfb\xcd\x0376W\x1e\x93\x96\xe3" +
	"a\xfbx\xd5ypK}J\x84\xd2\x0f6\x09=\xcd" +
	"\x13Dz\x92/\xeb\xe7\xa2\xafp\xe3|\xa1vg\xab" +
	"\xbaAZ\x0e\xdbl5\xc2Js\xfc\x7f\xe8\"\x16," +
	"\xf2>\xe1\xd3\x9b\x0b\x0f\xb3s\xeb\x9fE\x0e;\xb9," +
	"\xe2~\xe4e\xe8[1\xf7\x0b\xef\x93\x1d:W\xda\xc5" +
	"\xae\xdd\xee\xa8\xcd\xa2+\xcd\x96t\x8b\x97\xa5\xd9\x9an" +
	"\x9a\x8e\xe5\x94\x1b\xf1d\xbae[\xb2\xd0\x90^\xd0\xf5" +
	"=\x12\x0aW\x88\x14\x10i\xe92\x91\x98\xe0\x10Y\x06" +
	"\xc3\x8dqd\x86\xee\x04d\x08\xa3\xfd\xca^\xfb\x8d\xba" +
	"\xe9\x9aW\xbd\x7f\x0a\xb4\xe4v|Y\x18\x08\xc6\x06*" +
	"0\x18\xd7\xcdn =\xec#\xd49\x90\x09/)\xa7" +
	"&O\x7f\xed\xbd&B4\x1c\x19\xf1\xdd\x8c\xb8t\xeb" +
	"\x80\x98\xe0*\xd1\xe8=a={\xb9T\xba\x7f\xf1\x9e" +
	"63KL;\x94\xc0\xf6\x15`x/\xda\xc1\xc3\xc4" +
	"\xb4t\"\x1f\x07\xad`\x7f\xd4\xb0\x82:\xf6p\xadI" +
	"\xb3E\x14\x99\xa6F\x9dN\xcc\x12\x89\x0a\x87X`\xd0" +
	"\x80,\xa2\xe1\xc9\xa8\xe8<\x87\xa83h\x8ce\xc1\x88" +
	"\xb4\xc5\x06\x91X\xe0\x10g\x19\xf2\x1d\xcb\x09\xfc?Z" +
	"g\x08\x86\x1d\xf8c\x81\xd0v\xa4k\xfa\x1d\x9b`\x8d" +
	"A\xff\x1a{\xde\xb6\xa41\xb8\x8f\xdd\xb3\x8f\x8f\x8e\xdf" +
	"\xd1\xa3a\x8dC\x9ca\xc87\xed\xc0\xf2\x91$\x86$" +
	"\xc1\xf0|\xd3\x0f<\xa4\x88!E0Z\xd27;\xdd" +
	"\xe1\xef\xaf\x00\x00\x00\xff\xff\xb9\xab\xfbq"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_ad058c9d70423d67,
		Nodes: []uint64{
			0x91abfb38cbe6befe,
			0xa604422faf3bc4af,
			0xa90cc4fc96973a23,
			0xaa96eb7918ebde7a,
			0xcc42f99248245ccc,
			0xf2cb410014a05dc6,
		},
		Compressed: true,
	})
}
