// Code generated by capnpc-go. DO NOT EDIT.

package synthesis

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
	primitive "github.com/theapemachine/six/pkg/logic/lang/primitive"
)

type HAS capnp.Client

// HAS_TypeID is the unique identifier for the type HAS.
const HAS_TypeID = 0x9cabc36bb2042d20

func (c HAS) Write(ctx context.Context, params func(HAS_write_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x9cabc36bb2042d20,
			MethodID:      0,
			InterfaceName: "pkg/logic/synthesis/has.capnp:HAS",
			MethodName:    "write",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 2}
		s.PlaceArgs = func(s capnp.Struct) error { return params(HAS_write_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c HAS) Done(ctx context.Context, params func(HAS_done_Params) error) (HAS_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x9cabc36bb2042d20,
			MethodID:      1,
			InterfaceName: "pkg/logic/synthesis/has.capnp:HAS",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(HAS_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return HAS_done_Results_Future{Future: ans.Future()}, release

}

func (c HAS) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c HAS) String() string {
	return "HAS(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c HAS) AddRef() HAS {
	return HAS(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c HAS) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c HAS) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c HAS) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (HAS) DecodeFromPtr(p capnp.Ptr) HAS {
	return HAS(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c HAS) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c HAS) IsSame(other HAS) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c HAS) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c HAS) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A HAS_Server is a HAS with a local implementation.
type HAS_Server interface {
	Write(context.Context, HAS_write) error

	Done(context.Context, HAS_done) error
}

// HAS_NewServer creates a new Server from an implementation of HAS_Server.
func HAS_NewServer(s HAS_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(HAS_Methods(nil, s), s, c)
}

// HAS_ServerToClient creates a new Client from an implementation of HAS_Server.
// The caller is responsible for calling Release on the returned Client.
func HAS_ServerToClient(s HAS_Server) HAS {
	return HAS(capnp.NewClient(HAS_NewServer(s)))
}

// HAS_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func HAS_Methods(methods []server.Method, s HAS_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x9cabc36bb2042d20,
			MethodID:      0,
			InterfaceName: "pkg/logic/synthesis/has.capnp:HAS",
			MethodName:    "write",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Write(ctx, HAS_write{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x9cabc36bb2042d20,
			MethodID:      1,
			InterfaceName: "pkg/logic/synthesis/has.capnp:HAS",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, HAS_done{call})
		},
	})

	return methods
}

// HAS_write holds the state for a server call to HAS.write.
// See server.Call for documentation.
type HAS_write struct {
	*server.Call
}

// Args returns the call's arguments.
func (c HAS_write) Args() HAS_write_Params {
	return HAS_write_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c HAS_write) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// HAS_done holds the state for a server call to HAS.done.
// See server.Call for documentation.
type HAS_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c HAS_done) Args() HAS_done_Params {
	return HAS_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c HAS_done) AllocResults() (HAS_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 24, PointerCount: 1})
	return HAS_done_Results(r), err
}

// HAS_List is a list of HAS.
type HAS_List = capnp.CapList[HAS]

// NewHAS_List creates a new list of HAS.
func NewHAS_List(s *capnp.Segment, sz int32) (HAS_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[HAS](l), err
}

type HAS_write_Params capnp.Struct

// HAS_write_Params_TypeID is the unique identifier for the type HAS_write_Params.
const HAS_write_Params_TypeID = 0xbc44ecaf56bccdfe

func NewHAS_write_Params(s *capnp.Segment) (HAS_write_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return HAS_write_Params(st), err
}

func NewRootHAS_write_Params(s *capnp.Segment) (HAS_write_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return HAS_write_Params(st), err
}

func ReadRootHAS_write_Params(msg *capnp.Message) (HAS_write_Params, error) {
	root, err := msg.Root()
	return HAS_write_Params(root.Struct()), err
}

func (s HAS_write_Params) String() string {
	str, _ := text.Marshal(0xbc44ecaf56bccdfe, capnp.Struct(s))
	return str
}

func (s HAS_write_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (HAS_write_Params) DecodeFromPtr(p capnp.Ptr) HAS_write_Params {
	return HAS_write_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s HAS_write_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s HAS_write_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s HAS_write_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s HAS_write_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s HAS_write_Params) Start() (primitive.Value, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return primitive.Value(p.Struct()), err
}

func (s HAS_write_Params) HasStart() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s HAS_write_Params) SetStart(v primitive.Value) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewStart sets the start field to a newly
// allocated primitive.Value struct, preferring placement in s's segment.
func (s HAS_write_Params) NewStart() (primitive.Value, error) {
	ss, err := primitive.NewValue(capnp.Struct(s).Segment())
	if err != nil {
		return primitive.Value{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s HAS_write_Params) End() (primitive.Value, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return primitive.Value(p.Struct()), err
}

func (s HAS_write_Params) HasEnd() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s HAS_write_Params) SetEnd(v primitive.Value) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewEnd sets the end field to a newly
// allocated primitive.Value struct, preferring placement in s's segment.
func (s HAS_write_Params) NewEnd() (primitive.Value, error) {
	ss, err := primitive.NewValue(capnp.Struct(s).Segment())
	if err != nil {
		return primitive.Value{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// HAS_write_Params_List is a list of HAS_write_Params.
type HAS_write_Params_List = capnp.StructList[HAS_write_Params]

// NewHAS_write_Params creates a new list of HAS_write_Params.
func NewHAS_write_Params_List(s *capnp.Segment, sz int32) (HAS_write_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[HAS_write_Params](l), err
}

// HAS_write_Params_Future is a wrapper for a HAS_write_Params promised by a client call.
type HAS_write_Params_Future struct{ *capnp.Future }

func (f HAS_write_Params_Future) Struct() (HAS_write_Params, error) {
	p, err := f.Future.Ptr()
	return HAS_write_Params(p.Struct()), err
}
func (p HAS_write_Params_Future) Start() primitive.Value_Future {
	return primitive.Value_Future{Future: p.Future.Field(0, nil)}
}
func (p HAS_write_Params_Future) End() primitive.Value_Future {
	return primitive.Value_Future{Future: p.Future.Field(1, nil)}
}

type HAS_done_Params capnp.Struct

// HAS_done_Params_TypeID is the unique identifier for the type HAS_done_Params.
const HAS_done_Params_TypeID = 0xf64d9b2672740664

func NewHAS_done_Params(s *capnp.Segment) (HAS_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return HAS_done_Params(st), err
}

func NewRootHAS_done_Params(s *capnp.Segment) (HAS_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return HAS_done_Params(st), err
}

func ReadRootHAS_done_Params(msg *capnp.Message) (HAS_done_Params, error) {
	root, err := msg.Root()
	return HAS_done_Params(root.Struct()), err
}

func (s HAS_done_Params) String() string {
	str, _ := text.Marshal(0xf64d9b2672740664, capnp.Struct(s))
	return str
}

func (s HAS_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (HAS_done_Params) DecodeFromPtr(p capnp.Ptr) HAS_done_Params {
	return HAS_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s HAS_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s HAS_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s HAS_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s HAS_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// HAS_done_Params_List is a list of HAS_done_Params.
type HAS_done_Params_List = capnp.StructList[HAS_done_Params]

// NewHAS_done_Params creates a new list of HAS_done_Params.
func NewHAS_done_Params_List(s *capnp.Segment, sz int32) (HAS_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[HAS_done_Params](l), err
}

// HAS_done_Params_Future is a wrapper for a HAS_done_Params promised by a client call.
type HAS_done_Params_Future struct{ *capnp.Future }

func (f HAS_done_Params_Future) Struct() (HAS_done_Params, error) {
	p, err := f.Future.Ptr()
	return HAS_done_Params(p.Struct()), err
}

type HAS_done_Results capnp.Struct

// HAS_done_Results_TypeID is the unique identifier for the type HAS_done_Results.
const HAS_done_Results_TypeID = 0xa4539c2b7bef364f

func NewHAS_done_Results(s *capnp.Segment) (HAS_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1})
	return HAS_done_Results(st), err
}

func NewRootHAS_done_Results(s *capnp.Segment) (HAS_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1})
	return HAS_done_Results(st), err
}

func ReadRootHAS_done_Results(msg *capnp.Message) (HAS_done_Results, error) {
	root, err := msg.Root()
	return HAS_done_Results(root.Struct()), err
}

func (s HAS_done_Results) String() string {
	str, _ := text.Marshal(0xa4539c2b7bef364f, capnp.Struct(s))
	return str
}

func (s HAS_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (HAS_done_Results) DecodeFromPtr(p capnp.Ptr) HAS_done_Results {
	return HAS_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s HAS_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s HAS_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s HAS_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s HAS_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s HAS_done_Results) KeyText() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s HAS_done_Results) HasKeyText() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s HAS_done_Results) KeyTextBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s HAS_done_Results) SetKeyText(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s HAS_done_Results) UseCount() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s HAS_done_Results) SetUseCount(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s HAS_done_Results) Hardened() bool {
	return capnp.Struct(s).Bit(64)
}

func (s HAS_done_Results) SetHardened(v bool) {
	capnp.Struct(s).SetBit(64, v)
}

func (s HAS_done_Results) WinnerIndex() int32 {
	return int32(capnp.Struct(s).Uint32(12))
}

func (s HAS_done_Results) SetWinnerIndex(v int32) {
	capnp.Struct(s).SetUint32(12, uint32(v))
}

func (s HAS_done_Results) PostResidue() int32 {
	return int32(capnp.Struct(s).Uint32(16))
}

func (s HAS_done_Results) SetPostResidue(v int32) {
	capnp.Struct(s).SetUint32(16, uint32(v))
}

func (s HAS_done_Results) Steps() uint32 {
	return capnp.Struct(s).Uint32(20)
}

func (s HAS_done_Results) SetSteps(v uint32) {
	capnp.Struct(s).SetUint32(20, v)
}

// HAS_done_Results_List is a list of HAS_done_Results.
type HAS_done_Results_List = capnp.StructList[HAS_done_Results]

// NewHAS_done_Results creates a new list of HAS_done_Results.
func NewHAS_done_Results_List(s *capnp.Segment, sz int32) (HAS_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1}, sz)
	return capnp.StructList[HAS_done_Results](l), err
}

// HAS_done_Results_Future is a wrapper for a HAS_done_Results promised by a client call.
type HAS_done_Results_Future struct{ *capnp.Future }

func (f HAS_done_Results_Future) Struct() (HAS_done_Results, error) {
	p, err := f.Future.Ptr()
	return HAS_done_Results(p.Struct()), err
}

const schema_ad058c9d70413d3c = "x\xda\x8c\x91\xbbk\x14_\x1c\xc5\xcf\xb9\xf7Nf\x03" +
	"\x09\xbf\xdc\xdfn\xa1\x16FB\x14\x1f\xe4\xb9\"\"J" +
	"6j\xa1\xc1\xc7\xdeD\xb4\x12\x193\xd7dI\x9c\x1d" +
	"ff\xd9$\x16\x966\x96ZD\x13P\x88 h\xf0" +
	"\x81B\x8a\x08\x81\xd8Z\xfbO\x08v\x16\x82\x8e\xdcH" +
	"\xd6B\x84t\xc3g\xce\xe5\x1c>\xdf\xc1\x0b\xac\xa8\xa1" +
	"\xce\xcf\x0a\xc2\x1c\xf7\xda\xf2}}\xea\xed\xcc\xe6\x8b%" +
	"\xe8\xbd2?yj4^\xbe\xef\xad\x02,\x1b\xf1?" +
	"\x8b\x81\xf0\x81\xe2uq\xaf\xb8\xea\xbe\xf2\xcb\xc7\xbe\xde" +
	"9\xb24\xb1\x02\xd3C\x09x\xf4\x81\xf2C\xb1@\xb0" +
	"\xfcT\\#\x98\xff\xfc\xb4~\xf5\xd5\x97\xb3\xeb\xd0=" +
	"\x04<\xf7\xac\xfcC\xbaD\xb1]5\xc1<l\xcb\x92" +
	"\x03\x8f/~\xfb\x1dP\xee\xbfU\x09\x91\xe4\xf1\xcc\xd4" +
	"\xc0l}\xaa&'\x07\xd2\xf9(\x9b\xb6i-\x1d\x98" +
	"\x0e\xd2\xfe\xc9 \x8e\xe2\x13\xe7F9Q%MAz" +
	"@\xab\x87\xd1\x9b\x8df\xf9\xd1\x8dE=4\x0c\xa1\xf7" +
	"\xfb\xfcS\xc1\xed\xbdz\xf7a\x08\xdd\xe9w7\x93Z" +
	"f+\xfc/\xacG\xb6\xc2*\xd9*U\xff*\x9d\xe8" +
	"w\xe1\xde\xf1\x11\x9b6f\xb3\xd4\xec\x92\x0aP\x04\xf4" +
	"\xe2i\xc0<\x904O\x04\xc9\x12\x1d[\x1e\x03\xcc\x92" +
	"\xa4y.\xa8E\xa5D\x01\xe8g\x0e\xaeH\x9a\xd7\x82" +
	"Z\xca\x92s\xa7Wo\x02\xe6\xa5\xa4Y\x13\xd4J\x95" +
	"\xa8\x00\xfd\xde\xc1w\x92fCP{^\x89\x1e\xa0?" +
	"\x0c\x03fM\xd2|\x14\xbc;c\xe7\xaf\xd8\xb9\x8c\x1d" +
	"\x10\xec\x00\xf3Fj\xcf\xd4\x1bQ\x06\x80\xed\x10l\x07" +
	"\xf3\xe9 \x09mdC\xc7\x08Aw\x97f-\x8al" +
	"r>\x82\x1f\xda9*\x08*0\x8f\xebi6n\xd3" +
	"\x1a\xfc\xb0a\xb7iw\x9a\xd98e\x01\x82\x05\xec\xc8" +
	"\xd0\x96\xd6\xde\x91j\x90\x04\xb7SSh\x19:\xe4\x96" +
	"\xf7J\x9aAA\xbd\xad\xa8\xaf\x070\x07%\xcdQ\xe1" +
	"\xaa\x82$cW~K\x8d\xed\xb9\xf4}a\xd3-\xee" +
	"\x02}\x1b\x85\x7f\xd3\x1d\x1f\xab\xda\xbd\xb5\xe4W\x00\x00" +
	"\x00\xff\xff1\xff\xbf\xb1"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_ad058c9d70413d3c,
		Nodes: []uint64{
			0x9cabc36bb2042d20,
			0xa4539c2b7bef364f,
			0xbc44ecaf56bccdfe,
			0xf64d9b2672740664,
		},
		Compressed: true,
	})
}
