// Code generated by capnpc-go. DO NOT EDIT.

package bvp

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
)

type Cantilever capnp.Client

// Cantilever_TypeID is the unique identifier for the type Cantilever.
const Cantilever_TypeID = 0xcc7a3ddf056ca685

func (c Cantilever) Prompt(ctx context.Context, params func(Cantilever_prompt_Params) error) (Cantilever_prompt_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xcc7a3ddf056ca685,
			MethodID:      0,
			InterfaceName: "pkg/logic/synthesis/bvp/cantilever.capnp:Cantilever",
			MethodName:    "prompt",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Cantilever_prompt_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Cantilever_prompt_Results_Future{Future: ans.Future()}, release

}

func (c Cantilever) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Cantilever) String() string {
	return "Cantilever(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Cantilever) AddRef() Cantilever {
	return Cantilever(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Cantilever) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Cantilever) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Cantilever) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Cantilever) DecodeFromPtr(p capnp.Ptr) Cantilever {
	return Cantilever(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Cantilever) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Cantilever) IsSame(other Cantilever) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Cantilever) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Cantilever) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Cantilever_Server is a Cantilever with a local implementation.
type Cantilever_Server interface {
	Prompt(context.Context, Cantilever_prompt) error
}

// Cantilever_NewServer creates a new Server from an implementation of Cantilever_Server.
func Cantilever_NewServer(s Cantilever_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Cantilever_Methods(nil, s), s, c)
}

// Cantilever_ServerToClient creates a new Client from an implementation of Cantilever_Server.
// The caller is responsible for calling Release on the returned Client.
func Cantilever_ServerToClient(s Cantilever_Server) Cantilever {
	return Cantilever(capnp.NewClient(Cantilever_NewServer(s)))
}

// Cantilever_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Cantilever_Methods(methods []server.Method, s Cantilever_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 1)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xcc7a3ddf056ca685,
			MethodID:      0,
			InterfaceName: "pkg/logic/synthesis/bvp/cantilever.capnp:Cantilever",
			MethodName:    "prompt",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Prompt(ctx, Cantilever_prompt{call})
		},
	})

	return methods
}

// Cantilever_prompt holds the state for a server call to Cantilever.prompt.
// See server.Call for documentation.
type Cantilever_prompt struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Cantilever_prompt) Args() Cantilever_prompt_Params {
	return Cantilever_prompt_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Cantilever_prompt) AllocResults() (Cantilever_prompt_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Cantilever_prompt_Results(r), err
}

// Cantilever_List is a list of Cantilever.
type Cantilever_List = capnp.CapList[Cantilever]

// NewCantilever_List creates a new list of Cantilever.
func NewCantilever_List(s *capnp.Segment, sz int32) (Cantilever_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Cantilever](l), err
}

type Cantilever_prompt_Params capnp.Struct

// Cantilever_prompt_Params_TypeID is the unique identifier for the type Cantilever_prompt_Params.
const Cantilever_prompt_Params_TypeID = 0xa95068d88bef6781

func NewCantilever_prompt_Params(s *capnp.Segment) (Cantilever_prompt_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Cantilever_prompt_Params(st), err
}

func NewRootCantilever_prompt_Params(s *capnp.Segment) (Cantilever_prompt_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Cantilever_prompt_Params(st), err
}

func ReadRootCantilever_prompt_Params(msg *capnp.Message) (Cantilever_prompt_Params, error) {
	root, err := msg.Root()
	return Cantilever_prompt_Params(root.Struct()), err
}

func (s Cantilever_prompt_Params) String() string {
	str, _ := text.Marshal(0xa95068d88bef6781, capnp.Struct(s))
	return str
}

func (s Cantilever_prompt_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Cantilever_prompt_Params) DecodeFromPtr(p capnp.Ptr) Cantilever_prompt_Params {
	return Cantilever_prompt_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Cantilever_prompt_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Cantilever_prompt_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Cantilever_prompt_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Cantilever_prompt_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Cantilever_prompt_Params) Msg() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Cantilever_prompt_Params) HasMsg() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Cantilever_prompt_Params) MsgBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Cantilever_prompt_Params) SetMsg(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// Cantilever_prompt_Params_List is a list of Cantilever_prompt_Params.
type Cantilever_prompt_Params_List = capnp.StructList[Cantilever_prompt_Params]

// NewCantilever_prompt_Params creates a new list of Cantilever_prompt_Params.
func NewCantilever_prompt_Params_List(s *capnp.Segment, sz int32) (Cantilever_prompt_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Cantilever_prompt_Params](l), err
}

// Cantilever_prompt_Params_Future is a wrapper for a Cantilever_prompt_Params promised by a client call.
type Cantilever_prompt_Params_Future struct{ *capnp.Future }

func (f Cantilever_prompt_Params_Future) Struct() (Cantilever_prompt_Params, error) {
	p, err := f.Future.Ptr()
	return Cantilever_prompt_Params(p.Struct()), err
}

type Cantilever_prompt_Results capnp.Struct

// Cantilever_prompt_Results_TypeID is the unique identifier for the type Cantilever_prompt_Results.
const Cantilever_prompt_Results_TypeID = 0xc7be4b718260c780

func NewCantilever_prompt_Results(s *capnp.Segment) (Cantilever_prompt_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Cantilever_prompt_Results(st), err
}

func NewRootCantilever_prompt_Results(s *capnp.Segment) (Cantilever_prompt_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Cantilever_prompt_Results(st), err
}

func ReadRootCantilever_prompt_Results(msg *capnp.Message) (Cantilever_prompt_Results, error) {
	root, err := msg.Root()
	return Cantilever_prompt_Results(root.Struct()), err
}

func (s Cantilever_prompt_Results) String() string {
	str, _ := text.Marshal(0xc7be4b718260c780, capnp.Struct(s))
	return str
}

func (s Cantilever_prompt_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Cantilever_prompt_Results) DecodeFromPtr(p capnp.Ptr) Cantilever_prompt_Results {
	return Cantilever_prompt_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Cantilever_prompt_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Cantilever_prompt_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Cantilever_prompt_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Cantilever_prompt_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Cantilever_prompt_Results) Result() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Cantilever_prompt_Results) HasResult() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Cantilever_prompt_Results) ResultBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Cantilever_prompt_Results) SetResult(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// Cantilever_prompt_Results_List is a list of Cantilever_prompt_Results.
type Cantilever_prompt_Results_List = capnp.StructList[Cantilever_prompt_Results]

// NewCantilever_prompt_Results creates a new list of Cantilever_prompt_Results.
func NewCantilever_prompt_Results_List(s *capnp.Segment, sz int32) (Cantilever_prompt_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Cantilever_prompt_Results](l), err
}

// Cantilever_prompt_Results_Future is a wrapper for a Cantilever_prompt_Results promised by a client call.
type Cantilever_prompt_Results_Future struct{ *capnp.Future }

func (f Cantilever_prompt_Results_Future) Struct() (Cantilever_prompt_Results, error) {
	p, err := f.Future.Ptr()
	return Cantilever_prompt_Results(p.Struct()), err
}

const schema_ad058c9d70413d6a = "x\xda\x12\x98\xe9\xc0b\xc8\x9b\xcf\xc4\xc0\x14(\xc3\xca" +
	"\xf6\xbf1\xfd}\xf7\x8d\x8c\x80\x95\x0c\x82&\x8c\x0c\x0c" +
	"\xac\x8c\xec\x0c\x0c\xc6\xb2\x8cBL\x0c\x8c\xc2\xa6\x8c\xf6" +
	"\x0c\x8c\xff\x1b\x8e'4\x15z\xef;\x8e\xac \x94Q" +
	"\x0a\xa4 \x17\xac\xa0uY\x0e\xeb}\xdb\xaa3\x0c\x82" +
	"\x9a\xcc\xff\xb3l\x1d\x0b\xe6\xf6\xb0\xaee``4\xee" +
	"e\\\xc4(\xbc\x14\xa4Ax!\xa3\xbb\xf0IFv" +
	"\x06\x9d\xff\x05\xd9\xe9\xfa9\xf9\xe9\x99\xec\xc9\xfa\xc5\x95" +
	"y%\x19\xa9\xc5\x99\xc5\xfaIe\x05\xfa\xc9\x89y%" +
	"\x999\xa9e\xa9Ez\xc9\x89\x05y\x05V\xce\x08\x81" +
	"\x82\xa2\xfc\xdc\x82\x12\x95\x80\xc4\xa2\xc4\\\xc6\xe2@\x16" +
	"f\x16\x06\x06\x16F\x06\x06A^%\x06\x86@\x0ef" +
	"\xc6@\x11&F\xf6\xdc\xe2tF\x1e\x06&F\x1e\x06" +
	"F\x8a\xac\x09J-.\xcda.A\xb1\xc7\x0aa\x8f" +
	"}\x11H\xbe\x04\xc3*Vb\xadb/K-\x0a`" +
	"d\x0cdafe`\x80G\x00#,\xa0\x05\x05\xad" +
	"\x18\x98\x04Y\xd9\xed!\xceq`\x0c`d\x04\x04\x00" +
	"\x00\xff\xff~h}\xcf"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_ad058c9d70413d6a,
		Nodes: []uint64{
			0xa95068d88bef6781,
			0xc7be4b718260c780,
			0xcc7a3ddf056ca685,
		},
		Compressed: true,
	})
}
