// Code generated by capnpc-go. DO NOT EDIT.

package lsm

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
	data "github.com/theapemachine/six/pkg/data"
)

type GraphEdge capnp.Struct

// GraphEdge_TypeID is the unique identifier for the type GraphEdge.
const GraphEdge_TypeID = 0xff419ee763c22842

func NewGraphEdge(s *capnp.Segment) (GraphEdge, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return GraphEdge(st), err
}

func NewRootGraphEdge(s *capnp.Segment) (GraphEdge, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return GraphEdge(st), err
}

func ReadRootGraphEdge(msg *capnp.Message) (GraphEdge, error) {
	root, err := msg.Root()
	return GraphEdge(root.Struct()), err
}

func (s GraphEdge) String() string {
	str, _ := text.Marshal(0xff419ee763c22842, capnp.Struct(s))
	return str
}

func (s GraphEdge) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (GraphEdge) DecodeFromPtr(p capnp.Ptr) GraphEdge {
	return GraphEdge(capnp.Struct{}.DecodeFromPtr(p))
}

func (s GraphEdge) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s GraphEdge) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s GraphEdge) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s GraphEdge) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s GraphEdge) Left() uint8 {
	return capnp.Struct(s).Uint8(0)
}

func (s GraphEdge) SetLeft(v uint8) {
	capnp.Struct(s).SetUint8(0, v)
}

func (s GraphEdge) Right() uint8 {
	return capnp.Struct(s).Uint8(1)
}

func (s GraphEdge) SetRight(v uint8) {
	capnp.Struct(s).SetUint8(1, v)
}

func (s GraphEdge) Position() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s GraphEdge) SetPosition(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

func (s GraphEdge) Chord() (data.Chord, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return data.Chord(p.Struct()), err
}

func (s GraphEdge) HasChord() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s GraphEdge) SetChord(v data.Chord) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewChord sets the chord field to a newly
// allocated data.Chord struct, preferring placement in s's segment.
func (s GraphEdge) NewChord() (data.Chord, error) {
	ss, err := data.NewChord(capnp.Struct(s).Segment())
	if err != nil {
		return data.Chord{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s GraphEdge) Meta() (data.Chord, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return data.Chord(p.Struct()), err
}

func (s GraphEdge) HasMeta() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s GraphEdge) SetMeta(v data.Chord) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewMeta sets the meta field to a newly
// allocated data.Chord struct, preferring placement in s's segment.
func (s GraphEdge) NewMeta() (data.Chord, error) {
	ss, err := data.NewChord(capnp.Struct(s).Segment())
	if err != nil {
		return data.Chord{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// GraphEdge_List is a list of GraphEdge.
type GraphEdge_List = capnp.StructList[GraphEdge]

// NewGraphEdge creates a new list of GraphEdge.
func NewGraphEdge_List(s *capnp.Segment, sz int32) (GraphEdge_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[GraphEdge](l), err
}

// GraphEdge_Future is a wrapper for a GraphEdge promised by a client call.
type GraphEdge_Future struct{ *capnp.Future }

func (f GraphEdge_Future) Struct() (GraphEdge, error) {
	p, err := f.Future.Ptr()
	return GraphEdge(p.Struct()), err
}
func (p GraphEdge_Future) Chord() data.Chord_Future {
	return data.Chord_Future{Future: p.Future.Field(0, nil)}
}
func (p GraphEdge_Future) Meta() data.Chord_Future {
	return data.Chord_Future{Future: p.Future.Field(1, nil)}
}

type SpatialIndex capnp.Client

// SpatialIndex_TypeID is the unique identifier for the type SpatialIndex.
const SpatialIndex_TypeID = 0xfdb082e626e1958b

func (c SpatialIndex) Insert(ctx context.Context, params func(SpatialIndex_insert_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xfdb082e626e1958b,
			MethodID:      0,
			InterfaceName: "pkg/store/lsm/spatial_index.capnp:SpatialIndex",
			MethodName:    "insert",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(SpatialIndex_insert_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c SpatialIndex) Done(ctx context.Context, params func(SpatialIndex_done_Params) error) (SpatialIndex_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xfdb082e626e1958b,
			MethodID:      1,
			InterfaceName: "pkg/store/lsm/spatial_index.capnp:SpatialIndex",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(SpatialIndex_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return SpatialIndex_done_Results_Future{Future: ans.Future()}, release

}

func (c SpatialIndex) Lookup(ctx context.Context, params func(SpatialIndex_lookup_Params) error) (SpatialIndex_lookup_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xfdb082e626e1958b,
			MethodID:      2,
			InterfaceName: "pkg/store/lsm/spatial_index.capnp:SpatialIndex",
			MethodName:    "lookup",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(SpatialIndex_lookup_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return SpatialIndex_lookup_Results_Future{Future: ans.Future()}, release

}

func (c SpatialIndex) QueryTransitions(ctx context.Context, params func(SpatialIndex_queryTransitions_Params) error) (SpatialIndex_queryTransitions_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xfdb082e626e1958b,
			MethodID:      3,
			InterfaceName: "pkg/store/lsm/spatial_index.capnp:SpatialIndex",
			MethodName:    "queryTransitions",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(SpatialIndex_queryTransitions_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return SpatialIndex_queryTransitions_Results_Future{Future: ans.Future()}, release

}

func (c SpatialIndex) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c SpatialIndex) String() string {
	return "SpatialIndex(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c SpatialIndex) AddRef() SpatialIndex {
	return SpatialIndex(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c SpatialIndex) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c SpatialIndex) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c SpatialIndex) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (SpatialIndex) DecodeFromPtr(p capnp.Ptr) SpatialIndex {
	return SpatialIndex(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c SpatialIndex) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c SpatialIndex) IsSame(other SpatialIndex) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c SpatialIndex) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c SpatialIndex) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A SpatialIndex_Server is a SpatialIndex with a local implementation.
type SpatialIndex_Server interface {
	Insert(context.Context, SpatialIndex_insert) error

	Done(context.Context, SpatialIndex_done) error

	Lookup(context.Context, SpatialIndex_lookup) error

	QueryTransitions(context.Context, SpatialIndex_queryTransitions) error
}

// SpatialIndex_NewServer creates a new Server from an implementation of SpatialIndex_Server.
func SpatialIndex_NewServer(s SpatialIndex_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(SpatialIndex_Methods(nil, s), s, c)
}

// SpatialIndex_ServerToClient creates a new Client from an implementation of SpatialIndex_Server.
// The caller is responsible for calling Release on the returned Client.
func SpatialIndex_ServerToClient(s SpatialIndex_Server) SpatialIndex {
	return SpatialIndex(capnp.NewClient(SpatialIndex_NewServer(s)))
}

// SpatialIndex_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func SpatialIndex_Methods(methods []server.Method, s SpatialIndex_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 4)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xfdb082e626e1958b,
			MethodID:      0,
			InterfaceName: "pkg/store/lsm/spatial_index.capnp:SpatialIndex",
			MethodName:    "insert",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Insert(ctx, SpatialIndex_insert{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xfdb082e626e1958b,
			MethodID:      1,
			InterfaceName: "pkg/store/lsm/spatial_index.capnp:SpatialIndex",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, SpatialIndex_done{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xfdb082e626e1958b,
			MethodID:      2,
			InterfaceName: "pkg/store/lsm/spatial_index.capnp:SpatialIndex",
			MethodName:    "lookup",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Lookup(ctx, SpatialIndex_lookup{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xfdb082e626e1958b,
			MethodID:      3,
			InterfaceName: "pkg/store/lsm/spatial_index.capnp:SpatialIndex",
			MethodName:    "queryTransitions",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.QueryTransitions(ctx, SpatialIndex_queryTransitions{call})
		},
	})

	return methods
}

// SpatialIndex_insert holds the state for a server call to SpatialIndex.insert.
// See server.Call for documentation.
type SpatialIndex_insert struct {
	*server.Call
}

// Args returns the call's arguments.
func (c SpatialIndex_insert) Args() SpatialIndex_insert_Params {
	return SpatialIndex_insert_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c SpatialIndex_insert) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// SpatialIndex_done holds the state for a server call to SpatialIndex.done.
// See server.Call for documentation.
type SpatialIndex_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c SpatialIndex_done) Args() SpatialIndex_done_Params {
	return SpatialIndex_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c SpatialIndex_done) AllocResults() (SpatialIndex_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return SpatialIndex_done_Results(r), err
}

// SpatialIndex_lookup holds the state for a server call to SpatialIndex.lookup.
// See server.Call for documentation.
type SpatialIndex_lookup struct {
	*server.Call
}

// Args returns the call's arguments.
func (c SpatialIndex_lookup) Args() SpatialIndex_lookup_Params {
	return SpatialIndex_lookup_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c SpatialIndex_lookup) AllocResults() (SpatialIndex_lookup_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return SpatialIndex_lookup_Results(r), err
}

// SpatialIndex_queryTransitions holds the state for a server call to SpatialIndex.queryTransitions.
// See server.Call for documentation.
type SpatialIndex_queryTransitions struct {
	*server.Call
}

// Args returns the call's arguments.
func (c SpatialIndex_queryTransitions) Args() SpatialIndex_queryTransitions_Params {
	return SpatialIndex_queryTransitions_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c SpatialIndex_queryTransitions) AllocResults() (SpatialIndex_queryTransitions_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return SpatialIndex_queryTransitions_Results(r), err
}

// SpatialIndex_List is a list of SpatialIndex.
type SpatialIndex_List = capnp.CapList[SpatialIndex]

// NewSpatialIndex_List creates a new list of SpatialIndex.
func NewSpatialIndex_List(s *capnp.Segment, sz int32) (SpatialIndex_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[SpatialIndex](l), err
}

type SpatialIndex_insert_Params capnp.Struct

// SpatialIndex_insert_Params_TypeID is the unique identifier for the type SpatialIndex_insert_Params.
const SpatialIndex_insert_Params_TypeID = 0xd76706c15772ec89

func NewSpatialIndex_insert_Params(s *capnp.Segment) (SpatialIndex_insert_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SpatialIndex_insert_Params(st), err
}

func NewRootSpatialIndex_insert_Params(s *capnp.Segment) (SpatialIndex_insert_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SpatialIndex_insert_Params(st), err
}

func ReadRootSpatialIndex_insert_Params(msg *capnp.Message) (SpatialIndex_insert_Params, error) {
	root, err := msg.Root()
	return SpatialIndex_insert_Params(root.Struct()), err
}

func (s SpatialIndex_insert_Params) String() string {
	str, _ := text.Marshal(0xd76706c15772ec89, capnp.Struct(s))
	return str
}

func (s SpatialIndex_insert_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SpatialIndex_insert_Params) DecodeFromPtr(p capnp.Ptr) SpatialIndex_insert_Params {
	return SpatialIndex_insert_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SpatialIndex_insert_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SpatialIndex_insert_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SpatialIndex_insert_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SpatialIndex_insert_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SpatialIndex_insert_Params) Edge() (GraphEdge, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return GraphEdge(p.Struct()), err
}

func (s SpatialIndex_insert_Params) HasEdge() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s SpatialIndex_insert_Params) SetEdge(v GraphEdge) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewEdge sets the edge field to a newly
// allocated GraphEdge struct, preferring placement in s's segment.
func (s SpatialIndex_insert_Params) NewEdge() (GraphEdge, error) {
	ss, err := NewGraphEdge(capnp.Struct(s).Segment())
	if err != nil {
		return GraphEdge{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// SpatialIndex_insert_Params_List is a list of SpatialIndex_insert_Params.
type SpatialIndex_insert_Params_List = capnp.StructList[SpatialIndex_insert_Params]

// NewSpatialIndex_insert_Params creates a new list of SpatialIndex_insert_Params.
func NewSpatialIndex_insert_Params_List(s *capnp.Segment, sz int32) (SpatialIndex_insert_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[SpatialIndex_insert_Params](l), err
}

// SpatialIndex_insert_Params_Future is a wrapper for a SpatialIndex_insert_Params promised by a client call.
type SpatialIndex_insert_Params_Future struct{ *capnp.Future }

func (f SpatialIndex_insert_Params_Future) Struct() (SpatialIndex_insert_Params, error) {
	p, err := f.Future.Ptr()
	return SpatialIndex_insert_Params(p.Struct()), err
}
func (p SpatialIndex_insert_Params_Future) Edge() GraphEdge_Future {
	return GraphEdge_Future{Future: p.Future.Field(0, nil)}
}

type SpatialIndex_done_Params capnp.Struct

// SpatialIndex_done_Params_TypeID is the unique identifier for the type SpatialIndex_done_Params.
const SpatialIndex_done_Params_TypeID = 0x8c90bc9bca134d52

func NewSpatialIndex_done_Params(s *capnp.Segment) (SpatialIndex_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return SpatialIndex_done_Params(st), err
}

func NewRootSpatialIndex_done_Params(s *capnp.Segment) (SpatialIndex_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return SpatialIndex_done_Params(st), err
}

func ReadRootSpatialIndex_done_Params(msg *capnp.Message) (SpatialIndex_done_Params, error) {
	root, err := msg.Root()
	return SpatialIndex_done_Params(root.Struct()), err
}

func (s SpatialIndex_done_Params) String() string {
	str, _ := text.Marshal(0x8c90bc9bca134d52, capnp.Struct(s))
	return str
}

func (s SpatialIndex_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SpatialIndex_done_Params) DecodeFromPtr(p capnp.Ptr) SpatialIndex_done_Params {
	return SpatialIndex_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SpatialIndex_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SpatialIndex_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SpatialIndex_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SpatialIndex_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// SpatialIndex_done_Params_List is a list of SpatialIndex_done_Params.
type SpatialIndex_done_Params_List = capnp.StructList[SpatialIndex_done_Params]

// NewSpatialIndex_done_Params creates a new list of SpatialIndex_done_Params.
func NewSpatialIndex_done_Params_List(s *capnp.Segment, sz int32) (SpatialIndex_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[SpatialIndex_done_Params](l), err
}

// SpatialIndex_done_Params_Future is a wrapper for a SpatialIndex_done_Params promised by a client call.
type SpatialIndex_done_Params_Future struct{ *capnp.Future }

func (f SpatialIndex_done_Params_Future) Struct() (SpatialIndex_done_Params, error) {
	p, err := f.Future.Ptr()
	return SpatialIndex_done_Params(p.Struct()), err
}

type SpatialIndex_done_Results capnp.Struct

// SpatialIndex_done_Results_TypeID is the unique identifier for the type SpatialIndex_done_Results.
const SpatialIndex_done_Results_TypeID = 0xd5cc0a4ec696f38a

func NewSpatialIndex_done_Results(s *capnp.Segment) (SpatialIndex_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return SpatialIndex_done_Results(st), err
}

func NewRootSpatialIndex_done_Results(s *capnp.Segment) (SpatialIndex_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return SpatialIndex_done_Results(st), err
}

func ReadRootSpatialIndex_done_Results(msg *capnp.Message) (SpatialIndex_done_Results, error) {
	root, err := msg.Root()
	return SpatialIndex_done_Results(root.Struct()), err
}

func (s SpatialIndex_done_Results) String() string {
	str, _ := text.Marshal(0xd5cc0a4ec696f38a, capnp.Struct(s))
	return str
}

func (s SpatialIndex_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SpatialIndex_done_Results) DecodeFromPtr(p capnp.Ptr) SpatialIndex_done_Results {
	return SpatialIndex_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SpatialIndex_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SpatialIndex_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SpatialIndex_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SpatialIndex_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// SpatialIndex_done_Results_List is a list of SpatialIndex_done_Results.
type SpatialIndex_done_Results_List = capnp.StructList[SpatialIndex_done_Results]

// NewSpatialIndex_done_Results creates a new list of SpatialIndex_done_Results.
func NewSpatialIndex_done_Results_List(s *capnp.Segment, sz int32) (SpatialIndex_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[SpatialIndex_done_Results](l), err
}

// SpatialIndex_done_Results_Future is a wrapper for a SpatialIndex_done_Results promised by a client call.
type SpatialIndex_done_Results_Future struct{ *capnp.Future }

func (f SpatialIndex_done_Results_Future) Struct() (SpatialIndex_done_Results, error) {
	p, err := f.Future.Ptr()
	return SpatialIndex_done_Results(p.Struct()), err
}

type SpatialIndex_lookup_Params capnp.Struct

// SpatialIndex_lookup_Params_TypeID is the unique identifier for the type SpatialIndex_lookup_Params.
const SpatialIndex_lookup_Params_TypeID = 0xb227a13d6bdbead1

func NewSpatialIndex_lookup_Params(s *capnp.Segment) (SpatialIndex_lookup_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SpatialIndex_lookup_Params(st), err
}

func NewRootSpatialIndex_lookup_Params(s *capnp.Segment) (SpatialIndex_lookup_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SpatialIndex_lookup_Params(st), err
}

func ReadRootSpatialIndex_lookup_Params(msg *capnp.Message) (SpatialIndex_lookup_Params, error) {
	root, err := msg.Root()
	return SpatialIndex_lookup_Params(root.Struct()), err
}

func (s SpatialIndex_lookup_Params) String() string {
	str, _ := text.Marshal(0xb227a13d6bdbead1, capnp.Struct(s))
	return str
}

func (s SpatialIndex_lookup_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SpatialIndex_lookup_Params) DecodeFromPtr(p capnp.Ptr) SpatialIndex_lookup_Params {
	return SpatialIndex_lookup_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SpatialIndex_lookup_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SpatialIndex_lookup_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SpatialIndex_lookup_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SpatialIndex_lookup_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SpatialIndex_lookup_Params) Chords() (data.Chord_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return data.Chord_List(p.List()), err
}

func (s SpatialIndex_lookup_Params) HasChords() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s SpatialIndex_lookup_Params) SetChords(v data.Chord_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewChords sets the chords field to a newly
// allocated data.Chord_List, preferring placement in s's segment.
func (s SpatialIndex_lookup_Params) NewChords(n int32) (data.Chord_List, error) {
	l, err := data.NewChord_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return data.Chord_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// SpatialIndex_lookup_Params_List is a list of SpatialIndex_lookup_Params.
type SpatialIndex_lookup_Params_List = capnp.StructList[SpatialIndex_lookup_Params]

// NewSpatialIndex_lookup_Params creates a new list of SpatialIndex_lookup_Params.
func NewSpatialIndex_lookup_Params_List(s *capnp.Segment, sz int32) (SpatialIndex_lookup_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[SpatialIndex_lookup_Params](l), err
}

// SpatialIndex_lookup_Params_Future is a wrapper for a SpatialIndex_lookup_Params promised by a client call.
type SpatialIndex_lookup_Params_Future struct{ *capnp.Future }

func (f SpatialIndex_lookup_Params_Future) Struct() (SpatialIndex_lookup_Params, error) {
	p, err := f.Future.Ptr()
	return SpatialIndex_lookup_Params(p.Struct()), err
}

type SpatialIndex_lookup_Results capnp.Struct

// SpatialIndex_lookup_Results_TypeID is the unique identifier for the type SpatialIndex_lookup_Results.
const SpatialIndex_lookup_Results_TypeID = 0xe86464012be422fc

func NewSpatialIndex_lookup_Results(s *capnp.Segment) (SpatialIndex_lookup_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return SpatialIndex_lookup_Results(st), err
}

func NewRootSpatialIndex_lookup_Results(s *capnp.Segment) (SpatialIndex_lookup_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return SpatialIndex_lookup_Results(st), err
}

func ReadRootSpatialIndex_lookup_Results(msg *capnp.Message) (SpatialIndex_lookup_Results, error) {
	root, err := msg.Root()
	return SpatialIndex_lookup_Results(root.Struct()), err
}

func (s SpatialIndex_lookup_Results) String() string {
	str, _ := text.Marshal(0xe86464012be422fc, capnp.Struct(s))
	return str
}

func (s SpatialIndex_lookup_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SpatialIndex_lookup_Results) DecodeFromPtr(p capnp.Ptr) SpatialIndex_lookup_Results {
	return SpatialIndex_lookup_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SpatialIndex_lookup_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SpatialIndex_lookup_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SpatialIndex_lookup_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SpatialIndex_lookup_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SpatialIndex_lookup_Results) Paths() (capnp.PointerList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.PointerList(p.List()), err
}

func (s SpatialIndex_lookup_Results) HasPaths() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s SpatialIndex_lookup_Results) SetPaths(v capnp.PointerList) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewPaths sets the paths field to a newly
// allocated capnp.PointerList, preferring placement in s's segment.
func (s SpatialIndex_lookup_Results) NewPaths(n int32) (capnp.PointerList, error) {
	l, err := capnp.NewPointerList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.PointerList{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s SpatialIndex_lookup_Results) MetaPaths() (capnp.PointerList, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.PointerList(p.List()), err
}

func (s SpatialIndex_lookup_Results) HasMetaPaths() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s SpatialIndex_lookup_Results) SetMetaPaths(v capnp.PointerList) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewMetaPaths sets the metaPaths field to a newly
// allocated capnp.PointerList, preferring placement in s's segment.
func (s SpatialIndex_lookup_Results) NewMetaPaths(n int32) (capnp.PointerList, error) {
	l, err := capnp.NewPointerList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.PointerList{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}

// SpatialIndex_lookup_Results_List is a list of SpatialIndex_lookup_Results.
type SpatialIndex_lookup_Results_List = capnp.StructList[SpatialIndex_lookup_Results]

// NewSpatialIndex_lookup_Results creates a new list of SpatialIndex_lookup_Results.
func NewSpatialIndex_lookup_Results_List(s *capnp.Segment, sz int32) (SpatialIndex_lookup_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[SpatialIndex_lookup_Results](l), err
}

// SpatialIndex_lookup_Results_Future is a wrapper for a SpatialIndex_lookup_Results promised by a client call.
type SpatialIndex_lookup_Results_Future struct{ *capnp.Future }

func (f SpatialIndex_lookup_Results_Future) Struct() (SpatialIndex_lookup_Results, error) {
	p, err := f.Future.Ptr()
	return SpatialIndex_lookup_Results(p.Struct()), err
}

type SpatialIndex_queryTransitions_Params capnp.Struct

// SpatialIndex_queryTransitions_Params_TypeID is the unique identifier for the type SpatialIndex_queryTransitions_Params.
const SpatialIndex_queryTransitions_Params_TypeID = 0x854c2ec877468233

func NewSpatialIndex_queryTransitions_Params(s *capnp.Segment) (SpatialIndex_queryTransitions_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return SpatialIndex_queryTransitions_Params(st), err
}

func NewRootSpatialIndex_queryTransitions_Params(s *capnp.Segment) (SpatialIndex_queryTransitions_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return SpatialIndex_queryTransitions_Params(st), err
}

func ReadRootSpatialIndex_queryTransitions_Params(msg *capnp.Message) (SpatialIndex_queryTransitions_Params, error) {
	root, err := msg.Root()
	return SpatialIndex_queryTransitions_Params(root.Struct()), err
}

func (s SpatialIndex_queryTransitions_Params) String() string {
	str, _ := text.Marshal(0x854c2ec877468233, capnp.Struct(s))
	return str
}

func (s SpatialIndex_queryTransitions_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SpatialIndex_queryTransitions_Params) DecodeFromPtr(p capnp.Ptr) SpatialIndex_queryTransitions_Params {
	return SpatialIndex_queryTransitions_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SpatialIndex_queryTransitions_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SpatialIndex_queryTransitions_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SpatialIndex_queryTransitions_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SpatialIndex_queryTransitions_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SpatialIndex_queryTransitions_Params) Left() uint8 {
	return capnp.Struct(s).Uint8(0)
}

func (s SpatialIndex_queryTransitions_Params) SetLeft(v uint8) {
	capnp.Struct(s).SetUint8(0, v)
}

func (s SpatialIndex_queryTransitions_Params) Position() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s SpatialIndex_queryTransitions_Params) SetPosition(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

// SpatialIndex_queryTransitions_Params_List is a list of SpatialIndex_queryTransitions_Params.
type SpatialIndex_queryTransitions_Params_List = capnp.StructList[SpatialIndex_queryTransitions_Params]

// NewSpatialIndex_queryTransitions_Params creates a new list of SpatialIndex_queryTransitions_Params.
func NewSpatialIndex_queryTransitions_Params_List(s *capnp.Segment, sz int32) (SpatialIndex_queryTransitions_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[SpatialIndex_queryTransitions_Params](l), err
}

// SpatialIndex_queryTransitions_Params_Future is a wrapper for a SpatialIndex_queryTransitions_Params promised by a client call.
type SpatialIndex_queryTransitions_Params_Future struct{ *capnp.Future }

func (f SpatialIndex_queryTransitions_Params_Future) Struct() (SpatialIndex_queryTransitions_Params, error) {
	p, err := f.Future.Ptr()
	return SpatialIndex_queryTransitions_Params(p.Struct()), err
}

type SpatialIndex_queryTransitions_Results capnp.Struct

// SpatialIndex_queryTransitions_Results_TypeID is the unique identifier for the type SpatialIndex_queryTransitions_Results.
const SpatialIndex_queryTransitions_Results_TypeID = 0x832dfadf68390c84

func NewSpatialIndex_queryTransitions_Results(s *capnp.Segment) (SpatialIndex_queryTransitions_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return SpatialIndex_queryTransitions_Results(st), err
}

func NewRootSpatialIndex_queryTransitions_Results(s *capnp.Segment) (SpatialIndex_queryTransitions_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return SpatialIndex_queryTransitions_Results(st), err
}

func ReadRootSpatialIndex_queryTransitions_Results(msg *capnp.Message) (SpatialIndex_queryTransitions_Results, error) {
	root, err := msg.Root()
	return SpatialIndex_queryTransitions_Results(root.Struct()), err
}

func (s SpatialIndex_queryTransitions_Results) String() string {
	str, _ := text.Marshal(0x832dfadf68390c84, capnp.Struct(s))
	return str
}

func (s SpatialIndex_queryTransitions_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SpatialIndex_queryTransitions_Results) DecodeFromPtr(p capnp.Ptr) SpatialIndex_queryTransitions_Results {
	return SpatialIndex_queryTransitions_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SpatialIndex_queryTransitions_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SpatialIndex_queryTransitions_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SpatialIndex_queryTransitions_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SpatialIndex_queryTransitions_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SpatialIndex_queryTransitions_Results) Chords() (data.Chord_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return data.Chord_List(p.List()), err
}

func (s SpatialIndex_queryTransitions_Results) HasChords() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s SpatialIndex_queryTransitions_Results) SetChords(v data.Chord_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewChords sets the chords field to a newly
// allocated data.Chord_List, preferring placement in s's segment.
func (s SpatialIndex_queryTransitions_Results) NewChords(n int32) (data.Chord_List, error) {
	l, err := data.NewChord_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return data.Chord_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s SpatialIndex_queryTransitions_Results) Metas() (data.Chord_List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return data.Chord_List(p.List()), err
}

func (s SpatialIndex_queryTransitions_Results) HasMetas() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s SpatialIndex_queryTransitions_Results) SetMetas(v data.Chord_List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewMetas sets the metas field to a newly
// allocated data.Chord_List, preferring placement in s's segment.
func (s SpatialIndex_queryTransitions_Results) NewMetas(n int32) (data.Chord_List, error) {
	l, err := data.NewChord_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return data.Chord_List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}

// SpatialIndex_queryTransitions_Results_List is a list of SpatialIndex_queryTransitions_Results.
type SpatialIndex_queryTransitions_Results_List = capnp.StructList[SpatialIndex_queryTransitions_Results]

// NewSpatialIndex_queryTransitions_Results creates a new list of SpatialIndex_queryTransitions_Results.
func NewSpatialIndex_queryTransitions_Results_List(s *capnp.Segment, sz int32) (SpatialIndex_queryTransitions_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[SpatialIndex_queryTransitions_Results](l), err
}

// SpatialIndex_queryTransitions_Results_Future is a wrapper for a SpatialIndex_queryTransitions_Results promised by a client call.
type SpatialIndex_queryTransitions_Results_Future struct{ *capnp.Future }

func (f SpatialIndex_queryTransitions_Results_Future) Struct() (SpatialIndex_queryTransitions_Results, error) {
	p, err := f.Future.Ptr()
	return SpatialIndex_queryTransitions_Results(p.Struct()), err
}

const schema_ad058c9d70413d66 = "x\xda\x9c\x94\xddk#U\x18\xc6\xdf\xe7\x9c\x99L\x10" +
	"\xd7\xe4\x90x\x1d(\xf1c\xab\xdd\xac\x1b\x84\xdd@I" +
	"\xb2\xb0\x8a\xd2,9qA\xbc\x9026\xd3$4\xc9" +
	"Lg\xa6\xb4\x15\xbd\xb0\xb6Pk\xc5\x0a~UQ\xf0" +
	"\x0f(\xa8x\xe9\x85\x15\x11\x11o\xbc\x10Q/D\x11" +
	"\x95\xa2^\xe8\x9dXF\xceL\x92\x0e\xd5n?n\xcf" +
	"y\x9e\x97\xdfy\x9f\xf3\xbe\x17\x8b\xac\xa2\xddw\xee\xc5" +
	"\x0419\xa5'\x82\xd5[\xaf\xb4\xbf\xff{\xe2Y\x12" +
	"\x05\x10\xe9\xcc *N\xf0\xab\x8c\x90\xb9\xc6\x17\x09A" +
	"q\xe5\x81\xc5\xcf.L\xad\x91,\x00D\x9a\x12\xec\xf2" +
	"\x92\x12|\x13\x0a\x1a\xb5\xcc\xe7o~\xb8\xb5\x19U\x08" +
	"\xef\xafh\xdf\x82\xb4\xe0\xcb\xbd\xef\xe6&\xdf\xb9\xeb\xfd" +
	"Am\x84\xb5\xb5=\x102U\xadL\x086\xfez\xf5" +
	"\xd3\xeb\xb7|\xf1U\xcc:\xaf\xfd\xa8\xac\xcf\xfd\xe6>" +
	"\xba\x9bh}\x1d\xb7Z\x91u9\xb4\xfe3\xf6\xd3=" +
	"h6\x7f\x8dsok\x7f*\xc1\x8e\xa6\xb0\x9e\x7f\xe5" +
	"\x87;\x7f^yw\x9f\xc4\x18\x0ff'\xab\xce[\x9b" +
	"\xfa\x0e\x11\x8a5\xfdIdL]\x19\x1e\xd7\x0dd\xf4" +
	"\x84A\x14\\\xbd\xfb\xe3\x99_\xde\xae\x06$\xc7\x80\x03" +
	"}T\xf8w\xfd\x09d\xa0t\xc5}=\x07\xb2\x03g" +
	"\xaeU\xf0|\xdbMZ\x85\xae\xd7+x\x8e\xe9w\xcc" +
	"\xeet\xa7\xdf\xb4\x96.\xcc\x98N\xdf)=\x12\x9d=" +
	"\x14\x1e\xcd/X\xee\xf2\x0d\xd7\xec{\x1d\xbfc\xf7\xbd" +
	"|\xc3\xf2\x16\xba\xbeG2\xc95\"\x0dD\xe2|\x89" +
	"H\xe69d\x85A\x00Y\xd5n1y\x89H^\xe6" +
	"\x907\x18\xca3m\xdbmz\xb8\x8dP\xe7@:x" +
	"\xads\xfb\xf5?\xbc\x0f>!\x82:\xcc\xf5,\xdf<" +
	"\xfaz\x04m\x9c\x15\xba\\7]\xb3\xe7\xc5\x99\xc7\x07" +
	"\xcc\x17c\xcc\x13\x0f\x13\xc9{9\xe4e\x86T\xd7\x9a" +
	"\xf5\x91 \x86\x84\"\xb0\xa3RD\x84$1$cT" +
	"\x89\x13R5\xed\xbe\x95W \xbc\xe7\x9d\xda\xdc\xb5\xed" +
	"\xb9\x05'_7S\xe1C\xb4\xd1C\xce\xa9\xe6'9" +
	"d\xfe\xf8>\x9f\x0dY%nt\xfd\xd33w\xfa\x9e" +
	"\xe5\xfa\xff\xc7<>`\xce2\xa4\xacf\xcbB\xfa\xe0" +
	"\x1f\x13\x90>\x03\xea\xa0A\x0d+\x17\xfe\xcfx\xd4\x97" +
	"\x06Q\xd7cQ\xd7\x1aDr\x8aC.1\xe4\x1c\xd3" +
	"o\x8f\xbavd\xf3\xd4'\xad\x9b~\x9bp\xbcvH" +
	"\xaf\x1dG_\x8e\xf0\xeb\x80Ls\x9dh\xb4@\xd0\x7f" +
	"\xef\xa3\xc5\xe2\x1b\xd3\xdbb\xbeDLX\x06\x0e6\x16" +
	"\x86\xfbG<6NL\xd4\x0c\xb0\xd1\xce\xc2p\xc1\x88" +
	"\xaa\xf2\xddo\x80\x8fV!\x86KS\x9c\xdf &\xee" +
	"0\xcaQD\x15\xa4T\xd2\x15\x94\xa3.V\x10\x0cG" +
	"\x08\xc3\x19\"\xaa\xa0\x8e\x13\xbd\xecA\xd7t\xda\xd7\x8c" +
	"f\xcbR\xcf\xca\x8e\x82xZ\xc5\xbe\xc4!WcA" +
	"<\xa3\xd2y\x8aC\xae3\x08\x86,\x18\x91XS\x83" +
	"\xb8\xca!\xb7\x18\xc0\xb3\xe0D\xe2\x05%\\\xe7\x90/" +
	"3\x08\x0dYhD\xe2%Ur\x93C\xbe~hb" +
	"sn\xa7\xd5\xbe\xe9\xfc\xe6\xc2a9\x94]\x9a\x90R" +
	"9\xff\xf7\xf8\xdf\x00\x00\x00\xff\xff\x9c\x9d\xcfT"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_ad058c9d70413d66,
		Nodes: []uint64{
			0x832dfadf68390c84,
			0x854c2ec877468233,
			0x8c90bc9bca134d52,
			0xb227a13d6bdbead1,
			0xd5cc0a4ec696f38a,
			0xd76706c15772ec89,
			0xe86464012be422fc,
			0xfdb082e626e1958b,
			0xff419ee763c22842,
		},
		Compressed: true,
	})
}
