// Code generated by capnpc-go. DO NOT EDIT.

package macro

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
	primitive "github.com/theapemachine/six/pkg/logic/lang/primitive"
)

type MacroIndex capnp.Client

// MacroIndex_TypeID is the unique identifier for the type MacroIndex.
const MacroIndex_TypeID = 0x982c65930257bacb

func (c MacroIndex) Write(ctx context.Context, params func(MacroIndex_write_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x982c65930257bacb,
			MethodID:      0,
			InterfaceName: "pkg/logic/synthesis/macro/macro_index.capnp:MacroIndex",
			MethodName:    "write",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 2}
		s.PlaceArgs = func(s capnp.Struct) error { return params(MacroIndex_write_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c MacroIndex) Done(ctx context.Context, params func(MacroIndex_done_Params) error) (MacroIndex_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x982c65930257bacb,
			MethodID:      1,
			InterfaceName: "pkg/logic/synthesis/macro/macro_index.capnp:MacroIndex",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(MacroIndex_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return MacroIndex_done_Results_Future{Future: ans.Future()}, release

}

func (c MacroIndex) ResolveGap(ctx context.Context, params func(MacroIndex_resolveGap_Params) error) (MacroIndex_resolveGap_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x982c65930257bacb,
			MethodID:      2,
			InterfaceName: "pkg/logic/synthesis/macro/macro_index.capnp:MacroIndex",
			MethodName:    "resolveGap",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 2}
		s.PlaceArgs = func(s capnp.Struct) error { return params(MacroIndex_resolveGap_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return MacroIndex_resolveGap_Results_Future{Future: ans.Future()}, release

}

func (c MacroIndex) RecordResult(ctx context.Context, params func(MacroIndex_recordResult_Params) error) (MacroIndex_recordResult_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x982c65930257bacb,
			MethodID:      3,
			InterfaceName: "pkg/logic/synthesis/macro/macro_index.capnp:MacroIndex",
			MethodName:    "recordResult",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 16, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(MacroIndex_recordResult_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return MacroIndex_recordResult_Results_Future{Future: ans.Future()}, release

}

func (c MacroIndex) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c MacroIndex) String() string {
	return "MacroIndex(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c MacroIndex) AddRef() MacroIndex {
	return MacroIndex(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c MacroIndex) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c MacroIndex) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c MacroIndex) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (MacroIndex) DecodeFromPtr(p capnp.Ptr) MacroIndex {
	return MacroIndex(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c MacroIndex) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c MacroIndex) IsSame(other MacroIndex) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c MacroIndex) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c MacroIndex) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A MacroIndex_Server is a MacroIndex with a local implementation.
type MacroIndex_Server interface {
	Write(context.Context, MacroIndex_write) error

	Done(context.Context, MacroIndex_done) error

	ResolveGap(context.Context, MacroIndex_resolveGap) error

	RecordResult(context.Context, MacroIndex_recordResult) error
}

// MacroIndex_NewServer creates a new Server from an implementation of MacroIndex_Server.
func MacroIndex_NewServer(s MacroIndex_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(MacroIndex_Methods(nil, s), s, c)
}

// MacroIndex_ServerToClient creates a new Client from an implementation of MacroIndex_Server.
// The caller is responsible for calling Release on the returned Client.
func MacroIndex_ServerToClient(s MacroIndex_Server) MacroIndex {
	return MacroIndex(capnp.NewClient(MacroIndex_NewServer(s)))
}

// MacroIndex_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func MacroIndex_Methods(methods []server.Method, s MacroIndex_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 4)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x982c65930257bacb,
			MethodID:      0,
			InterfaceName: "pkg/logic/synthesis/macro/macro_index.capnp:MacroIndex",
			MethodName:    "write",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Write(ctx, MacroIndex_write{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x982c65930257bacb,
			MethodID:      1,
			InterfaceName: "pkg/logic/synthesis/macro/macro_index.capnp:MacroIndex",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, MacroIndex_done{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x982c65930257bacb,
			MethodID:      2,
			InterfaceName: "pkg/logic/synthesis/macro/macro_index.capnp:MacroIndex",
			MethodName:    "resolveGap",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.ResolveGap(ctx, MacroIndex_resolveGap{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x982c65930257bacb,
			MethodID:      3,
			InterfaceName: "pkg/logic/synthesis/macro/macro_index.capnp:MacroIndex",
			MethodName:    "recordResult",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.RecordResult(ctx, MacroIndex_recordResult{call})
		},
	})

	return methods
}

// MacroIndex_write holds the state for a server call to MacroIndex.write.
// See server.Call for documentation.
type MacroIndex_write struct {
	*server.Call
}

// Args returns the call's arguments.
func (c MacroIndex_write) Args() MacroIndex_write_Params {
	return MacroIndex_write_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c MacroIndex_write) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// MacroIndex_done holds the state for a server call to MacroIndex.done.
// See server.Call for documentation.
type MacroIndex_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c MacroIndex_done) Args() MacroIndex_done_Params {
	return MacroIndex_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c MacroIndex_done) AllocResults() (MacroIndex_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return MacroIndex_done_Results(r), err
}

// MacroIndex_resolveGap holds the state for a server call to MacroIndex.resolveGap.
// See server.Call for documentation.
type MacroIndex_resolveGap struct {
	*server.Call
}

// Args returns the call's arguments.
func (c MacroIndex_resolveGap) Args() MacroIndex_resolveGap_Params {
	return MacroIndex_resolveGap_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c MacroIndex_resolveGap) AllocResults() (MacroIndex_resolveGap_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 24, PointerCount: 0})
	return MacroIndex_resolveGap_Results(r), err
}

// MacroIndex_recordResult holds the state for a server call to MacroIndex.recordResult.
// See server.Call for documentation.
type MacroIndex_recordResult struct {
	*server.Call
}

// Args returns the call's arguments.
func (c MacroIndex_recordResult) Args() MacroIndex_recordResult_Params {
	return MacroIndex_recordResult_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c MacroIndex_recordResult) AllocResults() (MacroIndex_recordResult_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return MacroIndex_recordResult_Results(r), err
}

// MacroIndex_List is a list of MacroIndex.
type MacroIndex_List = capnp.CapList[MacroIndex]

// NewMacroIndex_List creates a new list of MacroIndex.
func NewMacroIndex_List(s *capnp.Segment, sz int32) (MacroIndex_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[MacroIndex](l), err
}

type MacroIndex_write_Params capnp.Struct

// MacroIndex_write_Params_TypeID is the unique identifier for the type MacroIndex_write_Params.
const MacroIndex_write_Params_TypeID = 0xbbe1b8edd4375187

func NewMacroIndex_write_Params(s *capnp.Segment) (MacroIndex_write_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return MacroIndex_write_Params(st), err
}

func NewRootMacroIndex_write_Params(s *capnp.Segment) (MacroIndex_write_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return MacroIndex_write_Params(st), err
}

func ReadRootMacroIndex_write_Params(msg *capnp.Message) (MacroIndex_write_Params, error) {
	root, err := msg.Root()
	return MacroIndex_write_Params(root.Struct()), err
}

func (s MacroIndex_write_Params) String() string {
	str, _ := text.Marshal(0xbbe1b8edd4375187, capnp.Struct(s))
	return str
}

func (s MacroIndex_write_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MacroIndex_write_Params) DecodeFromPtr(p capnp.Ptr) MacroIndex_write_Params {
	return MacroIndex_write_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MacroIndex_write_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MacroIndex_write_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MacroIndex_write_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MacroIndex_write_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MacroIndex_write_Params) Start() (primitive.Value, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return primitive.Value(p.Struct()), err
}

func (s MacroIndex_write_Params) HasStart() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s MacroIndex_write_Params) SetStart(v primitive.Value) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewStart sets the start field to a newly
// allocated primitive.Value struct, preferring placement in s's segment.
func (s MacroIndex_write_Params) NewStart() (primitive.Value, error) {
	ss, err := primitive.NewValue(capnp.Struct(s).Segment())
	if err != nil {
		return primitive.Value{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s MacroIndex_write_Params) End() (primitive.Value, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return primitive.Value(p.Struct()), err
}

func (s MacroIndex_write_Params) HasEnd() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s MacroIndex_write_Params) SetEnd(v primitive.Value) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewEnd sets the end field to a newly
// allocated primitive.Value struct, preferring placement in s's segment.
func (s MacroIndex_write_Params) NewEnd() (primitive.Value, error) {
	ss, err := primitive.NewValue(capnp.Struct(s).Segment())
	if err != nil {
		return primitive.Value{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// MacroIndex_write_Params_List is a list of MacroIndex_write_Params.
type MacroIndex_write_Params_List = capnp.StructList[MacroIndex_write_Params]

// NewMacroIndex_write_Params creates a new list of MacroIndex_write_Params.
func NewMacroIndex_write_Params_List(s *capnp.Segment, sz int32) (MacroIndex_write_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[MacroIndex_write_Params](l), err
}

// MacroIndex_write_Params_Future is a wrapper for a MacroIndex_write_Params promised by a client call.
type MacroIndex_write_Params_Future struct{ *capnp.Future }

func (f MacroIndex_write_Params_Future) Struct() (MacroIndex_write_Params, error) {
	p, err := f.Future.Ptr()
	return MacroIndex_write_Params(p.Struct()), err
}
func (p MacroIndex_write_Params_Future) Start() primitive.Value_Future {
	return primitive.Value_Future{Future: p.Future.Field(0, nil)}
}
func (p MacroIndex_write_Params_Future) End() primitive.Value_Future {
	return primitive.Value_Future{Future: p.Future.Field(1, nil)}
}

type MacroIndex_done_Params capnp.Struct

// MacroIndex_done_Params_TypeID is the unique identifier for the type MacroIndex_done_Params.
const MacroIndex_done_Params_TypeID = 0x886d598024c9e70e

func NewMacroIndex_done_Params(s *capnp.Segment) (MacroIndex_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return MacroIndex_done_Params(st), err
}

func NewRootMacroIndex_done_Params(s *capnp.Segment) (MacroIndex_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return MacroIndex_done_Params(st), err
}

func ReadRootMacroIndex_done_Params(msg *capnp.Message) (MacroIndex_done_Params, error) {
	root, err := msg.Root()
	return MacroIndex_done_Params(root.Struct()), err
}

func (s MacroIndex_done_Params) String() string {
	str, _ := text.Marshal(0x886d598024c9e70e, capnp.Struct(s))
	return str
}

func (s MacroIndex_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MacroIndex_done_Params) DecodeFromPtr(p capnp.Ptr) MacroIndex_done_Params {
	return MacroIndex_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MacroIndex_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MacroIndex_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MacroIndex_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MacroIndex_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// MacroIndex_done_Params_List is a list of MacroIndex_done_Params.
type MacroIndex_done_Params_List = capnp.StructList[MacroIndex_done_Params]

// NewMacroIndex_done_Params creates a new list of MacroIndex_done_Params.
func NewMacroIndex_done_Params_List(s *capnp.Segment, sz int32) (MacroIndex_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[MacroIndex_done_Params](l), err
}

// MacroIndex_done_Params_Future is a wrapper for a MacroIndex_done_Params promised by a client call.
type MacroIndex_done_Params_Future struct{ *capnp.Future }

func (f MacroIndex_done_Params_Future) Struct() (MacroIndex_done_Params, error) {
	p, err := f.Future.Ptr()
	return MacroIndex_done_Params(p.Struct()), err
}

type MacroIndex_done_Results capnp.Struct

// MacroIndex_done_Results_TypeID is the unique identifier for the type MacroIndex_done_Results.
const MacroIndex_done_Results_TypeID = 0xece62ea9cf685941

func NewMacroIndex_done_Results(s *capnp.Segment) (MacroIndex_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return MacroIndex_done_Results(st), err
}

func NewRootMacroIndex_done_Results(s *capnp.Segment) (MacroIndex_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return MacroIndex_done_Results(st), err
}

func ReadRootMacroIndex_done_Results(msg *capnp.Message) (MacroIndex_done_Results, error) {
	root, err := msg.Root()
	return MacroIndex_done_Results(root.Struct()), err
}

func (s MacroIndex_done_Results) String() string {
	str, _ := text.Marshal(0xece62ea9cf685941, capnp.Struct(s))
	return str
}

func (s MacroIndex_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MacroIndex_done_Results) DecodeFromPtr(p capnp.Ptr) MacroIndex_done_Results {
	return MacroIndex_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MacroIndex_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MacroIndex_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MacroIndex_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MacroIndex_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MacroIndex_done_Results) KeyText() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s MacroIndex_done_Results) HasKeyText() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s MacroIndex_done_Results) KeyTextBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s MacroIndex_done_Results) SetKeyText(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s MacroIndex_done_Results) UseCount() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s MacroIndex_done_Results) SetUseCount(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s MacroIndex_done_Results) Hardened() bool {
	return capnp.Struct(s).Bit(64)
}

func (s MacroIndex_done_Results) SetHardened(v bool) {
	capnp.Struct(s).SetBit(64, v)
}

// MacroIndex_done_Results_List is a list of MacroIndex_done_Results.
type MacroIndex_done_Results_List = capnp.StructList[MacroIndex_done_Results]

// NewMacroIndex_done_Results creates a new list of MacroIndex_done_Results.
func NewMacroIndex_done_Results_List(s *capnp.Segment, sz int32) (MacroIndex_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1}, sz)
	return capnp.StructList[MacroIndex_done_Results](l), err
}

// MacroIndex_done_Results_Future is a wrapper for a MacroIndex_done_Results promised by a client call.
type MacroIndex_done_Results_Future struct{ *capnp.Future }

func (f MacroIndex_done_Results_Future) Struct() (MacroIndex_done_Results, error) {
	p, err := f.Future.Ptr()
	return MacroIndex_done_Results(p.Struct()), err
}

type MacroIndex_resolveGap_Params capnp.Struct

// MacroIndex_resolveGap_Params_TypeID is the unique identifier for the type MacroIndex_resolveGap_Params.
const MacroIndex_resolveGap_Params_TypeID = 0xf6539e8f1799878f

func NewMacroIndex_resolveGap_Params(s *capnp.Segment) (MacroIndex_resolveGap_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return MacroIndex_resolveGap_Params(st), err
}

func NewRootMacroIndex_resolveGap_Params(s *capnp.Segment) (MacroIndex_resolveGap_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return MacroIndex_resolveGap_Params(st), err
}

func ReadRootMacroIndex_resolveGap_Params(msg *capnp.Message) (MacroIndex_resolveGap_Params, error) {
	root, err := msg.Root()
	return MacroIndex_resolveGap_Params(root.Struct()), err
}

func (s MacroIndex_resolveGap_Params) String() string {
	str, _ := text.Marshal(0xf6539e8f1799878f, capnp.Struct(s))
	return str
}

func (s MacroIndex_resolveGap_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MacroIndex_resolveGap_Params) DecodeFromPtr(p capnp.Ptr) MacroIndex_resolveGap_Params {
	return MacroIndex_resolveGap_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MacroIndex_resolveGap_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MacroIndex_resolveGap_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MacroIndex_resolveGap_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MacroIndex_resolveGap_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MacroIndex_resolveGap_Params) Start() (primitive.Value, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return primitive.Value(p.Struct()), err
}

func (s MacroIndex_resolveGap_Params) HasStart() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s MacroIndex_resolveGap_Params) SetStart(v primitive.Value) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewStart sets the start field to a newly
// allocated primitive.Value struct, preferring placement in s's segment.
func (s MacroIndex_resolveGap_Params) NewStart() (primitive.Value, error) {
	ss, err := primitive.NewValue(capnp.Struct(s).Segment())
	if err != nil {
		return primitive.Value{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s MacroIndex_resolveGap_Params) End() (primitive.Value, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return primitive.Value(p.Struct()), err
}

func (s MacroIndex_resolveGap_Params) HasEnd() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s MacroIndex_resolveGap_Params) SetEnd(v primitive.Value) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewEnd sets the end field to a newly
// allocated primitive.Value struct, preferring placement in s's segment.
func (s MacroIndex_resolveGap_Params) NewEnd() (primitive.Value, error) {
	ss, err := primitive.NewValue(capnp.Struct(s).Segment())
	if err != nil {
		return primitive.Value{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// MacroIndex_resolveGap_Params_List is a list of MacroIndex_resolveGap_Params.
type MacroIndex_resolveGap_Params_List = capnp.StructList[MacroIndex_resolveGap_Params]

// NewMacroIndex_resolveGap_Params creates a new list of MacroIndex_resolveGap_Params.
func NewMacroIndex_resolveGap_Params_List(s *capnp.Segment, sz int32) (MacroIndex_resolveGap_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[MacroIndex_resolveGap_Params](l), err
}

// MacroIndex_resolveGap_Params_Future is a wrapper for a MacroIndex_resolveGap_Params promised by a client call.
type MacroIndex_resolveGap_Params_Future struct{ *capnp.Future }

func (f MacroIndex_resolveGap_Params_Future) Struct() (MacroIndex_resolveGap_Params, error) {
	p, err := f.Future.Ptr()
	return MacroIndex_resolveGap_Params(p.Struct()), err
}
func (p MacroIndex_resolveGap_Params_Future) Start() primitive.Value_Future {
	return primitive.Value_Future{Future: p.Future.Field(0, nil)}
}
func (p MacroIndex_resolveGap_Params_Future) End() primitive.Value_Future {
	return primitive.Value_Future{Future: p.Future.Field(1, nil)}
}

type MacroIndex_resolveGap_Results capnp.Struct

// MacroIndex_resolveGap_Results_TypeID is the unique identifier for the type MacroIndex_resolveGap_Results.
const MacroIndex_resolveGap_Results_TypeID = 0xff21f6dd4edaa20d

func NewMacroIndex_resolveGap_Results(s *capnp.Segment) (MacroIndex_resolveGap_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0})
	return MacroIndex_resolveGap_Results(st), err
}

func NewRootMacroIndex_resolveGap_Results(s *capnp.Segment) (MacroIndex_resolveGap_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0})
	return MacroIndex_resolveGap_Results(st), err
}

func ReadRootMacroIndex_resolveGap_Results(msg *capnp.Message) (MacroIndex_resolveGap_Results, error) {
	root, err := msg.Root()
	return MacroIndex_resolveGap_Results(root.Struct()), err
}

func (s MacroIndex_resolveGap_Results) String() string {
	str, _ := text.Marshal(0xff21f6dd4edaa20d, capnp.Struct(s))
	return str
}

func (s MacroIndex_resolveGap_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MacroIndex_resolveGap_Results) DecodeFromPtr(p capnp.Ptr) MacroIndex_resolveGap_Results {
	return MacroIndex_resolveGap_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MacroIndex_resolveGap_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MacroIndex_resolveGap_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MacroIndex_resolveGap_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MacroIndex_resolveGap_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MacroIndex_resolveGap_Results) Scale() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s MacroIndex_resolveGap_Results) SetScale(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s MacroIndex_resolveGap_Results) Translate() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s MacroIndex_resolveGap_Results) SetTranslate(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

func (s MacroIndex_resolveGap_Results) UseCount() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s MacroIndex_resolveGap_Results) SetUseCount(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s MacroIndex_resolveGap_Results) Hardened() bool {
	return capnp.Struct(s).Bit(128)
}

func (s MacroIndex_resolveGap_Results) SetHardened(v bool) {
	capnp.Struct(s).SetBit(128, v)
}

// MacroIndex_resolveGap_Results_List is a list of MacroIndex_resolveGap_Results.
type MacroIndex_resolveGap_Results_List = capnp.StructList[MacroIndex_resolveGap_Results]

// NewMacroIndex_resolveGap_Results creates a new list of MacroIndex_resolveGap_Results.
func NewMacroIndex_resolveGap_Results_List(s *capnp.Segment, sz int32) (MacroIndex_resolveGap_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0}, sz)
	return capnp.StructList[MacroIndex_resolveGap_Results](l), err
}

// MacroIndex_resolveGap_Results_Future is a wrapper for a MacroIndex_resolveGap_Results promised by a client call.
type MacroIndex_resolveGap_Results_Future struct{ *capnp.Future }

func (f MacroIndex_resolveGap_Results_Future) Struct() (MacroIndex_resolveGap_Results, error) {
	p, err := f.Future.Ptr()
	return MacroIndex_resolveGap_Results(p.Struct()), err
}

type MacroIndex_recordResult_Params capnp.Struct

// MacroIndex_recordResult_Params_TypeID is the unique identifier for the type MacroIndex_recordResult_Params.
const MacroIndex_recordResult_Params_TypeID = 0xdf63cc51a6976334

func NewMacroIndex_recordResult_Params(s *capnp.Segment) (MacroIndex_recordResult_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return MacroIndex_recordResult_Params(st), err
}

func NewRootMacroIndex_recordResult_Params(s *capnp.Segment) (MacroIndex_recordResult_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return MacroIndex_recordResult_Params(st), err
}

func ReadRootMacroIndex_recordResult_Params(msg *capnp.Message) (MacroIndex_recordResult_Params, error) {
	root, err := msg.Root()
	return MacroIndex_recordResult_Params(root.Struct()), err
}

func (s MacroIndex_recordResult_Params) String() string {
	str, _ := text.Marshal(0xdf63cc51a6976334, capnp.Struct(s))
	return str
}

func (s MacroIndex_recordResult_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MacroIndex_recordResult_Params) DecodeFromPtr(p capnp.Ptr) MacroIndex_recordResult_Params {
	return MacroIndex_recordResult_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MacroIndex_recordResult_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MacroIndex_recordResult_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MacroIndex_recordResult_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MacroIndex_recordResult_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MacroIndex_recordResult_Params) KeyData() (capnp.UInt64List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.UInt64List(p.List()), err
}

func (s MacroIndex_recordResult_Params) HasKeyData() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s MacroIndex_recordResult_Params) SetKeyData(v capnp.UInt64List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewKeyData sets the keyData field to a newly
// allocated capnp.UInt64List, preferring placement in s's segment.
func (s MacroIndex_recordResult_Params) NewKeyData(n int32) (capnp.UInt64List, error) {
	l, err := capnp.NewUInt64List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.UInt64List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s MacroIndex_recordResult_Params) PreResidue() int32 {
	return int32(capnp.Struct(s).Uint32(0))
}

func (s MacroIndex_recordResult_Params) SetPreResidue(v int32) {
	capnp.Struct(s).SetUint32(0, uint32(v))
}

func (s MacroIndex_recordResult_Params) PostResidue() int32 {
	return int32(capnp.Struct(s).Uint32(4))
}

func (s MacroIndex_recordResult_Params) SetPostResidue(v int32) {
	capnp.Struct(s).SetUint32(4, uint32(v))
}

func (s MacroIndex_recordResult_Params) Advanced() bool {
	return capnp.Struct(s).Bit(64)
}

func (s MacroIndex_recordResult_Params) SetAdvanced(v bool) {
	capnp.Struct(s).SetBit(64, v)
}

func (s MacroIndex_recordResult_Params) Stable() bool {
	return capnp.Struct(s).Bit(65)
}

func (s MacroIndex_recordResult_Params) SetStable(v bool) {
	capnp.Struct(s).SetBit(65, v)
}

// MacroIndex_recordResult_Params_List is a list of MacroIndex_recordResult_Params.
type MacroIndex_recordResult_Params_List = capnp.StructList[MacroIndex_recordResult_Params]

// NewMacroIndex_recordResult_Params creates a new list of MacroIndex_recordResult_Params.
func NewMacroIndex_recordResult_Params_List(s *capnp.Segment, sz int32) (MacroIndex_recordResult_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1}, sz)
	return capnp.StructList[MacroIndex_recordResult_Params](l), err
}

// MacroIndex_recordResult_Params_Future is a wrapper for a MacroIndex_recordResult_Params promised by a client call.
type MacroIndex_recordResult_Params_Future struct{ *capnp.Future }

func (f MacroIndex_recordResult_Params_Future) Struct() (MacroIndex_recordResult_Params, error) {
	p, err := f.Future.Ptr()
	return MacroIndex_recordResult_Params(p.Struct()), err
}

type MacroIndex_recordResult_Results capnp.Struct

// MacroIndex_recordResult_Results_TypeID is the unique identifier for the type MacroIndex_recordResult_Results.
const MacroIndex_recordResult_Results_TypeID = 0xb0cb9afe753e6b87

func NewMacroIndex_recordResult_Results(s *capnp.Segment) (MacroIndex_recordResult_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return MacroIndex_recordResult_Results(st), err
}

func NewRootMacroIndex_recordResult_Results(s *capnp.Segment) (MacroIndex_recordResult_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return MacroIndex_recordResult_Results(st), err
}

func ReadRootMacroIndex_recordResult_Results(msg *capnp.Message) (MacroIndex_recordResult_Results, error) {
	root, err := msg.Root()
	return MacroIndex_recordResult_Results(root.Struct()), err
}

func (s MacroIndex_recordResult_Results) String() string {
	str, _ := text.Marshal(0xb0cb9afe753e6b87, capnp.Struct(s))
	return str
}

func (s MacroIndex_recordResult_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MacroIndex_recordResult_Results) DecodeFromPtr(p capnp.Ptr) MacroIndex_recordResult_Results {
	return MacroIndex_recordResult_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MacroIndex_recordResult_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MacroIndex_recordResult_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MacroIndex_recordResult_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MacroIndex_recordResult_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// MacroIndex_recordResult_Results_List is a list of MacroIndex_recordResult_Results.
type MacroIndex_recordResult_Results_List = capnp.StructList[MacroIndex_recordResult_Results]

// NewMacroIndex_recordResult_Results creates a new list of MacroIndex_recordResult_Results.
func NewMacroIndex_recordResult_Results_List(s *capnp.Segment, sz int32) (MacroIndex_recordResult_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[MacroIndex_recordResult_Results](l), err
}

// MacroIndex_recordResult_Results_Future is a wrapper for a MacroIndex_recordResult_Results promised by a client call.
type MacroIndex_recordResult_Results_Future struct{ *capnp.Future }

func (f MacroIndex_recordResult_Results_Future) Struct() (MacroIndex_recordResult_Results, error) {
	p, err := f.Future.Ptr()
	return MacroIndex_recordResult_Results(p.Struct()), err
}

const schema_ad058c9d70413d6c = "x\xda\xccSAh\x1cU\x18\xfe\xbe\xf7fwRH" +
	"\xda<\xb2 \xf4\x12,\x11\x8c\xb4Mm\x0a\xc1\x82v" +
	"\xa3\x15\xdb`\xcb\xbeX\x91\x84By\xd9y6kf" +
	"g\xd7y\xb3M*\x88\xb9H<\x08U\x14l\x8a\x15" +
	"+E((\xb6\x07A\xeaE\xf0$\x15\xbcx\x12D" +
	"\xbc\xd8\x8b^\x0bzp\xe4\xedf\xa7[\xbcT\xe3\xc1" +
	"\xcb\xee\xcc7?\xdf\xfb\xbe\xef\xff\xde\x81\xa3\xa2\x1a<" +
	":2S\x86\xd0\xc7J\xe5|\xe7\xedo&\xd6\x17\x9a" +
	"o@\xcd\x10\x08B`\x9ar\xb7@\x90\xdf\xba\xf9\x82" +
	"x\xc7\xee\xbd\x08\xb5W\xe6\xf1\xe3\xb3\xed\xcbo\x96>" +
	"\x058\xfd\xbb\xb8\xc91%\xfd\xe8\x88\x0c9\xf6\xb9\x7f" +
	"\xcc7V\x9e\xe8\xfcy\xe9\xd6\xf5\x01\xa2\xcbr\xc9\x13" +
	"m\xe8\x99\xef\x7f\xfb\xe2\xe7/{_J\xc2\x7f\xda\x94" +
	"{\x048vC\xae\x82\xf9\xa1\xfa{\x1f\xebo\xeb?" +
	"A\xcfP\x00%v\xa9\x83E\x01NO\x06\xe3\x04\xf3" +
	"\xd9\x85\xe5\xef\xae\xed\xff\xe5\xd7{F\x9e/uI\x9a" +
	"\xa5\xcf\xc0\xfc\xc2\xc6\xe6\x03\x17>x\xee\xce\xe0)#" +
	"\xe59?0Y\xf6\xa7\x8c|\xf4\xc3\xc9\x1f\xef<\x98" +
	"{\x0a\xb9\xa5\xf0\xf5\xf2\xbc\x1f\xb8R\xbe\x8dV\xde^" +
	"9;\x15\xb7\xce6\xc2\xfa\x94;\x9fd\xcb\xd65\xdc" +
	"T\xd3\xd4\xd3V\xef\xf7L#\x89\xec\xda\xfe\xbai'" +
	"\xed\xc3'<r\xbc\x0bD\xad\xc4N\xd4Ljd\xd3" +
	"\x15$\xa5\xfb%9\xd2c\xa9\x91zT\x96|\x90[" +
	"q1\xb9\xf1\xd5\xea\xf4\xa53\x9b\xea\xe5\x83\x10\xca\x86" +
	"d\xb1-\xf6\xf3P\x0b\x8f@\xa8\x13!E\x11\x00\xfb" +
	"F\xd5\xec\"\x84z,\xa4,\x12f\x7fKj\xdfK" +
	"\x10\xea\xa1p|5md\xb6\xca]\xdeD\x95yj" +
	"]+>g\x9f\x814\xed\xeek\xbd\x95F\xf3\x16\xbb" +
	"\\'\xce\xaa\xac\x91\x85\xc3\xa1\x7f\x18S\x9f\xcb3M" +
	"\xf8\xbf0\xce\xdc\xbf\x0e\xbd\xab\xdb\xa7\x1e\x9a\xa6\xd3C" +
	"2\x00\x02\x02j\xf2 \xa0'$\xf5\x01AEV\xe8" +
	"\xc1}{\x00\xfd\xb0\xa4>$8\xee2\x93f\x1c\xcd" +
	"_\x0c\xe6v\x9f\xfc\xe3\x95\xaf\x01r\x14\x0cm\x12\xfd" +
	"\x1d\xfdo\xdcn\x95CW\x0a\x99\xaf>\x09\xe85I" +
	"\xfd\xae`_\xe5\xdb\x8b\x80~KR\xbf/\xa8\x04+" +
	"\xbe\xe8js\x09\xd0\x17%\xf5UA%\xab\x15_]" +
	"ue\x0e\xd0\x1fJ\xeaO\x04U0[a\x00\xa8k" +
	"\x87\x01}UR_\x17|m\xc5\x9e?j2\xc3\x9d" +
	"`M\x92; \xfcc\xdeN\xed\xbcu\x8d\x08\xb2c" +
	"\x19@0\xf0`\xcbe\x1eE\x18\x0d\xa0&:g\x92" +
	"\xba\x8d\xe0\x93\x80 \xc1#.3K\xb1\xed\xbfn\xef" +
	"\xc2\xf4\x1b\xa0\x87\x8bP\x9e\xf6\xa1T%\xf5\xb3wC" +
	"9\xee\xad\x1e\x93\xd4\xa7|(\xd5^(\xda\x835I" +
	"}\xbag\xf5\x94]\xcb8\x0c\xc1a0\xef8\xfbT" +
	"\xab\x93d^\xb8\xf7\xbd\x03\xcc\x97M\x1a\xd9\xe4\x1e3" +
	"\xdb\xd8l\xef\x8a\x98vw\xafM\x07\xfc/\xfbW\xa8" +
	"\xec\x95\x90N\x8f\x16*\x8dWyZR/\x0f\xa8\xb4" +
	"\xf3\x80\x8e$u{\xa0\x7fM\x1fu,\xa9\xd7|\xff" +
	"\xd6{\xfd\xebx0\x93\xd4\xeb\xdeO\xdd\xc4\x96C\x10" +
	"\x1c\x02\xf3,5\x89\x8bM\x06\xde\xc5\xees#\x7f\x05" +
	"\x00\x00\xff\xff\x933\xce\x01"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_ad058c9d70413d6c,
		Nodes: []uint64{
			0x886d598024c9e70e,
			0x982c65930257bacb,
			0xb0cb9afe753e6b87,
			0xbbe1b8edd4375187,
			0xdf63cc51a6976334,
			0xece62ea9cf685941,
			0xf6539e8f1799878f,
			0xff21f6dd4edaa20d,
		},
		Compressed: true,
	})
}
