package vm

import (
	"unsafe"

	"math"
	"sort"

	"github.com/theapemachine/six/data"
	"github.com/theapemachine/six/eigenmode"
	"github.com/theapemachine/six/gpu/metal"
	"github.com/theapemachine/six/numeric"
	"github.com/theapemachine/six/store"
	"github.com/theapemachine/six/tokenizer"
)

const (
	// snapThreshold is the minimum resonance for a span to hold.
	snapThreshold = 0.85
	// topK is the number of alternate candidates held per probe.
	topK = 5
)

/*
Machine is the entrypoint to the architecture.
It loads the initial data into the store and is then ready for
prompting. Prompting is essentially the same thing as loading data,
and can follow the same mechanism, it just comes with some extra steps,
one of which is to generate an actual output.
*/
type Machine struct {
	loader *Loader
	primefield *store.PrimeField
	eigen *eigenmode.EigenInit
}

type machineOpts func(*Machine)

/*
NewMachine creates a new Machine.
*/
func NewMachine(opts ...machineOpts) *Machine {
	machine := &Machine{
		primefield: store.NewPrimeField(),
		eigen: eigenmode.NewEigenInit(),
	}

	for _, opt := range opts {
		opt(machine)
	}

	return machine
}

func (machine *Machine) Start() {
	for token := range machine.loader.Generate() {
		machine.primefield.Insert(token.Chord, token.TokenID)
	}
	machine.eigen.BuildMultiScaleCooccurrence(machine.primefield)
}

/*
SpanResult is the output of a single cantilever probe.
*/
type SpanResult struct {
	Index int
	Key   uint64
	Scale int
	Score float64
	Chord data.Chord
	Overlap int
}

/*
Prompt runs the full cantilever-based span retrieval with pathfinding.

For each prompt token from the loader:
 1. Build the context chord from the prompt window.
 2. Try FibWindows from largest (21) to smallest (3).
 3. For each scale, GPU scans the PrimeField via BestFill.
 4. If resonance >= snapThreshold → span holds, emit with overlap.
 5. If all scales snap → emit the best-scoring candidate at the
    smallest scale (never get stuck).
 6. Advance by overlap (scale * 0.6) to create overlapping joints
    that act as structural checksums between spans.
 7. If the next probe returns terrible scores across all scales,
    backtrack: pop the last emitted span, try the next-best
    candidate from the saved top-K alternatives.
*/
type spanFrame struct {
	result       SpanResult
	alternatives []SpanResult
	depth        int
}

/*
Prompt runs the full cantilever-based span retrieval with pathfinding.
*/
func (machine *Machine) Prompt(prompt []tokenizer.Token) chan SpanResult {
	out := make(chan SpanResult)

	go func() {
		defer close(out)

		// Create a sliding context buffer of maximum Fibonacci window size.
		maxScale := numeric.FibWindows[len(numeric.FibWindows)-1]
		contextBuf := make([]data.Chord, 0, maxScale)

		// Track the actual generated byte stream for BVP sliding window
		var generatedBytes []byte

		// 1. Fill the initial context from the prompt.
		for _, token := range prompt {
			contextBuf = append(contextBuf, token.Chord)
			generatedBytes = append(generatedBytes, byte(token.TokenID>>24))

			if len(contextBuf) > maxScale {
				contextBuf = contextBuf[1:]
			}
			// Emit prompt tokens as baseline results.
			out <- SpanResult{
				Chord: token.Chord,
				Scale: 1,
				Score: 1.0,
			}
		}

		if len(contextBuf) == 0 {
			return
		}

		// The generated output as a stack for backtracking.
		var stack []spanFrame
		var depth int

		// We assume generation continues indefinitely or until max depth.
		// For the sake of this prompt, we generate continuously.
		currentIdx := 0 // Tracks the current spatial position
		for {
			ctxScale := maxScale
			if len(generatedBytes) < maxScale {
				ctxScale = len(generatedBytes)
			}
			contextPhase := 0.0
			if ctxScale > 0 {
				contextPhase = machine.eigen.SeqCircularMeanPhase(generatedBytes[len(generatedBytes)-ctxScale:])
			}

			result, alternatives := machine.probe(contextBuf, currentIdx, contextPhase, generatedBytes)
			var advance int

			// Check if we need to backtrack.
			if result.Score < snapThreshold && len(stack) > 0 {
				// Current path is a dead end. Pop the last span and try an alternative.
				prev := stack[len(stack)-1]
				stack = stack[:len(stack)-1]

				rewound := false
				for i, alt := range prev.alternatives {
					if alt.Score >= snapThreshold*0.9 {
						// Remove this alternative so we don't try it again if we backtrack to here
						var remainingAlts []SpanResult
						if i+1 < len(prev.alternatives) {
							remainingAlts = prev.alternatives[i+1:]
						}

						stack = append(stack, spanFrame{
							result:       alt,
							alternatives: remainingAlts,
							depth:        prev.depth,
						})
						
						// Restore contextBuf to the state it was before the popped span.
						// This is complex in a streaming buffer, so a simpler backtracking
						// approach is to rebuild the context from the stack history.
						contextBuf = machine.rebuildContext(stack, maxScale)
						
						// Backtracking rewind
						rewound = true
						
						advance = alt.Scale - alt.Overlap
						if advance <= 0 { advance = 1 }
						
						var startPos uint32
						actualAdvance := 0
						for i := 0; i < advance; i++ {
							idx := alt.Index + alt.Overlap + i
							if idx >= machine.primefield.N {
								break
							}
							key := machine.primefield.Key(idx)
							pos := uint32(key & 0xFFFFFF)
							if i == 0 {
								startPos = pos
							} else if pos != startPos+uint32(i) {
								break
							}

							out <- SpanResult{
								Index: idx,
								Key:   key,
								Scale: alt.Scale,
								Score: alt.Score,
								Chord: machine.primefield.Chord(idx),
							}
							generatedBytes = append(generatedBytes, byte(key>>24))
							actualAdvance++
						}
						advance = actualAdvance
						currentIdx = int(startPos) + advance
						break
					}
				}

				if rewound {
					continue
				}

				// No viable alternatives found in backtracking — accept the newly probed best result,
				// even though it is below threshold, and we are forced to proceed forward.
				stack = append(stack, spanFrame{
					result:       result,
					alternatives: alternatives,
					depth:        depth,
				})

				advance = result.Scale - result.Overlap
				if advance <= 0 { advance = 1 }
				var startPos uint32
				actualAdvance := 0
				for i := 0; i < advance; i++ {
					idx := result.Index + result.Overlap + i
					if idx >= machine.primefield.N {
						break
					}
					key := machine.primefield.Key(idx)
					pos := uint32(key & 0xFFFFFF)
					if i == 0 {
						startPos = pos
					} else if pos != startPos+uint32(i) {
						break
					}

					out <- SpanResult{
						Index: idx,
						Key:   key,
						Scale: result.Scale,
						Score: result.Score,
						Chord: machine.primefield.Chord(idx),
					}
					generatedBytes = append(generatedBytes, byte(key>>24))
					actualAdvance++
				}
				advance = actualAdvance
				currentIdx = int(startPos) + advance
				depth++
			} else {
				// Emit the result and push to stack.
				stack = append(stack, spanFrame{
					result:       result,
					alternatives: alternatives,
					depth:        depth,
				})

				advance = result.Scale - result.Overlap
				if advance <= 0 { advance = 1 }
				var startPos uint32
				actualAdvance := 0
				for i := 0; i < advance; i++ {
					idx := result.Index + result.Overlap + i
					if idx >= machine.primefield.N {
						break
					}
					key := machine.primefield.Key(idx)
					pos := uint32(key & 0xFFFFFF)
					if i == 0 {
						startPos = pos
					} else if pos != startPos+uint32(i) {
						break
					}

					out <- SpanResult{
						Index: idx,
						Key:   key,
						Scale: result.Scale,
						Score: result.Score,
						Chord: machine.primefield.Chord(idx),
					}
					generatedBytes = append(generatedBytes, byte(key>>24))
					actualAdvance++
				}
				advance = actualAdvance
				currentIdx = int(startPos) + advance
				depth++
			}

			// If we couldn't advance at all, we've hit a hard boundary sequence end!
			if advance == 0 {
				return
			}

			// DO NOT build the BVP clamp natively from generated text! 
			// OR-aggregated bounds lack sequence order and cause Echo Loops ("are we using the generated chunk as the clamp?").
			// Instead, we shift the Boundary natively along the PrimeField struct.
			// This matches the verified Holographic read-head method!

			// We need the sequence from the corpus shifted forward by `advance` bytes.
			nextIdx := result.Index + advance
			var nextContext data.Chord
			
			// Verify nextIdx is strictly contiguous! If not, we reached the END of the sampled dataset sequence.
			// Falling back to BVP build from the dynamically generated bytes if we are at boundary!
			if nextIdx < machine.primefield.N {
				nextKey := machine.primefield.Key(nextIdx)
				expectedPos := uint32(result.Key&0xFFFFFF) + uint32(advance)
				if uint32(nextKey&0xFFFFFF) == expectedPos {
					nextContext = machine.primefield.Chord(nextIdx)
				}
			}

			// Numb nextContext indicates we crossed the Structural Read-Head boundary of a dataset sample.
			// Revert to generating our Context organically from the emitted tail
			if nextContext == (data.Chord{}) {
				ctxScale := maxScale
				if len(generatedBytes) < ctxScale {
					ctxScale = len(generatedBytes)
				}
				
				if ctxScale > 0 {
					tail := generatedBytes[len(generatedBytes)-ctxScale:]
					for _, b := range tail {
						base := tokenizer.BaseChord(b)
						for j := 0; j < numeric.ChordBlocks; j++ {
							nextContext[j] |= base[j]
						}
					}
				} else {
					nextContext = result.Chord
				}
			}

			contextBuf = append(contextBuf, nextContext)
			if len(contextBuf) > maxScale {
				contextBuf = contextBuf[1:]
			}
		}
	}()

	return out
}

func (machine *Machine) rebuildContext(stack []spanFrame, maxScale int) []data.Chord {
	var buf []data.Chord
	for _, frame := range stack {
		buf = append(buf, frame.result.Chord)
	}
	if len(buf) > maxScale {
		buf = buf[len(buf)-maxScale:]
	}
	return buf
}

/*
probe runs the cantilever directly using the BestFill GPU scan.
It falls back through FibWindows (21, 13, 8, 5, 3) to guarantee linkage!
*/
func (machine *Machine) probe(contextBuf []data.Chord, targetIdx int, contextPhase float64, generatedBytes []byte) (SpanResult, []SpanResult) {
	// The single recently advanced aggregate chord is the next BVP context query.
	latestChord := contextBuf[len(contextBuf)-1]
	
	for i := len(numeric.FibWindows) - 1; i >= 0; i-- {
		scale := numeric.FibWindows[i]
		
		// Adjust query chord based on scale? BestFill handles the exact chord.
		// Masking/shifting is implicitly matched by the LSM structure.
		topKResults := machine.probeTopK([]data.Chord{latestChord}, scale, targetIdx, contextPhase, topK, generatedBytes)
		
		if len(topKResults) > 0 {
			result := topKResults[0]
			alts := topKResults[1:]
			return result, alts
		}
	}

	return SpanResult{}, nil
}

// probeTopK executes a multi-pass BestFill to find the top K matches.
func (machine *Machine) probeTopK(buf []data.Chord, scale int, targetIdx int, contextPhase float64, k int, generatedBytes []byte) []SpanResult {
	var results []SpanResult
	
	// Keep track of original masked chords to restore them later.
	maskedIdxs := make([]int, 0, k)
	maskedChords := make([]data.Chord, 0, k)
	
	defer func() {
		// Always unmask all masked chords.
		for i, idx := range maskedIdxs {
			machine.primefield.Unmask(idx, maskedChords[i])
		}
	}()

	for range k {
		bestIdx, score, err := metal.BestFill(
			machine.primefield.Field(),
			machine.primefield.N,
			unsafe.Pointer(&buf[0]),
			targetIdx,
		)

		if err != nil || bestIdx < 0 || bestIdx >= machine.primefield.N {
			break
		}

		chord := machine.primefield.Chord(bestIdx)
		key := machine.primefield.Key(bestIdx)
		
		sym := byte(key >> 24)
		candPhase := machine.eigen.Phase[sym]
		phaseDiff := math.Abs(candPhase - contextPhase)
		if phaseDiff > math.Pi {
			phaseDiff = 2 * math.Pi - phaseDiff
		}
		
		// Subtract up to 0.15 for maximum opposite phase
		score -= (phaseDiff / math.Pi) * 0.15
		
		// Mask this best result to find the next best in the next pass.
		orig := machine.primefield.Mask(bestIdx)
		maskedIdxs = append(maskedIdxs, bestIdx)
		maskedChords = append(maskedChords, orig)

		// Overlap check
		candidateBytes := make([]byte, scale)
		for i := 0; i < scale; i++ {
			if bestIdx+i >= machine.primefield.N {
				break
			}
			candidateBytes[i] = byte(machine.primefield.Key(bestIdx+i) >> 24)
		}
		
		ovl := 0
		maxOvl := len(generatedBytes)
		if len(candidateBytes) < maxOvl {
			maxOvl = len(candidateBytes)
		}
		for o := maxOvl; o > 0; o-- {
			match := true
			for i := 0; i < o; i++ {
				if generatedBytes[len(generatedBytes)-o+i] != candidateBytes[i] {
					match = false
					break
				}
			}
			if match {
				ovl = o
				break
			}
		}
		
		newToks := len(candidateBytes) - ovl
		if newToks < 2 && len(results) > 0 { // at least 2 new bytes, unless we have nothing
			continue // Find another match that advances us!
		}
		
		results = append(results, SpanResult{
			Index: bestIdx,
			Key:   key,
			Scale: scale,
			Score: score,
			Chord: chord,
			Overlap: ovl,
		})
	}

	sort.Slice(results, func(i, j int) bool {
		return results[i].Score > results[j].Score // Descending order
	})

	return results
}

func MachineWithLoader(loader *Loader) machineOpts {
	return func(machine *Machine) {
		machine.loader = loader
	}
}