package vm

import (
	"sync/atomic"
	"testing"
	"unsafe"

	"github.com/stretchr/testify/require"
	"github.com/theapemachine/six/data"
	"github.com/theapemachine/six/geometry"
	"github.com/theapemachine/six/provider/local"
	"github.com/theapemachine/six/store"
	"github.com/theapemachine/six/tokenizer"
	"github.com/theapemachine/six/vm/generation"
)

// buildCorpus creates a realistic corpus of Python-like code snippets.
// Each entry is a complete statement, giving the system enough density
// across multiple byte values and topological events.
func buildCorpus() [][]byte {
	snippets := []string{
		"def add(a, b):\n    return a + b\n",
		"def sub(a, b):\n    return a - b\n",
		"def mul(a, b):\n    return a * b\n",
		"def div(a, b):\n    return a / b\n",
		"def square(x):\n    return x * x\n",
		"def cube(x):\n    return x * x * x\n",
		"def negate(x):\n    return -x\n",
		"def double(x):\n    return x + x\n",
		"def triple(x):\n    return x + x + x\n",
		"def identity(x):\n    return x\n",
		"for i in range(10):\n    print(i)\n",
		"for i in range(100):\n    print(i * 2)\n",
		"if x > 0:\n    return True\n",
		"if x < 0:\n    return False\n",
		"while x > 0:\n    x = x - 1\n",
		"result = []\nfor item in data:\n    result.append(item)\n",
		"total = 0\nfor n in nums:\n    total += n\n",
		"values = [x * 2 for x in range(20)]\n",
		"filtered = [x for x in items if x > 0]\n",
		"mapped = list(map(lambda x: x + 1, data))\n",
	}

	// Repeat the corpus 10x to build manifold density.
	corpus := make([][]byte, 0, len(snippets)*10)
	for range 10 {
		for _, s := range snippets {
			corpus = append(corpus, []byte(s))
		}
	}
	return corpus
}

func buildIntegrationMachine(corpus [][]byte, bestFill bestFillFn) (*Machine, *store.PrimeField) {
	pf := store.NewPrimeField()

	loader := NewLoader(
		LoaderWithStore(store.NewLSMSpatialIndex(1.0)),
		LoaderWithTokenizer(
			tokenizer.NewUniversal(
				tokenizer.TokenizerWithDataset(local.New(corpus)),
			),
		),
		LoaderWithPrimeField(pf),
	)

	opts := []machineOpts{
		MachineWithLoader(loader),
		MachineWithPrimeField(pf),
	}

	if bestFill != nil {
		opts = append(opts, MachineWithBestFill(bestFill))
	}

	return NewMachine(opts...), pf
}

func promptToChords(prompt string) []data.Chord {
	chords := make([]data.Chord, 0, len(prompt))
	for i := range len(prompt) {
		chords = append(chords, data.BaseChord(prompt[i]))
	}
	return chords
}

func collectBytes(out <-chan byte) []byte {
	res := make([]byte, 0, 64)
	for b := range out {
		res = append(res, b)
	}
	return res
}

func TestMachineIntegration_IngestsCorpusIntoManifolds(t *testing.T) {
	corpus := buildCorpus()
	machine, pf := buildIntegrationMachine(corpus, nil)
	machine.Start()

	// With 200 snippets of ~30 bytes each, we expect multiple manifolds.
	require.GreaterOrEqual(t, pf.N, 2, "corpus should produce multiple manifolds via freeze boundary")

	// Verify the SearchSnapshot returns usable data.
	ptr, n, offset := pf.SearchSnapshot()
	require.NotNil(t, ptr)
	require.Greater(t, n, 0, "dictionary should have entries")
	require.GreaterOrEqual(t, offset, 0)

	// Verify manifold data is non-trivial — check multiple cubes and faces.
	totalActive := 0
	for i := 0; i < pf.N; i++ {
		m := pf.Manifold(i)
		for cube := range 5 {
			for face := range 257 {
				totalActive += m.Cubes[cube][face].ActiveCount()
			}
		}
	}
	require.Greater(t, totalActive, 1000, "corpus should produce substantial manifold density")
}

func TestMachineIntegration_GeneratesBeyondPrompt(t *testing.T) {
	corpus := buildCorpus()
	machine, pf := buildIntegrationMachine(corpus, nil)
	machine.Start()

	// Prompt with a realistic multi-byte prefix.
	prompt := "def add("
	out := collectBytes(machine.Prompt(promptToChords(prompt), nil))

	// The prompt bytes should be echoed first.
	require.GreaterOrEqual(t, len(out), len(prompt),
		"output should include at least the prompt")

	for i, b := range []byte(prompt) {
		require.Equal(t, b, out[i], "prompt byte %d should match", i)
	}

	// After the prompt, generation should produce at least some output.
	generated := out[len(prompt):]
	require.Greater(t, len(generated), 0,
		"should generate at least one byte beyond the prompt")

	// All generated bytes should be valid ASCII (the corpus is ASCII).
	for i, b := range generated {
		require.Less(t, b, byte(128),
			"generated byte %d should be ASCII, got %d", i, b)
	}

	_ = pf // suppress unused warning
}

func TestMachineIntegration_DifferentPromptsProduceDifferentOutput(t *testing.T) {
	corpus := buildCorpus()

	machine1, _ := buildIntegrationMachine(corpus, nil)
	machine1.Start()
	out1 := collectBytes(machine1.Prompt(promptToChords("def add("), nil))

	machine2, _ := buildIntegrationMachine(corpus, nil)
	machine2.Start()
	out2 := collectBytes(machine2.Prompt(promptToChords("for i in"), nil))

	// Different prompts should produce different output.
	// At minimum, the prompts themselves differ.
	require.NotEqual(t, out1, out2, "different prompts should produce different output")
}

func TestMachineIntegration_ExpectedRealityPropagatesToBestFill(t *testing.T) {
	var sawExpectedReality atomic.Bool

	bestFill := func(_ unsafe.Pointer, _ int, _ unsafe.Pointer, expectedReality unsafe.Pointer, _ int, _ unsafe.Pointer) (int, float64, error) {
		expected := (*geometry.IcosahedralManifold)(expectedReality)
		if expected.Cubes[0][0].Has(100) {
			sawExpectedReality.Store(true)
		}
		return 0, 1.0, nil
	}

	corpus := buildCorpus()
	machine, pf := buildIntegrationMachine(corpus, bestFill)
	machine.Start()
	pf.SetMomentum(100.0)

	expectedReality := &geometry.IcosahedralManifold{}
	expectedReality.Cubes[0][0].Set(100)

	out := collectBytes(machine.Prompt(promptToChords("def "), expectedReality))
	require.NotEmpty(t, out)
	require.True(t, sawExpectedReality.Load(),
		"BestFill should have received the expectedReality with bit 100 set")
}

func TestMachineIntegration_ExpectedFieldPropagatesToBestFill(t *testing.T) {
	var sawExpectedField atomic.Bool

	bestFill := func(_ unsafe.Pointer, _ int, _ unsafe.Pointer, expectedReality unsafe.Pointer, _ int, _ unsafe.Pointer) (int, float64, error) {
		expected := (*geometry.IcosahedralManifold)(expectedReality)
		if expected.Cubes[0][0].Has(100) {
			sawExpectedField.Store(true)
		}
		return 0, 1.0, nil
	}

	corpus := buildCorpus()
	machine, pf := buildIntegrationMachine(corpus, bestFill)
	machine.Start()
	pf.SetMomentum(100.0)

	expectedField := geometry.NewExpectedField()
	expectedField.Support[0][0].Set(100)

	out := collectBytes(machine.PromptWithExpectedField(promptToChords("def "), &expectedField))
	require.NotEmpty(t, out)
	require.True(t, sawExpectedField.Load(),
		"BestFill should have received the expected field with bit 100 set")
}

func TestMachineIntegration_StopTerminatesGeneration(t *testing.T) {
	corpus := buildCorpus()
	machine, _ := buildIntegrationMachine(corpus, nil)
	machine.Start()

	// Start generation then immediately stop.
	ch := machine.Prompt(promptToChords("def "), nil)
	machine.Stop()

	// Drain the channel — it should close promptly.
	out := collectBytes(ch)
	// We just verify it doesn't hang. Some output is expected (at least prompt).
	require.GreaterOrEqual(t, len(out), 1)
}

func TestApplyEventsToContextTracksHeaderRotation(t *testing.T) {
	ctx := &geometry.IcosahedralManifold{}
	events := []int{
		geometry.EventDensitySpike,
		geometry.EventPhaseInversion,
		geometry.EventDensityTrough,
		geometry.EventLowVarianceFlux,
	}

	generation.ApplyEventsToContext(ctx, events)

	expectedRot := uint8(0)
	for _, ev := range events {
		expectedRot = geometry.StateTransitionMatrix[expectedRot][ev]
	}

	require.Equal(t, expectedRot, ctx.Header.RotState())
}
