// Code generated by capnpc-go. DO NOT EDIT.

package semantic

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
)

type Engine capnp.Client

// Engine_TypeID is the unique identifier for the type Engine.
const Engine_TypeID = 0xbb766ebbf71b27d2

func (c Engine) Prompt(ctx context.Context, params func(Engine_prompt_Params) error) (Engine_prompt_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xbb766ebbf71b27d2,
			MethodID:      0,
			InterfaceName: "pkg/logic/semantic/engine.capnp:Engine",
			MethodName:    "prompt",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Engine_prompt_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Engine_prompt_Results_Future{Future: ans.Future()}, release

}

func (c Engine) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Engine) String() string {
	return "Engine(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Engine) AddRef() Engine {
	return Engine(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Engine) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Engine) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Engine) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Engine) DecodeFromPtr(p capnp.Ptr) Engine {
	return Engine(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Engine) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Engine) IsSame(other Engine) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Engine) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Engine) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Engine_Server is a Engine with a local implementation.
type Engine_Server interface {
	Prompt(context.Context, Engine_prompt) error
}

// Engine_NewServer creates a new Server from an implementation of Engine_Server.
func Engine_NewServer(s Engine_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Engine_Methods(nil, s), s, c)
}

// Engine_ServerToClient creates a new Client from an implementation of Engine_Server.
// The caller is responsible for calling Release on the returned Client.
func Engine_ServerToClient(s Engine_Server) Engine {
	return Engine(capnp.NewClient(Engine_NewServer(s)))
}

// Engine_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Engine_Methods(methods []server.Method, s Engine_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 1)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xbb766ebbf71b27d2,
			MethodID:      0,
			InterfaceName: "pkg/logic/semantic/engine.capnp:Engine",
			MethodName:    "prompt",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Prompt(ctx, Engine_prompt{call})
		},
	})

	return methods
}

// Engine_prompt holds the state for a server call to Engine.prompt.
// See server.Call for documentation.
type Engine_prompt struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Engine_prompt) Args() Engine_prompt_Params {
	return Engine_prompt_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Engine_prompt) AllocResults() (Engine_prompt_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Engine_prompt_Results(r), err
}

// Engine_List is a list of Engine.
type Engine_List = capnp.CapList[Engine]

// NewEngine_List creates a new list of Engine.
func NewEngine_List(s *capnp.Segment, sz int32) (Engine_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Engine](l), err
}

type Engine_prompt_Params capnp.Struct

// Engine_prompt_Params_TypeID is the unique identifier for the type Engine_prompt_Params.
const Engine_prompt_Params_TypeID = 0xb191fd185627a7eb

func NewEngine_prompt_Params(s *capnp.Segment) (Engine_prompt_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Engine_prompt_Params(st), err
}

func NewRootEngine_prompt_Params(s *capnp.Segment) (Engine_prompt_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Engine_prompt_Params(st), err
}

func ReadRootEngine_prompt_Params(msg *capnp.Message) (Engine_prompt_Params, error) {
	root, err := msg.Root()
	return Engine_prompt_Params(root.Struct()), err
}

func (s Engine_prompt_Params) String() string {
	str, _ := text.Marshal(0xb191fd185627a7eb, capnp.Struct(s))
	return str
}

func (s Engine_prompt_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Engine_prompt_Params) DecodeFromPtr(p capnp.Ptr) Engine_prompt_Params {
	return Engine_prompt_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Engine_prompt_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Engine_prompt_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Engine_prompt_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Engine_prompt_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Engine_prompt_Params) Msg() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Engine_prompt_Params) HasMsg() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Engine_prompt_Params) MsgBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Engine_prompt_Params) SetMsg(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// Engine_prompt_Params_List is a list of Engine_prompt_Params.
type Engine_prompt_Params_List = capnp.StructList[Engine_prompt_Params]

// NewEngine_prompt_Params creates a new list of Engine_prompt_Params.
func NewEngine_prompt_Params_List(s *capnp.Segment, sz int32) (Engine_prompt_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Engine_prompt_Params](l), err
}

// Engine_prompt_Params_Future is a wrapper for a Engine_prompt_Params promised by a client call.
type Engine_prompt_Params_Future struct{ *capnp.Future }

func (f Engine_prompt_Params_Future) Struct() (Engine_prompt_Params, error) {
	p, err := f.Future.Ptr()
	return Engine_prompt_Params(p.Struct()), err
}

type Engine_prompt_Results capnp.Struct

// Engine_prompt_Results_TypeID is the unique identifier for the type Engine_prompt_Results.
const Engine_prompt_Results_TypeID = 0x9f3990c17eaa4e92

func NewEngine_prompt_Results(s *capnp.Segment) (Engine_prompt_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Engine_prompt_Results(st), err
}

func NewRootEngine_prompt_Results(s *capnp.Segment) (Engine_prompt_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Engine_prompt_Results(st), err
}

func ReadRootEngine_prompt_Results(msg *capnp.Message) (Engine_prompt_Results, error) {
	root, err := msg.Root()
	return Engine_prompt_Results(root.Struct()), err
}

func (s Engine_prompt_Results) String() string {
	str, _ := text.Marshal(0x9f3990c17eaa4e92, capnp.Struct(s))
	return str
}

func (s Engine_prompt_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Engine_prompt_Results) DecodeFromPtr(p capnp.Ptr) Engine_prompt_Results {
	return Engine_prompt_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Engine_prompt_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Engine_prompt_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Engine_prompt_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Engine_prompt_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Engine_prompt_Results) Result() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Engine_prompt_Results) HasResult() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Engine_prompt_Results) ResultBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Engine_prompt_Results) SetResult(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// Engine_prompt_Results_List is a list of Engine_prompt_Results.
type Engine_prompt_Results_List = capnp.StructList[Engine_prompt_Results]

// NewEngine_prompt_Results creates a new list of Engine_prompt_Results.
func NewEngine_prompt_Results_List(s *capnp.Segment, sz int32) (Engine_prompt_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Engine_prompt_Results](l), err
}

// Engine_prompt_Results_Future is a wrapper for a Engine_prompt_Results promised by a client call.
type Engine_prompt_Results_Future struct{ *capnp.Future }

func (f Engine_prompt_Results_Future) Struct() (Engine_prompt_Results, error) {
	p, err := f.Future.Ptr()
	return Engine_prompt_Results(p.Struct()), err
}

const schema_ad058c9d70413d69 = "x\xda\x12\x98\xec\xc0b\xc8\x9b\xcf\xc4\xc0\x14(\xc3\xca" +
	"\xf6\x7f\x92\xdf\xaa\xba\x83\x13,\xe73\x08\xaa320" +
	"\xb02\xb230\x18\xcb2nbd`\x14\xd6e\xb4" +
	"g`\xfc\xffz\xb9z\x98\xc4\xdf\x89\x1b\x91\x15\xf82" +
	"\xae\x02)\x88\x05+\xb8\xa4.\xfd}w^\xd9n\x06" +
	"A\x05\xe6\xff\x99\xb6\x8e\x05s{X\xd7200\x1a" +
	"\xd72Z1\x0a\xf7\x824\x08w2\xba\x0bodd" +
	"g\xd0\xf9_\x90\x9d\xae\x9f\x93\x9f\x9e\xc9\x9a\xac_\x9c" +
	"\x9a\x9b\x98W\x92\x99\xac\x9f\x9a\x97\x9e\x99\x97\xaa\x97\x9c" +
	"X\x90W`\xe5\x0a\xe1\x14\x14\xe5\xe7\x16\x94\xa8\x04\xa5" +
	"\xca\x17\x97\xe6\x94\x14\x07\xb20\xb300\xb0020" +
	"\x08\xf2Z10\x04r03\x06\x8a01\xda\x17\xa5" +
	"\x82\xa4\x19y\x18\x98\x18y\x18\x18I5= \x91\xbf" +
	"(1\x17\xc5p%\x84\xe1\xec\xb9\xc5\xe9\x18&3\xe3" +
	"2\xd9\x1ebt\x00#c \x0b3+\x03\x03<\xe0" +
	"\x18aA,(h\xc5\xc0$\xc8\xcan\x0f\xb1\xdd\x81" +
	"1\x80\x91\x11\x10\x00\x00\xff\xff6\x8emi"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_ad058c9d70413d69,
		Nodes: []uint64{
			0x9f3990c17eaa4e92,
			0xb191fd185627a7eb,
			0xbb766ebbf71b27d2,
		},
		Compressed: true,
	})
}
