package graph

import (
	"fmt"
	"math/rand"
	"os"
	"strings"
	"testing"
	"time"

	. "github.com/smartystreets/goconvey/convey"
	"github.com/theapemachine/six/data"
)

/*
TestMassiveAnomalyIsolationWithDetailedLog tests the anomaly isolation across distinct
synthetic baseline logs and sends actual telemetry to a log file showing the breakdown
of the inner mathematical processes taking place.
*/
func TestMassiveAnomalyIsolationWithDetailedLog(t *testing.T) {
	Convey("Stress Test: Detailed Logging of Geometric Occlusion", t, func() {
		// Open the requested log file
		logFile, err := os.Create("six.log")
		if err != nil {
			t.Skip("Could not create six.log")
		}
		defer logFile.Close()

		fmt.Fprintln(logFile, "==========================================================")
		fmt.Fprintln(logFile, "  SIX LOG: GEOMETRIC ANOMALY ISOLATION (CHORD HOLE PUNCH) ")
		fmt.Fprintln(logFile, "==========================================================")

		trials := 5
		successes := 0

		anomalyStr := "?query=' OR 1=1--"
		anomalyBytes := []byte(anomalyStr)
		anomalyChord, _ := data.BuildChord(anomalyBytes)

		fmt.Fprintf(logFile, "\n[INITIALIZATION]\n")
		fmt.Fprintf(logFile, "Target Attack String: %q\n", anomalyStr)
		fmt.Fprintf(logFile, "Attack Total Shape Size: %d bits\n", anomalyChord.ActiveCount())
		fmt.Fprintf(logFile, "Attack Bit Profile: %v\n\n", data.ChordPrimeIndices(&anomalyChord))

		rand.Seed(time.Now().UnixNano())

		for i := 0; i < trials; i++ {
			fmt.Fprintf(logFile, "----------------------------------------------------------\n")
			fmt.Fprintf(logFile, "TRIAL %d\n", i+1)
			fmt.Fprintf(logFile, "----------------------------------------------------------\n")

			// Generate baseline
			baselineStr := fmt.Sprintf("GET /api/v1/users?user=%d HTTP/1.1 User-Agent: Mozilla/5.0 status=200", rand.Intn(1000))
			baselineChord, _ := data.BuildChord([]byte(baselineStr))

			fmt.Fprintf(logFile, "[BASELINE]\n")
			fmt.Fprintf(logFile, "Normal String: %q\n", baselineStr)
			fmt.Fprintf(logFile, "Normal Shape Size: %d bits\n", baselineChord.ActiveCount())
			fmt.Fprintf(logFile, "Normal Bit Profile: %v\n\n", data.ChordPrimeIndices(&baselineChord))

			// The attack is the baseline + anomaly
			attackStr := baselineStr + anomalyStr
			attackChord, _ := data.BuildChord([]byte(attackStr))

			fmt.Fprintf(logFile, "[INCOMING PAYLOAD]\n")
			fmt.Fprintf(logFile, "Polluted String: %q\n", attackStr)
			fmt.Fprintf(logFile, "Polluted Shape Size (Baseline + Attack): %d bits\n", attackChord.ActiveCount())
			fmt.Fprintf(logFile, "Polluted Bit Profile: %v\n\n", data.ChordPrimeIndices(&attackChord))

			// GEOMETRIC EXTRACTION: Target AND NOT Match
			fmt.Fprintf(logFile, "[EVALUATION: CHORD HOLE PUNCH]\n")
			residue := data.ChordHole(&attackChord, &baselineChord)
			
			// We look at the intersection purely for analytical logging
			intersection := attackChord.AND(baselineChord)

			fmt.Fprintf(logFile, "MATH: Intersection (Polluted AND Baseline) = %d bits\n", intersection.ActiveCount())
			fmt.Fprintf(logFile, "MATH: Residue (Polluted AND NOT Baseline)  = %d bits\n", residue.ActiveCount())
			
			// Decode the residue bits back to characters
			residueBits := data.ChordPrimeIndices(&residue)
			fmt.Fprintf(logFile, "Residue Bit Profile: %v\n", residueBits)
			
			fmt.Fprintf(logFile, "Decoded Origin Letters matching those bits:\n")
			for _, bit := range residueBits {
				var originChars string
				for _, b := range []byte(anomalyStr) {
					singleCharChord, _ := data.BuildChord([]byte{b})
					if singleCharChord.Has(bit) {
						// Only add it if we haven't already
						if !strings.Contains(originChars, string(b)) {
							originChars += string(b)
						}
					}
				}
				fmt.Fprintf(logFile, "  Bit %03d <- generated by physical characters: [%s]\n", bit, originChars)
			}
			fmt.Fprintf(logFile, "\n")

			// What survived the hole punch?
			sim := data.ChordSimilarity(&residue, &anomalyChord)

			fmt.Fprintf(logFile, "[BREAKDOWN OF ISOLATION]\n")
			
			missing := anomalyChord.ActiveCount() - sim
			
			if missing > 0 {
				fmt.Fprintf(logFile, "WARNING: Structural Occlusion Detected!\n")
				fmt.Fprintf(logFile, "  -> %d bits of the attack were geometrically identical to the baseline.\n", missing)
				fmt.Fprintf(logFile, "  -> The baseline's structure absorbed these bits, making them invisible to this single logic gate.\n")
				fmt.Fprintf(logFile, "  -> The system was only able to isolate the %d naked, highly novel bits of the string.\n", sim)
			} else {
				fmt.Fprintf(logFile, "SUCCESS: Perfect Geometric Isolation.\n")
				fmt.Fprintf(logFile, "  -> Every single bit (%d bits) of the attack was entirely novel compared to the baseline.\n", sim)
			}
			fmt.Fprintf(logFile, "\n")

			if sim > 0 {
				successes++
			}
		}

		So(successes, ShouldEqual, trials)
	})
}
