// Code generated by capnpc-go. DO NOT EDIT.

package substrate

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
	primitive "github.com/theapemachine/six/pkg/logic/lang/primitive"
)

type GraphEdge capnp.Struct

// GraphEdge_TypeID is the unique identifier for the type GraphEdge.
const GraphEdge_TypeID = 0xf27792f1a923d6dc

func NewGraphEdge(s *capnp.Segment) (GraphEdge, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return GraphEdge(st), err
}

func NewRootGraphEdge(s *capnp.Segment) (GraphEdge, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return GraphEdge(st), err
}

func ReadRootGraphEdge(msg *capnp.Message) (GraphEdge, error) {
	root, err := msg.Root()
	return GraphEdge(root.Struct()), err
}

func (s GraphEdge) String() string {
	str, _ := text.Marshal(0xf27792f1a923d6dc, capnp.Struct(s))
	return str
}

func (s GraphEdge) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (GraphEdge) DecodeFromPtr(p capnp.Ptr) GraphEdge {
	return GraphEdge(capnp.Struct{}.DecodeFromPtr(p))
}

func (s GraphEdge) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s GraphEdge) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s GraphEdge) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s GraphEdge) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s GraphEdge) Left() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s GraphEdge) SetLeft(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s GraphEdge) Right() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s GraphEdge) SetRight(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

func (s GraphEdge) Position() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s GraphEdge) SetPosition(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

func (s GraphEdge) Value() (primitive.Value, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return primitive.Value(p.Struct()), err
}

func (s GraphEdge) HasValue() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s GraphEdge) SetValue(v primitive.Value) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewValue sets the value field to a newly
// allocated primitive.Value struct, preferring placement in s's segment.
func (s GraphEdge) NewValue() (primitive.Value, error) {
	ss, err := primitive.NewValue(capnp.Struct(s).Segment())
	if err != nil {
		return primitive.Value{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// GraphEdge_List is a list of GraphEdge.
type GraphEdge_List = capnp.StructList[GraphEdge]

// NewGraphEdge creates a new list of GraphEdge.
func NewGraphEdge_List(s *capnp.Segment, sz int32) (GraphEdge_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1}, sz)
	return capnp.StructList[GraphEdge](l), err
}

// GraphEdge_Future is a wrapper for a GraphEdge promised by a client call.
type GraphEdge_Future struct{ *capnp.Future }

func (f GraphEdge_Future) Struct() (GraphEdge, error) {
	p, err := f.Future.Ptr()
	return GraphEdge(p.Struct()), err
}
func (p GraphEdge_Future) Value() primitive.Value_Future {
	return primitive.Value_Future{Future: p.Future.Field(0, nil)}
}

type Graph capnp.Client

// Graph_TypeID is the unique identifier for the type Graph.
const Graph_TypeID = 0xd00db4bbf2cf46cb

func (c Graph) Write(ctx context.Context, params func(Graph_write_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd00db4bbf2cf46cb,
			MethodID:      0,
			InterfaceName: "pkg/logic/substrate/graph.capnp:Graph",
			MethodName:    "write",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Graph_write_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c Graph) Prompt(ctx context.Context, params func(Graph_prompt_Params) error) (Graph_prompt_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd00db4bbf2cf46cb,
			MethodID:      1,
			InterfaceName: "pkg/logic/substrate/graph.capnp:Graph",
			MethodName:    "prompt",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 2}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Graph_prompt_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Graph_prompt_Results_Future{Future: ans.Future()}, release

}

func (c Graph) Done(ctx context.Context, params func(Graph_done_Params) error) (Graph_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd00db4bbf2cf46cb,
			MethodID:      2,
			InterfaceName: "pkg/logic/substrate/graph.capnp:Graph",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Graph_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Graph_done_Results_Future{Future: ans.Future()}, release

}

func (c Graph) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Graph) String() string {
	return "Graph(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Graph) AddRef() Graph {
	return Graph(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Graph) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Graph) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Graph) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Graph) DecodeFromPtr(p capnp.Ptr) Graph {
	return Graph(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Graph) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Graph) IsSame(other Graph) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Graph) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Graph) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Graph_Server is a Graph with a local implementation.
type Graph_Server interface {
	Write(context.Context, Graph_write) error

	Prompt(context.Context, Graph_prompt) error

	Done(context.Context, Graph_done) error
}

// Graph_NewServer creates a new Server from an implementation of Graph_Server.
func Graph_NewServer(s Graph_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Graph_Methods(nil, s), s, c)
}

// Graph_ServerToClient creates a new Client from an implementation of Graph_Server.
// The caller is responsible for calling Release on the returned Client.
func Graph_ServerToClient(s Graph_Server) Graph {
	return Graph(capnp.NewClient(Graph_NewServer(s)))
}

// Graph_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Graph_Methods(methods []server.Method, s Graph_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 3)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd00db4bbf2cf46cb,
			MethodID:      0,
			InterfaceName: "pkg/logic/substrate/graph.capnp:Graph",
			MethodName:    "write",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Write(ctx, Graph_write{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd00db4bbf2cf46cb,
			MethodID:      1,
			InterfaceName: "pkg/logic/substrate/graph.capnp:Graph",
			MethodName:    "prompt",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Prompt(ctx, Graph_prompt{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd00db4bbf2cf46cb,
			MethodID:      2,
			InterfaceName: "pkg/logic/substrate/graph.capnp:Graph",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, Graph_done{call})
		},
	})

	return methods
}

// Graph_write holds the state for a server call to Graph.write.
// See server.Call for documentation.
type Graph_write struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Graph_write) Args() Graph_write_Params {
	return Graph_write_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Graph_write) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// Graph_prompt holds the state for a server call to Graph.prompt.
// See server.Call for documentation.
type Graph_prompt struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Graph_prompt) Args() Graph_prompt_Params {
	return Graph_prompt_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Graph_prompt) AllocResults() (Graph_prompt_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Graph_prompt_Results(r), err
}

// Graph_done holds the state for a server call to Graph.done.
// See server.Call for documentation.
type Graph_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Graph_done) Args() Graph_done_Params {
	return Graph_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Graph_done) AllocResults() (Graph_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Graph_done_Results(r), err
}

// Graph_List is a list of Graph.
type Graph_List = capnp.CapList[Graph]

// NewGraph_List creates a new list of Graph.
func NewGraph_List(s *capnp.Segment, sz int32) (Graph_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Graph](l), err
}

type Graph_write_Params capnp.Struct

// Graph_write_Params_TypeID is the unique identifier for the type Graph_write_Params.
const Graph_write_Params_TypeID = 0xaefe7ca74f304a81

func NewGraph_write_Params(s *capnp.Segment) (Graph_write_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Graph_write_Params(st), err
}

func NewRootGraph_write_Params(s *capnp.Segment) (Graph_write_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Graph_write_Params(st), err
}

func ReadRootGraph_write_Params(msg *capnp.Message) (Graph_write_Params, error) {
	root, err := msg.Root()
	return Graph_write_Params(root.Struct()), err
}

func (s Graph_write_Params) String() string {
	str, _ := text.Marshal(0xaefe7ca74f304a81, capnp.Struct(s))
	return str
}

func (s Graph_write_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Graph_write_Params) DecodeFromPtr(p capnp.Ptr) Graph_write_Params {
	return Graph_write_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Graph_write_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Graph_write_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Graph_write_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Graph_write_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Graph_write_Params) Key() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s Graph_write_Params) SetKey(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

// Graph_write_Params_List is a list of Graph_write_Params.
type Graph_write_Params_List = capnp.StructList[Graph_write_Params]

// NewGraph_write_Params creates a new list of Graph_write_Params.
func NewGraph_write_Params_List(s *capnp.Segment, sz int32) (Graph_write_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[Graph_write_Params](l), err
}

// Graph_write_Params_Future is a wrapper for a Graph_write_Params promised by a client call.
type Graph_write_Params_Future struct{ *capnp.Future }

func (f Graph_write_Params_Future) Struct() (Graph_write_Params, error) {
	p, err := f.Future.Ptr()
	return Graph_write_Params(p.Struct()), err
}

type Graph_prompt_Params capnp.Struct

// Graph_prompt_Params_TypeID is the unique identifier for the type Graph_prompt_Params.
const Graph_prompt_Params_TypeID = 0xacf933d1ea136925

func NewGraph_prompt_Params(s *capnp.Segment) (Graph_prompt_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Graph_prompt_Params(st), err
}

func NewRootGraph_prompt_Params(s *capnp.Segment) (Graph_prompt_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Graph_prompt_Params(st), err
}

func ReadRootGraph_prompt_Params(msg *capnp.Message) (Graph_prompt_Params, error) {
	root, err := msg.Root()
	return Graph_prompt_Params(root.Struct()), err
}

func (s Graph_prompt_Params) String() string {
	str, _ := text.Marshal(0xacf933d1ea136925, capnp.Struct(s))
	return str
}

func (s Graph_prompt_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Graph_prompt_Params) DecodeFromPtr(p capnp.Ptr) Graph_prompt_Params {
	return Graph_prompt_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Graph_prompt_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Graph_prompt_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Graph_prompt_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Graph_prompt_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Graph_prompt_Params) Paths() (capnp.PointerList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.PointerList(p.List()), err
}

func (s Graph_prompt_Params) HasPaths() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Graph_prompt_Params) SetPaths(v capnp.PointerList) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewPaths sets the paths field to a newly
// allocated capnp.PointerList, preferring placement in s's segment.
func (s Graph_prompt_Params) NewPaths(n int32) (capnp.PointerList, error) {
	l, err := capnp.NewPointerList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.PointerList{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s Graph_prompt_Params) MetaPaths() (capnp.PointerList, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.PointerList(p.List()), err
}

func (s Graph_prompt_Params) HasMetaPaths() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Graph_prompt_Params) SetMetaPaths(v capnp.PointerList) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewMetaPaths sets the metaPaths field to a newly
// allocated capnp.PointerList, preferring placement in s's segment.
func (s Graph_prompt_Params) NewMetaPaths(n int32) (capnp.PointerList, error) {
	l, err := capnp.NewPointerList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.PointerList{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}

// Graph_prompt_Params_List is a list of Graph_prompt_Params.
type Graph_prompt_Params_List = capnp.StructList[Graph_prompt_Params]

// NewGraph_prompt_Params creates a new list of Graph_prompt_Params.
func NewGraph_prompt_Params_List(s *capnp.Segment, sz int32) (Graph_prompt_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Graph_prompt_Params](l), err
}

// Graph_prompt_Params_Future is a wrapper for a Graph_prompt_Params promised by a client call.
type Graph_prompt_Params_Future struct{ *capnp.Future }

func (f Graph_prompt_Params_Future) Struct() (Graph_prompt_Params, error) {
	p, err := f.Future.Ptr()
	return Graph_prompt_Params(p.Struct()), err
}

type Graph_prompt_Results capnp.Struct

// Graph_prompt_Results_TypeID is the unique identifier for the type Graph_prompt_Results.
const Graph_prompt_Results_TypeID = 0xfe88eef4dd644993

func NewGraph_prompt_Results(s *capnp.Segment) (Graph_prompt_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Graph_prompt_Results(st), err
}

func NewRootGraph_prompt_Results(s *capnp.Segment) (Graph_prompt_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Graph_prompt_Results(st), err
}

func ReadRootGraph_prompt_Results(msg *capnp.Message) (Graph_prompt_Results, error) {
	root, err := msg.Root()
	return Graph_prompt_Results(root.Struct()), err
}

func (s Graph_prompt_Results) String() string {
	str, _ := text.Marshal(0xfe88eef4dd644993, capnp.Struct(s))
	return str
}

func (s Graph_prompt_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Graph_prompt_Results) DecodeFromPtr(p capnp.Ptr) Graph_prompt_Results {
	return Graph_prompt_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Graph_prompt_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Graph_prompt_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Graph_prompt_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Graph_prompt_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Graph_prompt_Results) Result() (capnp.PointerList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.PointerList(p.List()), err
}

func (s Graph_prompt_Results) HasResult() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Graph_prompt_Results) SetResult(v capnp.PointerList) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewResult sets the result field to a newly
// allocated capnp.PointerList, preferring placement in s's segment.
func (s Graph_prompt_Results) NewResult(n int32) (capnp.PointerList, error) {
	l, err := capnp.NewPointerList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.PointerList{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// Graph_prompt_Results_List is a list of Graph_prompt_Results.
type Graph_prompt_Results_List = capnp.StructList[Graph_prompt_Results]

// NewGraph_prompt_Results creates a new list of Graph_prompt_Results.
func NewGraph_prompt_Results_List(s *capnp.Segment, sz int32) (Graph_prompt_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Graph_prompt_Results](l), err
}

// Graph_prompt_Results_Future is a wrapper for a Graph_prompt_Results promised by a client call.
type Graph_prompt_Results_Future struct{ *capnp.Future }

func (f Graph_prompt_Results_Future) Struct() (Graph_prompt_Results, error) {
	p, err := f.Future.Ptr()
	return Graph_prompt_Results(p.Struct()), err
}

type Graph_done_Params capnp.Struct

// Graph_done_Params_TypeID is the unique identifier for the type Graph_done_Params.
const Graph_done_Params_TypeID = 0xa6c504fd8176eee7

func NewGraph_done_Params(s *capnp.Segment) (Graph_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Graph_done_Params(st), err
}

func NewRootGraph_done_Params(s *capnp.Segment) (Graph_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Graph_done_Params(st), err
}

func ReadRootGraph_done_Params(msg *capnp.Message) (Graph_done_Params, error) {
	root, err := msg.Root()
	return Graph_done_Params(root.Struct()), err
}

func (s Graph_done_Params) String() string {
	str, _ := text.Marshal(0xa6c504fd8176eee7, capnp.Struct(s))
	return str
}

func (s Graph_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Graph_done_Params) DecodeFromPtr(p capnp.Ptr) Graph_done_Params {
	return Graph_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Graph_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Graph_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Graph_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Graph_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Graph_done_Params_List is a list of Graph_done_Params.
type Graph_done_Params_List = capnp.StructList[Graph_done_Params]

// NewGraph_done_Params creates a new list of Graph_done_Params.
func NewGraph_done_Params_List(s *capnp.Segment, sz int32) (Graph_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Graph_done_Params](l), err
}

// Graph_done_Params_Future is a wrapper for a Graph_done_Params promised by a client call.
type Graph_done_Params_Future struct{ *capnp.Future }

func (f Graph_done_Params_Future) Struct() (Graph_done_Params, error) {
	p, err := f.Future.Ptr()
	return Graph_done_Params(p.Struct()), err
}

type Graph_done_Results capnp.Struct

// Graph_done_Results_TypeID is the unique identifier for the type Graph_done_Results.
const Graph_done_Results_TypeID = 0xdbe88eba4482deb4

func NewGraph_done_Results(s *capnp.Segment) (Graph_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Graph_done_Results(st), err
}

func NewRootGraph_done_Results(s *capnp.Segment) (Graph_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Graph_done_Results(st), err
}

func ReadRootGraph_done_Results(msg *capnp.Message) (Graph_done_Results, error) {
	root, err := msg.Root()
	return Graph_done_Results(root.Struct()), err
}

func (s Graph_done_Results) String() string {
	str, _ := text.Marshal(0xdbe88eba4482deb4, capnp.Struct(s))
	return str
}

func (s Graph_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Graph_done_Results) DecodeFromPtr(p capnp.Ptr) Graph_done_Results {
	return Graph_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Graph_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Graph_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Graph_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Graph_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Graph_done_Results_List is a list of Graph_done_Results.
type Graph_done_Results_List = capnp.StructList[Graph_done_Results]

// NewGraph_done_Results creates a new list of Graph_done_Results.
func NewGraph_done_Results_List(s *capnp.Segment, sz int32) (Graph_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Graph_done_Results](l), err
}

// Graph_done_Results_Future is a wrapper for a Graph_done_Results promised by a client call.
type Graph_done_Results_Future struct{ *capnp.Future }

func (f Graph_done_Results_Future) Struct() (Graph_done_Results, error) {
	p, err := f.Future.Ptr()
	return Graph_done_Results(p.Struct()), err
}

const schema_ad058c9d70413d67 = "x\xda\x94\x92MHTQ\x1c\xc5\xff\xe7\xde;\xcd\x08" +
	"\x99^f\xdc\xb4\x19+\x13\x14Js\xda$\xc4L\xa0" +
	"E\xd2\xc7\xdcY\x07\xf5\xd2\xe7\xcc\xc373\xaf\xf7\xde" +
	"8\x15m\x0c\x82\x16\xd1\xc2V\x09m\x82\x92\xa2\x02\xc1" +
	"6\xb5\x09BZ\xb4\xa8\x16\xb6\xe9ki\xb5\x10\x926" +
	"\x06\xf9\xe2\xce8O\x0bJ[\xbd\x8f{\xce\x9fs\xff" +
	"\xbf\xd3;\x8d\x8c\xd8\xd7\xfc)BL\x0dD\xb6\x04\x0b" +
	"\x8b\xe3\x13?\xc5\xdc]\x92\x9d \x12Q\xa2\xd4<\x9b" +
	"\x04\x89`\xb7\x15\xff\xfa&\xb5\xfc\xa0~\x12a\xfah" +
	"\x8e\xdd\x06!>\xcf\xaa\x84`b\xa8\xf7\xe4\xf4\xa5\x95" +
	"G\xa4:\xd1\xf0V\xf8\x94\x16\\\xe1iB\xf0\xf2\xf0" +
	"\xab\xa5\xa7\xb3\xcd\xafI\xb6\xf3 \x7f\xf0\x90s\xebZ" +
	"\xe4!\x11Rwx\x1f\xe2\x8fy\x94(>\xc3_\xc4" +
	"\xbb\xb45\x98\xfdxy\xe0\xc9\xf5\xcf\xef\xd6%\x91b" +
	"J'y\xffv\xd7\xbdo\x93\xd5%R\xed`k\x83" +
	"\"\xd0\x1a\x88\x1c\xe2mZ\x1e\x97b\x81\x10\xdc8:" +
	"\xf2\xe1\xfb\xe2\xd5\x95\xd5\xdc5\xd1\x17q_\xc7Z\x16" +
	"i*\x07\xceX\xbe\xc7.\xe7\xad\xc8p\x8fW9\xeb" +
	"\xf9\xae\xe1\x9b=y\xd7p\x0a{\x87\x0d\xa7\xe4\xf4\x1f" +
	"\xa9\xbd\x8f\x94KfG\xd6p\x8d\"\xbc\xcdz\x1c\xb7" +
	"\\t|\xed\x8a\x1aEO\xc5\xb8 \x12 \x92]}" +
	"D\xaa\x83Ce\x19$\x90\xd0\x0b\x93\xc7sD\xea\x18" +
	"\x87:\xcf\x90t\x0c\xbf\xe0a\x1b!\xcb\xd1x\xb4\x06" +
	"\xa3bh\xfb\x89\x1f\x17\x9f\x13\xd5~\x06E\xd37\xb2" +
	"\x86_ l\xac\xddd\xe6\xaak\xf9\xf5\x8b\xf2\xa2\xa7" +
	"D\x18\xb9y'\x91\x8aq\xa8\x04Ct\xcc\xbc\x80&" +
	"bhZ7\x97\xffmn\xb268\x0b\xa8\xad<B" +
	"\x14\x16\x05\xa5\x99g\xd5\xd4\xd4\xe9\x9bR\xf5\x11\x93\x83" +
	"Q l\x19\x1a\xd8\xe4\x81~brO\x14,\xec&" +
	"\x1a\xd5\x90;\xba\x89\xc9\xb6h\xb2\x969\x83t}\xdf" +
	"\x19\xb4hX\x19d\x81\xff\xa2\x9b3\xbd\x8a\xcd\xfd5" +
	"\xbc\xe2\x9f\xa6\xc1\x91<L}\xad\xd6pIF7\x91" +
	":\xc5\xa1\x0a\xeb\xb8\x9a\x1a\xf6\x19\x0ee3H\xc6\x12" +
	"`D\xd2\x1a\"R\x05\x0e\xe53\x80'\xc0\x89\xe49" +
	"-\xb4\xeb\x05h\xb1\xcdQ\x1f1b\x88\x11\x92\xae\x95" +
	"/\x84_\x81S\xf6,\xdf*\x97\x88(T\x8c\x1bv" +
	"\xc5\xfc\x83z\xeb\xe6\xa9\xaf65gz-\x15\xdb\xff" +
	"\x8d{\xff*\xf7\xfd\x0ciWo\xc8\xdf\xa8j\xbf\x02" +
	"\x00\x00\xff\xff\x0e\x993\xcb"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_ad058c9d70413d67,
		Nodes: []uint64{
			0xa6c504fd8176eee7,
			0xacf933d1ea136925,
			0xaefe7ca74f304a81,
			0xd00db4bbf2cf46cb,
			0xdbe88eba4482deb4,
			0xf27792f1a923d6dc,
			0xfe88eef4dd644993,
		},
		Compressed: true,
	})
}
