// Code generated by capnpc-go. DO NOT EDIT.

package substrate

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
	data "github.com/theapemachine/six/pkg/store/data"
)

type GraphEdge capnp.Struct

// GraphEdge_TypeID is the unique identifier for the type GraphEdge.
const GraphEdge_TypeID = 0xf27792f1a923d6dc

func NewGraphEdge(s *capnp.Segment) (GraphEdge, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return GraphEdge(st), err
}

func NewRootGraphEdge(s *capnp.Segment) (GraphEdge, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return GraphEdge(st), err
}

func ReadRootGraphEdge(msg *capnp.Message) (GraphEdge, error) {
	root, err := msg.Root()
	return GraphEdge(root.Struct()), err
}

func (s GraphEdge) String() string {
	str, _ := text.Marshal(0xf27792f1a923d6dc, capnp.Struct(s))
	return str
}

func (s GraphEdge) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (GraphEdge) DecodeFromPtr(p capnp.Ptr) GraphEdge {
	return GraphEdge(capnp.Struct{}.DecodeFromPtr(p))
}

func (s GraphEdge) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s GraphEdge) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s GraphEdge) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s GraphEdge) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s GraphEdge) Left() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s GraphEdge) SetLeft(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s GraphEdge) Right() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s GraphEdge) SetRight(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

func (s GraphEdge) Position() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s GraphEdge) SetPosition(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

func (s GraphEdge) Value() (data.Value, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return data.Value(p.Struct()), err
}

func (s GraphEdge) HasValue() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s GraphEdge) SetValue(v data.Value) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewValue sets the value field to a newly
// allocated data.Value struct, preferring placement in s's segment.
func (s GraphEdge) NewValue() (data.Value, error) {
	ss, err := data.NewValue(capnp.Struct(s).Segment())
	if err != nil {
		return data.Value{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// GraphEdge_List is a list of GraphEdge.
type GraphEdge_List = capnp.StructList[GraphEdge]

// NewGraphEdge creates a new list of GraphEdge.
func NewGraphEdge_List(s *capnp.Segment, sz int32) (GraphEdge_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1}, sz)
	return capnp.StructList[GraphEdge](l), err
}

// GraphEdge_Future is a wrapper for a GraphEdge promised by a client call.
type GraphEdge_Future struct{ *capnp.Future }

func (f GraphEdge_Future) Struct() (GraphEdge, error) {
	p, err := f.Future.Ptr()
	return GraphEdge(p.Struct()), err
}
func (p GraphEdge_Future) Value() data.Value_Future {
	return data.Value_Future{Future: p.Future.Field(0, nil)}
}

type Graph capnp.Client

// Graph_TypeID is the unique identifier for the type Graph.
const Graph_TypeID = 0xd00db4bbf2cf46cb

func (c Graph) Prompt(ctx context.Context, params func(Graph_prompt_Params) error) (Graph_prompt_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd00db4bbf2cf46cb,
			MethodID:      0,
			InterfaceName: "pkg/logic/substrate/graph.capnp:Graph",
			MethodName:    "prompt",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 2}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Graph_prompt_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Graph_prompt_Results_Future{Future: ans.Future()}, release

}

func (c Graph) Done(ctx context.Context, params func(Graph_done_Params) error) (Graph_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd00db4bbf2cf46cb,
			MethodID:      1,
			InterfaceName: "pkg/logic/substrate/graph.capnp:Graph",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Graph_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Graph_done_Results_Future{Future: ans.Future()}, release

}

func (c Graph) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Graph) String() string {
	return "Graph(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Graph) AddRef() Graph {
	return Graph(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Graph) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Graph) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Graph) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Graph) DecodeFromPtr(p capnp.Ptr) Graph {
	return Graph(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Graph) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Graph) IsSame(other Graph) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Graph) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Graph) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Graph_Server is a Graph with a local implementation.
type Graph_Server interface {
	Prompt(context.Context, Graph_prompt) error

	Done(context.Context, Graph_done) error
}

// Graph_NewServer creates a new Server from an implementation of Graph_Server.
func Graph_NewServer(s Graph_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Graph_Methods(nil, s), s, c)
}

// Graph_ServerToClient creates a new Client from an implementation of Graph_Server.
// The caller is responsible for calling Release on the returned Client.
func Graph_ServerToClient(s Graph_Server) Graph {
	return Graph(capnp.NewClient(Graph_NewServer(s)))
}

// Graph_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Graph_Methods(methods []server.Method, s Graph_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd00db4bbf2cf46cb,
			MethodID:      0,
			InterfaceName: "pkg/logic/substrate/graph.capnp:Graph",
			MethodName:    "prompt",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Prompt(ctx, Graph_prompt{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd00db4bbf2cf46cb,
			MethodID:      1,
			InterfaceName: "pkg/logic/substrate/graph.capnp:Graph",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, Graph_done{call})
		},
	})

	return methods
}

// Graph_prompt holds the state for a server call to Graph.prompt.
// See server.Call for documentation.
type Graph_prompt struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Graph_prompt) Args() Graph_prompt_Params {
	return Graph_prompt_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Graph_prompt) AllocResults() (Graph_prompt_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Graph_prompt_Results(r), err
}

// Graph_done holds the state for a server call to Graph.done.
// See server.Call for documentation.
type Graph_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Graph_done) Args() Graph_done_Params {
	return Graph_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Graph_done) AllocResults() (Graph_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Graph_done_Results(r), err
}

// Graph_List is a list of Graph.
type Graph_List = capnp.CapList[Graph]

// NewGraph_List creates a new list of Graph.
func NewGraph_List(s *capnp.Segment, sz int32) (Graph_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Graph](l), err
}

type Graph_prompt_Params capnp.Struct

// Graph_prompt_Params_TypeID is the unique identifier for the type Graph_prompt_Params.
const Graph_prompt_Params_TypeID = 0xaefe7ca74f304a81

func NewGraph_prompt_Params(s *capnp.Segment) (Graph_prompt_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Graph_prompt_Params(st), err
}

func NewRootGraph_prompt_Params(s *capnp.Segment) (Graph_prompt_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Graph_prompt_Params(st), err
}

func ReadRootGraph_prompt_Params(msg *capnp.Message) (Graph_prompt_Params, error) {
	root, err := msg.Root()
	return Graph_prompt_Params(root.Struct()), err
}

func (s Graph_prompt_Params) String() string {
	str, _ := text.Marshal(0xaefe7ca74f304a81, capnp.Struct(s))
	return str
}

func (s Graph_prompt_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Graph_prompt_Params) DecodeFromPtr(p capnp.Ptr) Graph_prompt_Params {
	return Graph_prompt_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Graph_prompt_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Graph_prompt_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Graph_prompt_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Graph_prompt_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Graph_prompt_Params) Paths() (capnp.PointerList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.PointerList(p.List()), err
}

func (s Graph_prompt_Params) HasPaths() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Graph_prompt_Params) SetPaths(v capnp.PointerList) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewPaths sets the paths field to a newly
// allocated capnp.PointerList, preferring placement in s's segment.
func (s Graph_prompt_Params) NewPaths(n int32) (capnp.PointerList, error) {
	l, err := capnp.NewPointerList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.PointerList{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s Graph_prompt_Params) MetaPaths() (capnp.PointerList, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.PointerList(p.List()), err
}

func (s Graph_prompt_Params) HasMetaPaths() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Graph_prompt_Params) SetMetaPaths(v capnp.PointerList) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewMetaPaths sets the metaPaths field to a newly
// allocated capnp.PointerList, preferring placement in s's segment.
func (s Graph_prompt_Params) NewMetaPaths(n int32) (capnp.PointerList, error) {
	l, err := capnp.NewPointerList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.PointerList{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}

// Graph_prompt_Params_List is a list of Graph_prompt_Params.
type Graph_prompt_Params_List = capnp.StructList[Graph_prompt_Params]

// NewGraph_prompt_Params creates a new list of Graph_prompt_Params.
func NewGraph_prompt_Params_List(s *capnp.Segment, sz int32) (Graph_prompt_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Graph_prompt_Params](l), err
}

// Graph_prompt_Params_Future is a wrapper for a Graph_prompt_Params promised by a client call.
type Graph_prompt_Params_Future struct{ *capnp.Future }

func (f Graph_prompt_Params_Future) Struct() (Graph_prompt_Params, error) {
	p, err := f.Future.Ptr()
	return Graph_prompt_Params(p.Struct()), err
}

type Graph_prompt_Results capnp.Struct

// Graph_prompt_Results_TypeID is the unique identifier for the type Graph_prompt_Results.
const Graph_prompt_Results_TypeID = 0x99d8b3030e521dde

func NewGraph_prompt_Results(s *capnp.Segment) (Graph_prompt_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Graph_prompt_Results(st), err
}

func NewRootGraph_prompt_Results(s *capnp.Segment) (Graph_prompt_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Graph_prompt_Results(st), err
}

func ReadRootGraph_prompt_Results(msg *capnp.Message) (Graph_prompt_Results, error) {
	root, err := msg.Root()
	return Graph_prompt_Results(root.Struct()), err
}

func (s Graph_prompt_Results) String() string {
	str, _ := text.Marshal(0x99d8b3030e521dde, capnp.Struct(s))
	return str
}

func (s Graph_prompt_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Graph_prompt_Results) DecodeFromPtr(p capnp.Ptr) Graph_prompt_Results {
	return Graph_prompt_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Graph_prompt_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Graph_prompt_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Graph_prompt_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Graph_prompt_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Graph_prompt_Results) Result() (capnp.PointerList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.PointerList(p.List()), err
}

func (s Graph_prompt_Results) HasResult() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Graph_prompt_Results) SetResult(v capnp.PointerList) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewResult sets the result field to a newly
// allocated capnp.PointerList, preferring placement in s's segment.
func (s Graph_prompt_Results) NewResult(n int32) (capnp.PointerList, error) {
	l, err := capnp.NewPointerList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.PointerList{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// Graph_prompt_Results_List is a list of Graph_prompt_Results.
type Graph_prompt_Results_List = capnp.StructList[Graph_prompt_Results]

// NewGraph_prompt_Results creates a new list of Graph_prompt_Results.
func NewGraph_prompt_Results_List(s *capnp.Segment, sz int32) (Graph_prompt_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Graph_prompt_Results](l), err
}

// Graph_prompt_Results_Future is a wrapper for a Graph_prompt_Results promised by a client call.
type Graph_prompt_Results_Future struct{ *capnp.Future }

func (f Graph_prompt_Results_Future) Struct() (Graph_prompt_Results, error) {
	p, err := f.Future.Ptr()
	return Graph_prompt_Results(p.Struct()), err
}

type Graph_done_Params capnp.Struct

// Graph_done_Params_TypeID is the unique identifier for the type Graph_done_Params.
const Graph_done_Params_TypeID = 0xacf933d1ea136925

func NewGraph_done_Params(s *capnp.Segment) (Graph_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Graph_done_Params(st), err
}

func NewRootGraph_done_Params(s *capnp.Segment) (Graph_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Graph_done_Params(st), err
}

func ReadRootGraph_done_Params(msg *capnp.Message) (Graph_done_Params, error) {
	root, err := msg.Root()
	return Graph_done_Params(root.Struct()), err
}

func (s Graph_done_Params) String() string {
	str, _ := text.Marshal(0xacf933d1ea136925, capnp.Struct(s))
	return str
}

func (s Graph_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Graph_done_Params) DecodeFromPtr(p capnp.Ptr) Graph_done_Params {
	return Graph_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Graph_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Graph_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Graph_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Graph_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Graph_done_Params_List is a list of Graph_done_Params.
type Graph_done_Params_List = capnp.StructList[Graph_done_Params]

// NewGraph_done_Params creates a new list of Graph_done_Params.
func NewGraph_done_Params_List(s *capnp.Segment, sz int32) (Graph_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Graph_done_Params](l), err
}

// Graph_done_Params_Future is a wrapper for a Graph_done_Params promised by a client call.
type Graph_done_Params_Future struct{ *capnp.Future }

func (f Graph_done_Params_Future) Struct() (Graph_done_Params, error) {
	p, err := f.Future.Ptr()
	return Graph_done_Params(p.Struct()), err
}

type Graph_done_Results capnp.Struct

// Graph_done_Results_TypeID is the unique identifier for the type Graph_done_Results.
const Graph_done_Results_TypeID = 0xfe88eef4dd644993

func NewGraph_done_Results(s *capnp.Segment) (Graph_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Graph_done_Results(st), err
}

func NewRootGraph_done_Results(s *capnp.Segment) (Graph_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Graph_done_Results(st), err
}

func ReadRootGraph_done_Results(msg *capnp.Message) (Graph_done_Results, error) {
	root, err := msg.Root()
	return Graph_done_Results(root.Struct()), err
}

func (s Graph_done_Results) String() string {
	str, _ := text.Marshal(0xfe88eef4dd644993, capnp.Struct(s))
	return str
}

func (s Graph_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Graph_done_Results) DecodeFromPtr(p capnp.Ptr) Graph_done_Results {
	return Graph_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Graph_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Graph_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Graph_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Graph_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Graph_done_Results_List is a list of Graph_done_Results.
type Graph_done_Results_List = capnp.StructList[Graph_done_Results]

// NewGraph_done_Results creates a new list of Graph_done_Results.
func NewGraph_done_Results_List(s *capnp.Segment, sz int32) (Graph_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Graph_done_Results](l), err
}

// Graph_done_Results_Future is a wrapper for a Graph_done_Results promised by a client call.
type Graph_done_Results_Future struct{ *capnp.Future }

func (f Graph_done_Results_Future) Struct() (Graph_done_Results, error) {
	p, err := f.Future.Ptr()
	return Graph_done_Results(p.Struct()), err
}

const schema_ad058c9d70413d67 = "x\xda\x94\x92\xbfO\x14_\x14\xc5\xcfyo\xf6\xbb\xfb" +
	"-\x16\x98\x0c\x14\x16\x06\x12A#\x89\xf2\xcbF\x12\x02" +
	"\x14` \x1a\xe6\xad\xad\x85O\x18g&\xce\xb2\xe3\xcc" +
	"[\xb1\xb0\xb1\xd2\xc2F\xac4\xb1\xb11\x1a\xb5\xc1\xce" +
	"?\xc1B-4\x16jg\x8c\x16&\x12-h\x183" +
	"\xbb\xee.1Q\xa1\x9a\x99{\xcf\xcd=\xf73gt" +
	"\x893\xd6X\xf9\x90\x05\xa1F\x0b\xffe\x1f\xf6W\xba" +
	"\xe4\xc6\xdb\xdb\xb0\x0f\x12(\xb0\x08Ll\xf1!A\xe7" +
	"\x7f1\x0dfC\xa1\xf3\xe5\xd5\xc4\xd6\xa3\xa6\xc0\xca\xfb" +
	"\x0bb\x9d\xb0\xb2\xab\x8b\xa3K\xf7\xafl?\xf95*" +
	"\xf2\xd6qq/\x1f]\x10k`\xf6|\xfe\xc5\xe6\xb3" +
	"\xa7\xe5\x97\xb0\x07d\xe6O\xcd\xc6wo\x14\x1e\x03\x9c" +
	"\xf8,\xc6\xe9l\xe5\x03\xce\x0fq\xcd\x99\x93E {" +
	"\xf7\xe6\xc0\x83o\xebk\x9bP\x03\x14\x1dy\xd3\xd2\x11" +
	"Y\xa13\x9b\xeb\x9c)\xf9\x09\xccn-\xac\xbc\xff\xfe" +
	"\xf5\xfa\xf6\x0e[}\xd6\x1db>\x8b/\xf8#Q\xcd" +
	"\x0f\x0b\xcb#i\xfd\\j\x12m\xbc\x11?\xd1qp" +
	"tY\xc7\xab\xf1\xe4\x89\xc6{\x9c\xd4\xaa\xb1\x19\xacx" +
	"iw=2\xa9\xb2\xa4\x05X\x04\xec\xf2$\xa0J\x92" +
	"\xea\x98\xe0t\xe2\xa5\xf5\xc8\xb0\x0bt%[\x8f\x9e\xec" +
	"\xe3\xeb\xcd\x8d\xbe\xf1\xd37\x81Fq\xb7KWj\xab" +
	"\xde\xa0\xab\x13]e\xbaG\xa3\xaeN\x8a\xba\x9a\xaaR" +
	"\xdb\xe7\xe1q@\x0dJ*W\xd0&{\x99\x17OU" +
	"\x00uRR]\x16\xec\x8f\xb5\x09\xd2\x7fz\xafzF" +
	"\xbb\xda\x04`\xba\xeb;\xe5\x9f<\xf77L\xbb\xa4*" +
	"\xc9\x02\xd0\x0e\x09[A\xb3\xc7&!\xec\xa1\";\xd1" +
	"b\xebg\xda\xfb\x86!\xecrq\xbay\xf3\x0c\xbbs" +
	"`3t\xd9\xd9l\xfd\x95\xd6\xdc\x8aO/\xdf\xde\xd3" +
	"\xc6\xa4\x87\x01uFR\x05;0y9\xbb\xb3\x92*" +
	"\x12\xb4\x85\xe8\xa5\x00\xecp\x11P\x81\xa42\x82\x94\xbd" +
	"\x94\x80}1\x17FM\x9e\xdd\x91w\xde\xb0\x04\xc1\x12" +
	"\xd8\x9f\x84~\xd0\xfe\xca\xe2Z\x1a\x9a\xb0\xb6\x0a\xa0\xad" +
	"\xb8\xa4\xa3\xba\xf7\x1b\xc4\x9e=\x86\xa5\x92\xe7O\x9a\xf4" +
	"g\x00\x00\x00\xff\xff\x00\xc2\x04r"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_ad058c9d70413d67,
		Nodes: []uint64{
			0x99d8b3030e521dde,
			0xacf933d1ea136925,
			0xaefe7ca74f304a81,
			0xd00db4bbf2cf46cb,
			0xf27792f1a923d6dc,
			0xfe88eef4dd644993,
		},
		Compressed: true,
	})
}
