// Code generated by capnpc-go. DO NOT EDIT.

package substrate

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
	data "github.com/theapemachine/six/pkg/store/data"
)

type GraphEdge capnp.Struct

// GraphEdge_TypeID is the unique identifier for the type GraphEdge.
const GraphEdge_TypeID = 0xf27792f1a923d6dc

func NewGraphEdge(s *capnp.Segment) (GraphEdge, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return GraphEdge(st), err
}

func NewRootGraphEdge(s *capnp.Segment) (GraphEdge, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return GraphEdge(st), err
}

func ReadRootGraphEdge(msg *capnp.Message) (GraphEdge, error) {
	root, err := msg.Root()
	return GraphEdge(root.Struct()), err
}

func (s GraphEdge) String() string {
	str, _ := text.Marshal(0xf27792f1a923d6dc, capnp.Struct(s))
	return str
}

func (s GraphEdge) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (GraphEdge) DecodeFromPtr(p capnp.Ptr) GraphEdge {
	return GraphEdge(capnp.Struct{}.DecodeFromPtr(p))
}

func (s GraphEdge) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s GraphEdge) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s GraphEdge) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s GraphEdge) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s GraphEdge) Left() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s GraphEdge) SetLeft(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s GraphEdge) Right() uint32 {
	return capnp.Struct(s).Uint32(4)
}

func (s GraphEdge) SetRight(v uint32) {
	capnp.Struct(s).SetUint32(4, v)
}

func (s GraphEdge) Position() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s GraphEdge) SetPosition(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

func (s GraphEdge) Value() (data.Value, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return data.Value(p.Struct()), err
}

func (s GraphEdge) HasValue() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s GraphEdge) SetValue(v data.Value) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewValue sets the value field to a newly
// allocated data.Value struct, preferring placement in s's segment.
func (s GraphEdge) NewValue() (data.Value, error) {
	ss, err := data.NewValue(capnp.Struct(s).Segment())
	if err != nil {
		return data.Value{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// GraphEdge_List is a list of GraphEdge.
type GraphEdge_List = capnp.StructList[GraphEdge]

// NewGraphEdge creates a new list of GraphEdge.
func NewGraphEdge_List(s *capnp.Segment, sz int32) (GraphEdge_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1}, sz)
	return capnp.StructList[GraphEdge](l), err
}

// GraphEdge_Future is a wrapper for a GraphEdge promised by a client call.
type GraphEdge_Future struct{ *capnp.Future }

func (f GraphEdge_Future) Struct() (GraphEdge, error) {
	p, err := f.Future.Ptr()
	return GraphEdge(p.Struct()), err
}
func (p GraphEdge_Future) Value() data.Value_Future {
	return data.Value_Future{Future: p.Future.Field(0, nil)}
}

type Graph capnp.Client

// Graph_TypeID is the unique identifier for the type Graph.
const Graph_TypeID = 0xd00db4bbf2cf46cb

func (c Graph) Write(ctx context.Context, params func(Graph_write_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd00db4bbf2cf46cb,
			MethodID:      0,
			InterfaceName: "pkg/logic/substrate/graph.capnp:Graph",
			MethodName:    "write",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Graph_write_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c Graph) Prompt(ctx context.Context, params func(Graph_prompt_Params) error) (Graph_prompt_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd00db4bbf2cf46cb,
			MethodID:      1,
			InterfaceName: "pkg/logic/substrate/graph.capnp:Graph",
			MethodName:    "prompt",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 2}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Graph_prompt_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Graph_prompt_Results_Future{Future: ans.Future()}, release

}

func (c Graph) Done(ctx context.Context, params func(Graph_done_Params) error) (Graph_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd00db4bbf2cf46cb,
			MethodID:      2,
			InterfaceName: "pkg/logic/substrate/graph.capnp:Graph",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Graph_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Graph_done_Results_Future{Future: ans.Future()}, release

}

func (c Graph) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Graph) String() string {
	return "Graph(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Graph) AddRef() Graph {
	return Graph(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Graph) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Graph) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Graph) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Graph) DecodeFromPtr(p capnp.Ptr) Graph {
	return Graph(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Graph) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Graph) IsSame(other Graph) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Graph) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Graph) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Graph_Server is a Graph with a local implementation.
type Graph_Server interface {
	Write(context.Context, Graph_write) error

	Prompt(context.Context, Graph_prompt) error

	Done(context.Context, Graph_done) error
}

// Graph_NewServer creates a new Server from an implementation of Graph_Server.
func Graph_NewServer(s Graph_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Graph_Methods(nil, s), s, c)
}

// Graph_ServerToClient creates a new Client from an implementation of Graph_Server.
// The caller is responsible for calling Release on the returned Client.
func Graph_ServerToClient(s Graph_Server) Graph {
	return Graph(capnp.NewClient(Graph_NewServer(s)))
}

// Graph_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Graph_Methods(methods []server.Method, s Graph_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 3)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd00db4bbf2cf46cb,
			MethodID:      0,
			InterfaceName: "pkg/logic/substrate/graph.capnp:Graph",
			MethodName:    "write",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Write(ctx, Graph_write{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd00db4bbf2cf46cb,
			MethodID:      1,
			InterfaceName: "pkg/logic/substrate/graph.capnp:Graph",
			MethodName:    "prompt",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Prompt(ctx, Graph_prompt{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd00db4bbf2cf46cb,
			MethodID:      2,
			InterfaceName: "pkg/logic/substrate/graph.capnp:Graph",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, Graph_done{call})
		},
	})

	return methods
}

// Graph_write holds the state for a server call to Graph.write.
// See server.Call for documentation.
type Graph_write struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Graph_write) Args() Graph_write_Params {
	return Graph_write_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Graph_write) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// Graph_prompt holds the state for a server call to Graph.prompt.
// See server.Call for documentation.
type Graph_prompt struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Graph_prompt) Args() Graph_prompt_Params {
	return Graph_prompt_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Graph_prompt) AllocResults() (Graph_prompt_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Graph_prompt_Results(r), err
}

// Graph_done holds the state for a server call to Graph.done.
// See server.Call for documentation.
type Graph_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Graph_done) Args() Graph_done_Params {
	return Graph_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Graph_done) AllocResults() (Graph_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Graph_done_Results(r), err
}

// Graph_List is a list of Graph.
type Graph_List = capnp.CapList[Graph]

// NewGraph_List creates a new list of Graph.
func NewGraph_List(s *capnp.Segment, sz int32) (Graph_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Graph](l), err
}

type Graph_write_Params capnp.Struct

// Graph_write_Params_TypeID is the unique identifier for the type Graph_write_Params.
const Graph_write_Params_TypeID = 0xaefe7ca74f304a81

func NewGraph_write_Params(s *capnp.Segment) (Graph_write_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Graph_write_Params(st), err
}

func NewRootGraph_write_Params(s *capnp.Segment) (Graph_write_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Graph_write_Params(st), err
}

func ReadRootGraph_write_Params(msg *capnp.Message) (Graph_write_Params, error) {
	root, err := msg.Root()
	return Graph_write_Params(root.Struct()), err
}

func (s Graph_write_Params) String() string {
	str, _ := text.Marshal(0xaefe7ca74f304a81, capnp.Struct(s))
	return str
}

func (s Graph_write_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Graph_write_Params) DecodeFromPtr(p capnp.Ptr) Graph_write_Params {
	return Graph_write_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Graph_write_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Graph_write_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Graph_write_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Graph_write_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Graph_write_Params) Key() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s Graph_write_Params) SetKey(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

// Graph_write_Params_List is a list of Graph_write_Params.
type Graph_write_Params_List = capnp.StructList[Graph_write_Params]

// NewGraph_write_Params creates a new list of Graph_write_Params.
func NewGraph_write_Params_List(s *capnp.Segment, sz int32) (Graph_write_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[Graph_write_Params](l), err
}

// Graph_write_Params_Future is a wrapper for a Graph_write_Params promised by a client call.
type Graph_write_Params_Future struct{ *capnp.Future }

func (f Graph_write_Params_Future) Struct() (Graph_write_Params, error) {
	p, err := f.Future.Ptr()
	return Graph_write_Params(p.Struct()), err
}

type Graph_prompt_Params capnp.Struct

// Graph_prompt_Params_TypeID is the unique identifier for the type Graph_prompt_Params.
const Graph_prompt_Params_TypeID = 0xacf933d1ea136925

func NewGraph_prompt_Params(s *capnp.Segment) (Graph_prompt_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Graph_prompt_Params(st), err
}

func NewRootGraph_prompt_Params(s *capnp.Segment) (Graph_prompt_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Graph_prompt_Params(st), err
}

func ReadRootGraph_prompt_Params(msg *capnp.Message) (Graph_prompt_Params, error) {
	root, err := msg.Root()
	return Graph_prompt_Params(root.Struct()), err
}

func (s Graph_prompt_Params) String() string {
	str, _ := text.Marshal(0xacf933d1ea136925, capnp.Struct(s))
	return str
}

func (s Graph_prompt_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Graph_prompt_Params) DecodeFromPtr(p capnp.Ptr) Graph_prompt_Params {
	return Graph_prompt_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Graph_prompt_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Graph_prompt_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Graph_prompt_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Graph_prompt_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Graph_prompt_Params) Paths() (capnp.PointerList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.PointerList(p.List()), err
}

func (s Graph_prompt_Params) HasPaths() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Graph_prompt_Params) SetPaths(v capnp.PointerList) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewPaths sets the paths field to a newly
// allocated capnp.PointerList, preferring placement in s's segment.
func (s Graph_prompt_Params) NewPaths(n int32) (capnp.PointerList, error) {
	l, err := capnp.NewPointerList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.PointerList{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s Graph_prompt_Params) MetaPaths() (capnp.PointerList, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.PointerList(p.List()), err
}

func (s Graph_prompt_Params) HasMetaPaths() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Graph_prompt_Params) SetMetaPaths(v capnp.PointerList) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewMetaPaths sets the metaPaths field to a newly
// allocated capnp.PointerList, preferring placement in s's segment.
func (s Graph_prompt_Params) NewMetaPaths(n int32) (capnp.PointerList, error) {
	l, err := capnp.NewPointerList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.PointerList{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}

// Graph_prompt_Params_List is a list of Graph_prompt_Params.
type Graph_prompt_Params_List = capnp.StructList[Graph_prompt_Params]

// NewGraph_prompt_Params creates a new list of Graph_prompt_Params.
func NewGraph_prompt_Params_List(s *capnp.Segment, sz int32) (Graph_prompt_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Graph_prompt_Params](l), err
}

// Graph_prompt_Params_Future is a wrapper for a Graph_prompt_Params promised by a client call.
type Graph_prompt_Params_Future struct{ *capnp.Future }

func (f Graph_prompt_Params_Future) Struct() (Graph_prompt_Params, error) {
	p, err := f.Future.Ptr()
	return Graph_prompt_Params(p.Struct()), err
}

type Graph_prompt_Results capnp.Struct

// Graph_prompt_Results_TypeID is the unique identifier for the type Graph_prompt_Results.
const Graph_prompt_Results_TypeID = 0xfe88eef4dd644993

func NewGraph_prompt_Results(s *capnp.Segment) (Graph_prompt_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Graph_prompt_Results(st), err
}

func NewRootGraph_prompt_Results(s *capnp.Segment) (Graph_prompt_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Graph_prompt_Results(st), err
}

func ReadRootGraph_prompt_Results(msg *capnp.Message) (Graph_prompt_Results, error) {
	root, err := msg.Root()
	return Graph_prompt_Results(root.Struct()), err
}

func (s Graph_prompt_Results) String() string {
	str, _ := text.Marshal(0xfe88eef4dd644993, capnp.Struct(s))
	return str
}

func (s Graph_prompt_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Graph_prompt_Results) DecodeFromPtr(p capnp.Ptr) Graph_prompt_Results {
	return Graph_prompt_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Graph_prompt_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Graph_prompt_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Graph_prompt_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Graph_prompt_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Graph_prompt_Results) Result() (capnp.PointerList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.PointerList(p.List()), err
}

func (s Graph_prompt_Results) HasResult() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Graph_prompt_Results) SetResult(v capnp.PointerList) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewResult sets the result field to a newly
// allocated capnp.PointerList, preferring placement in s's segment.
func (s Graph_prompt_Results) NewResult(n int32) (capnp.PointerList, error) {
	l, err := capnp.NewPointerList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.PointerList{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// Graph_prompt_Results_List is a list of Graph_prompt_Results.
type Graph_prompt_Results_List = capnp.StructList[Graph_prompt_Results]

// NewGraph_prompt_Results creates a new list of Graph_prompt_Results.
func NewGraph_prompt_Results_List(s *capnp.Segment, sz int32) (Graph_prompt_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Graph_prompt_Results](l), err
}

// Graph_prompt_Results_Future is a wrapper for a Graph_prompt_Results promised by a client call.
type Graph_prompt_Results_Future struct{ *capnp.Future }

func (f Graph_prompt_Results_Future) Struct() (Graph_prompt_Results, error) {
	p, err := f.Future.Ptr()
	return Graph_prompt_Results(p.Struct()), err
}

type Graph_done_Params capnp.Struct

// Graph_done_Params_TypeID is the unique identifier for the type Graph_done_Params.
const Graph_done_Params_TypeID = 0xa6c504fd8176eee7

func NewGraph_done_Params(s *capnp.Segment) (Graph_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Graph_done_Params(st), err
}

func NewRootGraph_done_Params(s *capnp.Segment) (Graph_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Graph_done_Params(st), err
}

func ReadRootGraph_done_Params(msg *capnp.Message) (Graph_done_Params, error) {
	root, err := msg.Root()
	return Graph_done_Params(root.Struct()), err
}

func (s Graph_done_Params) String() string {
	str, _ := text.Marshal(0xa6c504fd8176eee7, capnp.Struct(s))
	return str
}

func (s Graph_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Graph_done_Params) DecodeFromPtr(p capnp.Ptr) Graph_done_Params {
	return Graph_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Graph_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Graph_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Graph_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Graph_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Graph_done_Params_List is a list of Graph_done_Params.
type Graph_done_Params_List = capnp.StructList[Graph_done_Params]

// NewGraph_done_Params creates a new list of Graph_done_Params.
func NewGraph_done_Params_List(s *capnp.Segment, sz int32) (Graph_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Graph_done_Params](l), err
}

// Graph_done_Params_Future is a wrapper for a Graph_done_Params promised by a client call.
type Graph_done_Params_Future struct{ *capnp.Future }

func (f Graph_done_Params_Future) Struct() (Graph_done_Params, error) {
	p, err := f.Future.Ptr()
	return Graph_done_Params(p.Struct()), err
}

type Graph_done_Results capnp.Struct

// Graph_done_Results_TypeID is the unique identifier for the type Graph_done_Results.
const Graph_done_Results_TypeID = 0xdbe88eba4482deb4

func NewGraph_done_Results(s *capnp.Segment) (Graph_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Graph_done_Results(st), err
}

func NewRootGraph_done_Results(s *capnp.Segment) (Graph_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Graph_done_Results(st), err
}

func ReadRootGraph_done_Results(msg *capnp.Message) (Graph_done_Results, error) {
	root, err := msg.Root()
	return Graph_done_Results(root.Struct()), err
}

func (s Graph_done_Results) String() string {
	str, _ := text.Marshal(0xdbe88eba4482deb4, capnp.Struct(s))
	return str
}

func (s Graph_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Graph_done_Results) DecodeFromPtr(p capnp.Ptr) Graph_done_Results {
	return Graph_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Graph_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Graph_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Graph_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Graph_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Graph_done_Results_List is a list of Graph_done_Results.
type Graph_done_Results_List = capnp.StructList[Graph_done_Results]

// NewGraph_done_Results creates a new list of Graph_done_Results.
func NewGraph_done_Results_List(s *capnp.Segment, sz int32) (Graph_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Graph_done_Results](l), err
}

// Graph_done_Results_Future is a wrapper for a Graph_done_Results promised by a client call.
type Graph_done_Results_Future struct{ *capnp.Future }

func (f Graph_done_Results_Future) Struct() (Graph_done_Results, error) {
	p, err := f.Future.Ptr()
	return Graph_done_Results(p.Struct()), err
}

const schema_ad058c9d70413d67 = "x\xda\x94\x92?h\x13a\x18\xc6\xdf\xe7\xfb.^\x0a" +
	"\xd6\xf6\xe3\xd29Uk\xa1\x05mM\\,H\"\xb4" +
	"\x8aE1_\\\x05=\xdb39zI\xce\xbbK\xa3" +
	"\xe0RAp\x10\xc1:Yp\x11\xb4(*\x14\xeb\xa2" +
	"\x8bKqpP\x87\xba\xf8o\x92\xaaC\xc1\xe2\xd2\xc1" +
	"\x9e|Is\xad\x82\xb6N\xf7\xe7{\x9e\x97\xe7{\x7f" +
	"O\xff4\xb2\xda\xde\xd6O1br0\xb6%\\X" +
	"\x1c\x9f\xf8\xa9\xcd\xdd%\xd1\x0d\"M'J\xcf\xb3I" +
	"\x90\x16\xee\xb2\x8doo\xd2\xcb\x0f\x1a'1\xa6\x8e\xe6" +
	"\xd8m\x10\x8cyV#\x84\x13\xc3\xfd\xc7\xa7/\xae<" +
	"\"\xd9\x8d\xa6\xb7\xca\xa7\x94\xe02\xcf\x10\xc2\x97\x87^" +
	"-=\x9bm}M\xa2\x93\x87\x85\x03\x07\xdd[Wc" +
	"\x0f\x89\x90\xbe\xc3S0\x9ep\x9d\xc8\x98\xe1/\x8c\x1e" +
	"e\x0dg?^\x1a|z\xed\xcb\xbbuI\x846\xa5" +
	"\x92\xbc\x7f\xbb\xf3\xde\xf7\xc9\xda\x12\xc9N\xb0\xb5A1" +
	"(\x0d\xb4<\x8c\x0e%7\x84\xb6@\x08o\x1c\x19\xfd" +
	"\xf0c\xf1\xca\xcaj\xee\xba\xe8\xabv_\xc5Z\xd62" +
	"T\x09\xdd\xb1B\x9fS)\xd8\xb1\x91>\xbfz\xc6\x0f" +
	"<3\xb0\xfa\x0a\x9e\xe9\x16\xf7\x8c\x98n\xd9\x1d8\\" +
	"\x7f\x1f\xad\x94\xad\xae\x9c\xe9\x99%\xf8\x9b\xf5\xb8^\xa5" +
	"\xe4\x06\xca\xa5\x9b%_\xc6\xb9F\xa4\x81H\xf4\xa4\x88" +
	"d\x17\x87\xcc1\x08 \xa1\x16&\x8e\xe5\x89\xe4Q\x0e" +
	"y\x9e!\xe9\x9aA\xd1\xc76B\x8e\xa3\xf9h\x0f?" +
	"\xcf/=\xeeH\x9d\xb8NT\xff\x19\x96\xac\xc0\xcc\x99" +
	"A\x91\xb0\xb1v\x93\x99k\x9e\x1d4.\xcaK\xbe\xd4" +
	"\xa2\xc8\xad;\x88d\x9cC&\x18\xf41\xeb\x02Z\x88" +
	"\xa1e\xdd\\\xfe\xb7\xb9\xc9\xfa\xe0\x1c \xb7\xf2\x18Q" +
	"T\x14\x94g\x9e\xd7\xd2S\xa7n\x0a\x99\"&\x86t" +
	" j\x19\x9a\xd8\xc4\xfe\x01bb\xb7\x0e\x16u\x13\xcd" +
	"j\x88\xed\xbd\xc4D\x87\x9e\xacg\xce\"\xd3\xd8w\x16" +
	"m\x0aV\x169\xe0\xbf\xe8\xe6-\xbf\xea\xf0`\x0d\xaf" +
	"\xf6O\xd3\xd0h\x01\x96\xbaV{\xb4$\xb3\x97H\x9e" +
	"\xe4\x90\xc5u\\-\x05\xfb4\x87t\x18\x04c\x090" +
	"\"a\x0f\x13\xc9\"\x87\x0c\x18\xc0\x13\xe0D\xe2\x9c\x12" +
	":\x8d\x02\xb49\xd6\xd9\x00qb\x88\x13\x92\x9e](" +
	"F_\xa1[\xf1\xed\xc0\xae\x94\x89(R\x8c\x9bN\xd5" +
	"\xfa\x83z\xfb\xe6\xa9\xaf65o\xf9mU'\xf8\x8d" +
	"\xfb\xc0*\xf7}\x0c\x19Om(\xd8\xa8j\xbf\x02\x00" +
	"\x00\xff\xff\x08\x178\xa7"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_ad058c9d70413d67,
		Nodes: []uint64{
			0xa6c504fd8176eee7,
			0xacf933d1ea136925,
			0xaefe7ca74f304a81,
			0xd00db4bbf2cf46cb,
			0xdbe88eba4482deb4,
			0xf27792f1a923d6dc,
			0xfe88eef4dd644993,
		},
		Compressed: true,
	})
}
