//go:build ignore
// +build ignore

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/viper"
)

func main() {
	viper.SetConfigFile("../../cmd/cfg/config.yml")
	if err := viper.ReadInConfig(); err != nil {
		fmt.Printf("Error reading config: %v\n", err)
		os.Exit(1)
	}

	requiredKeys := []string{
		"value.words",
		"value.region.registers.pc",
		"value.region.program.start",
		"value.region.program.bits",
	}
	for _, k := range requiredKeys {
		if !viper.IsSet(k) {
			fmt.Printf("gen primitives: required config key missing: %q\n", k)
			os.Exit(1)
		}
	}

	words := viper.GetInt("value.words")
	regPC := viper.GetInt("value.region.registers.pc")
	progStart := viper.GetInt("value.region.program.start")
	progBits := viper.GetUint64("value.region.program.bits")
	if words == 0 || regPC == 0 || progStart == 0 || progBits == 0 {
		fmt.Printf("gen primitives: value.words, registers.pc, program.start, and program.bits must be non-zero (got words=%d regPC=%d progStart=%d progBits=%d)\n",
			words, regPC, progStart, progBits)
		os.Exit(1)
	}
	if progBits%32 != 0 {
		fmt.Printf("gen primitives: value.region.program.bits (%d) must be divisible by 32\n", progBits)
		os.Exit(1)
	}
	maxPC := int(progBits / 32)

	var content strings.Builder
	content.WriteString("// THIS FILE IS AUTOMATICALLY GENERATED BY go generate.\n")
	content.WriteString("// DO NOT EDIT. Source of truth: cmd/cfg/config.yml\n\n")
	content.WriteString("#ifndef SUBSTRATE_PRIMITIVES_H\n")
	content.WriteString("#define SUBSTRATE_PRIMITIVES_H\n\n")

	writeMacro(&content, "WORDS", words)
	writeMacro(&content, "REG_PC", regPC)
	writeMacro(&content, "PROGRAM_INDEX_WORD", progStart)
	writeMacro(&content, "MAX_PC", maxPC)

	content.WriteString("\n#endif // SUBSTRATE_PRIMITIVES_H\n")

	targetDir := "../../pkg/compute/kernel/shared"
	if err := os.MkdirAll(targetDir, 0755); err != nil {
		fmt.Printf("Error creating directory: %v\n", err)
		os.Exit(1)
	}

	targetPath := filepath.Join(targetDir, "primitives.h")
	if err := os.WriteFile(targetPath, []byte(content.String()), 0644); err != nil {
		fmt.Printf("Error creating header: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s\n", targetPath)
}

func writeMacro(b *strings.Builder, name string, val int) {
	fmt.Fprintf(b, "#define %-40s %d\n", name, val)
}
