//go:build ignore
// +build ignore

package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/spf13/viper"
)

func resolveConfigPath(configFlag string) string {
	if strings.TrimSpace(configFlag) != "" {
		return filepath.Clean(configFlag)
	}
	if env := strings.TrimSpace(os.Getenv("CONFIG_PATH")); env != "" {
		return filepath.Clean(env)
	}
	_, file, _, ok := runtime.Caller(0)
	if ok {
		return filepath.Clean(filepath.Join(filepath.Dir(file), "..", "..", "cmd", "cfg", "config.yml"))
	}
	return filepath.Clean(filepath.Join("..", "..", "cmd", "cfg", "config.yml"))
}

func main() {
	configPath := flag.String("config", "", "path to config.yml")
	flag.Parse()

	cfgFile := resolveConfigPath(*configPath)
	viper.SetConfigFile(cfgFile)
	if err := viper.ReadInConfig(); err != nil {
		fmt.Printf("Error reading config %q: %v\n", cfgFile, err)
		os.Exit(1)
	}

	requiredKeys := []string{
		"value.words",
		"value.region.tokens.start",
		"value.region.tokens.bits",
		"value.region.program.start",
		"value.region.program.bits",
		"value.region.signals.start",
		"value.region.signals.bits",
	}
	for _, k := range requiredKeys {
		if !viper.IsSet(k) {
			fmt.Printf("gen primitives: required config key missing: %q\n", k)
			os.Exit(1)
		}
	}

	words := viper.GetInt("value.words")
	tokensStart := viper.GetInt("value.region.tokens.start")
	tokenBits := viper.GetInt("value.region.tokens.bits")
	tokenWords := (tokenBits + 63) / 64
	aWords := tokenWords / 2
	bWords := tokenWords - aWords
	progStart := viper.GetInt("value.region.program.start")
	progBits := viper.GetInt("value.region.program.bits")
	progWords := (progBits + 63) / 64
	sigStart := viper.GetInt("value.region.signals.start")
	sigBits := viper.GetInt("value.region.signals.bits")
	sigWords := (sigBits + 63) / 64

	numRotations := 16
	if viper.IsSet("value.num_rotations") {
		numRotations = viper.GetInt("value.num_rotations")
		if numRotations <= 0 {
			fmt.Printf("gen primitives: value.num_rotations must be positive, got %d\n", numRotations)
			os.Exit(1)
		}
	}

	// Surface width: one result lane per rotation × each A word (B rotates in lockstep per word).
	surfaceElements := numRotations * aWords

	var content strings.Builder
	content.WriteString("// THIS FILE IS AUTOMATICALLY GENERATED BY go generate.\n")
	content.WriteString("// DO NOT EDIT. Source of truth: cmd/cfg/config.yml\n\n")
	content.WriteString("#ifndef SUBSTRATE_PRIMITIVES_H\n")
	content.WriteString("#define SUBSTRATE_PRIMITIVES_H\n\n")

	writeMacro(&content, "WORDS", words)
	writeMacro(&content, "TOKENS_START_WORD", tokensStart)
	writeMacro(&content, "TOKEN_WORDS", tokenWords)
	writeMacro(&content, "A_WORDS", aWords)
	writeMacro(&content, "B_WORDS", bWords)
	writeMacro(&content, "PROGRAM_START_WORD", progStart)
	writeMacro(&content, "PROGRAM_WORDS", progWords)
	writeMacro(&content, "SIGNALS_START_WORD", sigStart)
	writeMacro(&content, "SIGNALS_WORDS", sigWords)
	writeMacro(&content, "NUM_ROTATIONS", numRotations)
	writeMacro(&content, "SURFACE_ELEMENTS", surfaceElements)

	if viper.IsSet("value.region.affinity.start") {
		affStart := viper.GetInt("value.region.affinity.start")
		affBits := viper.GetInt("value.region.affinity.bits")
		affWords := (affBits + 63) / 64

		writeMacro(&content, "AFFINITY_START_WORD", affStart)
		writeMacro(&content, "AFFINITY_WORDS", affWords)
		writeMacro(&content, "AFFINITY_BITS", affBits)

		lastWordMask := 1
		remainder := affBits % 64
		if remainder > 0 {
			lastWordMask = (1 << remainder) - 1
		}
		writeMacro(&content, "AFFINITY_LAST_WORD_MASK", lastWordMask)
	}

	if viper.IsSet("value.region.meta.start") {
		metaStart := viper.GetInt("value.region.meta.start")
		metaBits := viper.GetInt("value.region.meta.bits")
		metaWords := (metaBits + 63) / 64

		writeMacro(&content, "META_START_WORD", metaStart)
		writeMacro(&content, "META_WORDS", metaWords)
	}

	content.WriteString("\n#endif // SUBSTRATE_PRIMITIVES_H\n")

	_, genFile, _, ok := runtime.Caller(0)
	if !ok {
		genFile = "."
	}
	targetDir := filepath.Join(filepath.Dir(genFile), "..", "compute", "kernel", "shared")
	if err := os.MkdirAll(targetDir, 0755); err != nil {
		fmt.Printf("Error creating directory: %v\n", err)
		os.Exit(1)
	}

	targetPath := filepath.Join(targetDir, "primitives.h")
	if err := os.WriteFile(targetPath, []byte(content.String()), 0644); err != nil {
		fmt.Printf("Error creating header: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s\n", targetPath)
}

func writeMacro(b *strings.Builder, name string, val int) {
	fmt.Fprintf(b, "#define %-40s %d\n", name, val)
}
