//go:build ignore
// +build ignore

package main

import (
	"flag"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/spf13/viper"
)

// resolveConfigPath picks the config file path: --config flag, then
// CONFIG_PATH env, then ../../cmd/cfg/config.yml relative to this source file
// (via runtime.Caller), so the generator works from any working directory.
func resolveConfigPath(configFlag string) string {
	if strings.TrimSpace(configFlag) != "" {
		return filepath.Clean(configFlag)
	}
	if env := strings.TrimSpace(os.Getenv("CONFIG_PATH")); env != "" {
		return filepath.Clean(env)
	}
	_, file, _, ok := runtime.Caller(0)
	if ok {
		return filepath.Clean(filepath.Join(filepath.Dir(file), "..", "..", "cmd", "cfg", "config.yml"))
	}
	return filepath.Clean(filepath.Join("..", "..", "cmd", "cfg", "config.yml"))
}

func main() {
	configPath := flag.String("config", "", "path to config.yml (overrides CONFIG_PATH and default)")
	flag.Parse()

	cfgFile := resolveConfigPath(*configPath)
	viper.SetConfigFile(cfgFile)
	if err := viper.ReadInConfig(); err != nil {
		fmt.Printf("Error reading config %q: %v\n", cfgFile, err)
		os.Exit(1)
	}

	requiredKeys := []string{
		"value.words",
		"value.region.registers.pc",
		"value.region.registers.fw",
		"value.region.program.start",
		"value.region.program.bits",
		"value.region.state.accumulator",
	}
	for _, k := range requiredKeys {
		if !viper.IsSet(k) {
			fmt.Printf("gen primitives: required config key missing: %q\n", k)
			os.Exit(1)
		}
	}

	words := viper.GetInt("value.words")
	regPC := viper.GetInt("value.region.registers.pc")
	fwWord := viper.GetInt("value.region.registers.fw")
	progStart := viper.GetInt("value.region.program.start")
	progBits := viper.GetUint64("value.region.program.bits")
	if words == 0 || regPC == 0 || fwWord == 0 || progStart == 0 || progBits == 0 {
		fmt.Printf("gen primitives: value.words, registers.pc, registers.fw, program.start, and program.bits must be non-zero (got words=%d regPC=%d fwWord=%d progStart=%d progBits=%d)\n",
			words, regPC, fwWord, progStart, progBits)
		os.Exit(1)
	}
	if progBits%32 != 0 {
		fmt.Printf("gen primitives: value.region.program.bits (%d) must be divisible by 32\n", progBits)
		os.Exit(1)
	}
	q := progBits / 32
	if q > uint64(math.MaxInt) {
		fmt.Printf("gen primitives: program bits imply maxPC=%d which overflows int\n", q)
		os.Exit(1)
	}
	maxPC := int(q)
	stateAccum := viper.GetInt("value.region.state.accumulator")
	execStatusWord := stateAccum + 1

	var content strings.Builder
	content.WriteString("// THIS FILE IS AUTOMATICALLY GENERATED BY go generate.\n")
	content.WriteString("// DO NOT EDIT. Source of truth: cmd/cfg/config.yml\n\n")
	content.WriteString("#ifndef SUBSTRATE_PRIMITIVES_H\n")
	content.WriteString("#define SUBSTRATE_PRIMITIVES_H\n\n")

	writeMacro(&content, "WORDS", words)
	writeMacro(&content, "REG_PC", regPC)
	writeMacro(&content, "FW_WORD", fwWord)
	writeMacro(&content, "PROGRAM_INDEX_WORD", progStart)
	writeMacro(&content, "USER_PROGRAM_PC_START", 4)
	writeMacro(&content, "MAX_PC", maxPC)
	writeMacro(&content, "EXEC_STATUS_WORD", execStatusWord)
	writeMacro(&content, "EXEC_STATUS_SHIFT", 48)
	writeMacro(&content, "EXEC_EXIT_EXHAUSTED", 1)
	writeMacro(&content, "EXEC_EXIT_HALT", 2)
	writeMacro(&content, "EXEC_EXIT_BAD_WORD", 3)

	content.WriteString("\n#endif // SUBSTRATE_PRIMITIVES_H\n")

	_, genFile, _, ok := runtime.Caller(0)
	if !ok {
		genFile = "."
	}
	targetDir := filepath.Join(filepath.Dir(genFile), "..", "compute", "kernel", "shared")
	if err := os.MkdirAll(targetDir, 0755); err != nil {
		fmt.Printf("Error creating directory: %v\n", err)
		os.Exit(1)
	}

	targetPath := filepath.Join(targetDir, "primitives.h")
	if err := os.WriteFile(targetPath, []byte(content.String()), 0644); err != nil {
		fmt.Printf("Error creating header: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s\n", targetPath)
}

func writeMacro(b *strings.Builder, name string, val int) {
	fmt.Fprintf(b, "#define %-40s %d\n", name, val)
}
