// Code generated by go generate; DO NOT EDIT.
// Source of truth: cmd/cfg/config.yml

package primitive

type StatusType uint64

const (
	PENDING StatusType = iota
	READY
	BUSY
	WAITING
	DONE
	RESOLVED
	ERROR
)

type PropertyType int

/*
PropertyType indexes words inside the properties region.
*/
const (
	LABELS PropertyType = iota
	CONFIDENCE
	EPOCH
	TTL
	TEMPERATURE
	STATUS
	NOISE
	PROGRAM_ID
	COMMUNITY
	TARGET
	ROLE
	REFERENCE
	SURPRISAL
	PREV_SURPRISAL
	DELTA_SURPRISAL
	STUCK_COUNT
	FALSIFIED
	STUCK
	CONTINUATION
)

/*
ValueRole is the in-band role carried in the Role property word.
*/
type ValueRole uint64

const (
	ValueRoleNone ValueRole = iota
	ValueRoleProgrammer
	ValueRoleLearner
	ValueRoleReadout
	ValueRoleAssociation
	ValueRolePrompt
)
