package data

import (
	capnp "capnproto.org/go/capnp/v3"
	"github.com/theapemachine/six/pkg/errnie"
	"github.com/theapemachine/six/pkg/numeric"
	"github.com/theapemachine/six/pkg/system/console"
)

var (
	/*
		canonicalValueBasis is a 5-mark Golomb ruler projected into GF(257).
		The pairwise deltas are unique, giving each lexical value a sparse
		resonant fingerprint rather than a handful of arbitrary coprime hits.
	*/
	canonicalValueBasis = [5]int{0, 1, 4, 9, 11}

	byteValueMultipliers = initByteValueMultipliers()

	bytePhaseScales = initBytePhaseScales()
	byteRouteHints  = initByteRouteHints()
)

func initBytePhaseScales() [256]numeric.Phase {
	var scales [256]numeric.Phase

	for b := 0; b < len(scales); b++ {
		scales[b] = numeric.Phase(modPow257(int(numeric.FermatPrimitive), b))

		if scales[b] == 0 {
			scales[b] = 1
		}
	}

	return scales
}

func initByteRouteHints() [256]uint8 {
	var hints [256]uint8

	for b := 0; b < len(hints); b++ {
		base := BaseValue(byte(b))
		hints[b] = uint8(base.Bin())
	}

	return hints
}

/*
PhaseScaleForByte returns the multiplicative GF(257) transition induced by a
byte. It is the native phase operator behind the old lexical update rule
state' = state * 3^byte (mod 257), but factored out so stored values can carry
that operator directly without redundantly storing the byte seed.
*/
func PhaseScaleForByte(symbol byte) numeric.Phase {
	return bytePhaseScales[int(symbol)]
}

/*
RouteHintForSymbol returns a compact routing class for a byte without storing
the byte itself in the persistent value. It is derived from the byte's sparse
lexical seed and only used as an execution hint inside the shell.
*/
func RouteHintForSymbol(symbol byte) uint8 {
	return byteRouteHints[int(symbol)]
}

/*
initByteValueMultipliers builds a 256-entry multiplier table using
modPow257(3, b+1) and returns [256]int.
*/
func initByteValueMultipliers() [256]int {
	var multipliers [256]int

	for b := range len(multipliers) {
		multipliers[b] = modPow257(3, b+1)
	}

	return multipliers
}

/*
modPow257 computes modular exponentiation modulo 257 using exponentiation
by squaring and returns int. Parameters are base and exp.
*/
func modPow257(base, exp int) int {
	result := 1
	base %= 257

	for exp > 0 {
		if exp&1 == 1 {
			result = (result * base) % 257
		}
		base = (base * base) % 257
		exp >>= 1
	}

	return result
}

/*
baseValueOffsets computes five offsets using byteValueMultipliers[int(b)],
the additive (int(b)*17+1)%257, and canonicalValueBasis, and returns [5]int.
*/
func baseValueOffsets(b byte) [5]int {
	mul := byteValueMultipliers[int(b)]
	add := (int(b)*17 + 1) % 257

	var offsets [5]int

	for i, base := range canonicalValueBasis {
		offsets[i] = (base*mul + add) % 257
	}

	return offsets
}

/*
BaseValue returns a deterministic 5-bit value for a byte value.
The value is generated by an affine transform of a sparse 5-mark basis
inside GF(257), so collisions remain structured and rotation-friendly
instead of behaving like arbitrary coprime scatter.
*/
func BaseValue(b byte) Value {
	value := MustNewValue()

	for _, off := range baseValueOffsets(b) {
		value.Set(off)
	}

	return value
}

/*
HasLexicalSeed reports whether the value visibly contains the five-bit
lexical seed for the supplied byte. Query observables should usually return
true; canonical stored values should usually return false.
*/
func HasLexicalSeed(value Value, b byte) bool {
	base := BaseValue(b)
	return value.Similarity(base) == base.ActiveCount()
}

/*
InferLexicalSeed returns the unique lexical seed projected onto an observable
value. Native lexical-free values return ok=false.
*/
func InferLexicalSeed(value Value) (byte, bool) {
	var symbol byte
	matches := 0

	for candidate := 0; candidate < 256; candidate++ {
		if !HasLexicalSeed(value, byte(candidate)) {
			continue
		}

		symbol = byte(candidate)
		matches++

		if matches > 1 {
			return 0, false
		}
	}

	return symbol, matches == 1
}

/*
SeedObservable projects a lexical seed onto an otherwise native value so
prompts and human-facing outputs remain decodable without forcing storage to
carry the byte twice.
*/
func SeedObservable(symbol byte, value Value) Value {
	return ObservableValue(symbol, value)
}

/*
ObservableValue projects a stored native value back into the lexical plane for
measurement and human-facing decode. The key already names the byte; this helper
simply re-injects the byte's transient five-bit seed without disturbing the
stored phase or control shell.
*/
func ObservableValue(symbol byte, value Value) Value {
	out := MustNewValue()
	out.CopyFrom(value)

	for _, off := range baseValueOffsets(symbol) {
		out.Set(off)
	}

	return out
}

/*
StorageValue removes the transient lexical seed from an observable value so the
persistent LSM value can stay native. Byte identity lives in the Morton key;
the stored value keeps phase, control metadata, and any higher-dimensional shell.
*/
func StorageValue(symbol byte, observable Value) Value {
	out := MustNewValue()
	out.CopyFrom(observable)

	if HasLexicalSeed(observable, symbol) {
		for _, off := range baseValueOffsets(symbol) {
			out.Clear(off)
		}
	}

	if carry := observable.ResidualCarry(); carry > 0 {
		phase := numeric.Phase(carry % uint64(numeric.FermatPrime))
		if phase > 0 {
			out.Set(int(phase))
		}
	}

	return out
}

/*
BuildValue is a projection-plane helper that builds an observable lexical value
from raw bytes. It deliberately preserves byte shadowing for tests, decode
paths, and human-facing evaluation.

Do not use BuildValue for persistent storage. Production ingest should tokenize
into radix keys and then compile native operator cells via CompileSequenceCells,
letting the key carry lexical identity and the Value carry only local program
state.
*/
func BuildValue(payload []byte) (Value, error) {
	console.Trace("Building value", "payload", string(payload))

	_, seg, err := capnp.NewMessage(capnp.SingleSegment(nil))
	if err != nil {
		return Value{}, err
	}

	state := errnie.NewState("data/buildValue")

	value := errnie.Guard(state, func() (Value, error) {
		return NewRootValue(seg)
	})

	if state.Failed() {
		return Value{}, state.Err()
	}

	for pos, b := range payload {
		positioned := BaseValue(b)
		positioned = positioned.RollLeft(pos)
		value = value.OR(positioned)
	}

	return value, nil
}
