// Code generated by capnpc-go. DO NOT EDIT.

package data

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
)

type Value capnp.Struct

// Value_TypeID is the unique identifier for the type Value.
const Value_TypeID = 0x91533215b3f2d5e5

func NewValue(s *capnp.Segment) (Value, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 64, PointerCount: 0})
	return Value(st), err
}

func NewRootValue(s *capnp.Segment) (Value, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 64, PointerCount: 0})
	return Value(st), err
}

func ReadRootValue(msg *capnp.Message) (Value, error) {
	root, err := msg.Root()
	return Value(root.Struct()), err
}

func (s Value) String() string {
	str, _ := text.Marshal(0x91533215b3f2d5e5, capnp.Struct(s))
	return str
}

func (s Value) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Value) DecodeFromPtr(p capnp.Ptr) Value {
	return Value(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Value) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Value) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Value) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Value) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Value) C0() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s Value) SetC0(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s Value) C1() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s Value) SetC1(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s Value) C2() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s Value) SetC2(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

func (s Value) C3() uint64 {
	return capnp.Struct(s).Uint64(24)
}

func (s Value) SetC3(v uint64) {
	capnp.Struct(s).SetUint64(24, v)
}

func (s Value) C4() uint64 {
	return capnp.Struct(s).Uint64(32)
}

func (s Value) SetC4(v uint64) {
	capnp.Struct(s).SetUint64(32, v)
}

func (s Value) C5() uint64 {
	return capnp.Struct(s).Uint64(40)
}

func (s Value) SetC5(v uint64) {
	capnp.Struct(s).SetUint64(40, v)
}

func (s Value) C6() uint64 {
	return capnp.Struct(s).Uint64(48)
}

func (s Value) SetC6(v uint64) {
	capnp.Struct(s).SetUint64(48, v)
}

func (s Value) C7() uint64 {
	return capnp.Struct(s).Uint64(56)
}

func (s Value) SetC7(v uint64) {
	capnp.Struct(s).SetUint64(56, v)
}

// Value_List is a list of Value.
type Value_List = capnp.StructList[Value]

// NewValue creates a new list of Value.
func NewValue_List(s *capnp.Segment, sz int32) (Value_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 64, PointerCount: 0}, sz)
	return capnp.StructList[Value](l), err
}

// Value_Future is a wrapper for a Value promised by a client call.
type Value_Future struct{ *capnp.Future }

func (f Value_Future) Struct() (Value, error) {
	p, err := f.Future.Ptr()
	return Value(p.Struct()), err
}

const schema_ad058c9d70413d68 = "x\xdaD\xc8=J3Q\x14\x06\xe0\xf7=\xe7\xce\xcc" +
	"\x97\x0f\x04\x0f\\\x1bm\xdc\x80\xc6\xc4?\x10\x04\xdd\x81" +
	"\x17\xc1~\x88AA\xd1A\xa3\xab\xb0q\x01.\xc1\xca" +
	"V\xb0\x12\x1b\x0b\x03\x06\"D\x88\x90@\x04\x05\x11\xfb" +
	"\xc8-d\xba\x87g\xf2v\xc3\xd5&\xee\x08\x09>I" +
	"\xc7\xc3\xce\xf7\xcdT}\xfb\x12a\x86\xff\xc6\xfb\xeb\x9b" +
	"\xc5\xd5Er\x0d\x97\x01\xb5\xfb\xff\xb4ND\xfb\x81\x98" +
	"\x1b\x17\x07{\xd5\xd3\xd6\xf1\x896\xab\xbby+\xaf\x9e" +
	"\xe7\x87g\xcd\xf9F^\x1c\x15k;\xd1\xc0\x16\x19f" +
	"\xd5\x01\x8e\x80\xb5\xa7\x81\xf0\xa8\x0c]\xa1\x91\x9e1;" +
	"1\x9f\x94\xa1'4\x11O\x01\xec%\xe6\xb32\xf4\x85" +
	"\xa6\xea\xa9\x80\xbd\xc6\xec*\xc3@h\xcey:\xc0\xde" +
	"b\xf6\x94a$\xb4$\xf1L\x00\x1b\xc6\xec+\xc3\x87" +
	"\xd0\xd2\xd43\x05\xec=\xe6@\x19\xbe\x84\x96e\x9e\x19" +
	"`\x9f1G\xca\xf0#\xd4\xc6\x02+\x10V@m\xd4" +
	"J\xd6K.\x96\\*\xb9\\r\xa5\xe4\xea\x1f\x7f\x03" +
	"\x00\x00\xff\xff{;A\x14"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_ad058c9d70413d68,
		Nodes: []uint64{
			0x91533215b3f2d5e5,
		},
		Compressed: true,
	})
}
