// THIS FILE IS AUTOMATICALLY GENERATED BY go generate.
// DO NOT EDIT DIRECTLY. UPDATE pkg/primitive/value.go INSTEAD.

#ifndef SUBSTRATE_PRIMITIVES_H
#define SUBSTRATE_PRIMITIVES_H

#define WORDS                          128
#define BYTE_SIZE                      1024
#define CORE_BITS                      8191
#define REGION0_TOKEN_COUNT            57
#define REGION0_VALUE_ID_INDEX         57
#define REGION0_PREV_VALUE_ID_INDEX    58
#define REGION0_NEXT_VALUE_ID_INDEX    59
#define DATA_WORDS                     60
#define DATA_BITS                      3840
#define STATE_SLOT_INDEX               61
#define STATE_SEQ_INDEX                62
#define STATE_ACCUMULATOR              63
#define REGION_AFFINITY_START_BIT      4096
#define REGION_AFFINITY_BITS           256
#define REGION_PROGRAM_START_BIT       4352
#define REGION_PROGRAM_BITS            256
#define REGION_LINK_START_BIT          4608
#define REGION_LINK_BITS               256
#define REGION_GOSSIP_START_BIT        4864
#define REGION_GOSSIP_BITS             256
#define REGION_TTL_START_BIT           5120
#define REGION_TTL_BITS                8
#define SIGNAL_MASK                    15
#define REG0                           81
#define REG1                           82
#define REG2                           83
#define REG3                           84
#define REG4                           85
#define REG5                           86
#define REG6                           87
#define OP_HALT                        0
#define OP_AND                         8
#define OP_OR                          14
#define OP_XOR                         6
#define OP_MATCH_ZERO                  6
#define OP_MOVE_SRC1                   10
#define OP_MOVE_SRC2                   12

#endif // SUBSTRATE_PRIMITIVES_H
