// Code generated by capnpc-go. DO NOT EDIT.

package primitive

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
)

type Value capnp.Struct

// Value_TypeID is the unique identifier for the type Value.
const Value_TypeID = 0xc37afa4e1a4a0466

func NewValue(s *capnp.Segment) (Value, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 64, PointerCount: 0})
	return Value(st), err
}

func NewRootValue(s *capnp.Segment) (Value, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 64, PointerCount: 0})
	return Value(st), err
}

func ReadRootValue(msg *capnp.Message) (Value, error) {
	root, err := msg.Root()
	return Value(root.Struct()), err
}

func (s Value) String() string {
	str, _ := text.Marshal(0xc37afa4e1a4a0466, capnp.Struct(s))
	return str
}

func (s Value) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Value) DecodeFromPtr(p capnp.Ptr) Value {
	return Value(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Value) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Value) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Value) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Value) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Value) C0() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s Value) SetC0(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s Value) C1() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s Value) SetC1(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s Value) C2() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s Value) SetC2(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

func (s Value) C3() uint64 {
	return capnp.Struct(s).Uint64(24)
}

func (s Value) SetC3(v uint64) {
	capnp.Struct(s).SetUint64(24, v)
}

func (s Value) C4() uint64 {
	return capnp.Struct(s).Uint64(32)
}

func (s Value) SetC4(v uint64) {
	capnp.Struct(s).SetUint64(32, v)
}

func (s Value) C5() uint64 {
	return capnp.Struct(s).Uint64(40)
}

func (s Value) SetC5(v uint64) {
	capnp.Struct(s).SetUint64(40, v)
}

func (s Value) C6() uint64 {
	return capnp.Struct(s).Uint64(48)
}

func (s Value) SetC6(v uint64) {
	capnp.Struct(s).SetUint64(48, v)
}

func (s Value) C7() uint64 {
	return capnp.Struct(s).Uint64(56)
}

func (s Value) SetC7(v uint64) {
	capnp.Struct(s).SetUint64(56, v)
}

// Value_List is a list of Value.
type Value_List = capnp.StructList[Value]

// NewValue creates a new list of Value.
func NewValue_List(s *capnp.Segment, sz int32) (Value_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 64, PointerCount: 0}, sz)
	return capnp.StructList[Value](l), err
}

// Value_Future is a wrapper for a Value promised by a client call.
type Value_Future struct{ *capnp.Future }

func (f Value_Future) Struct() (Value, error) {
	p, err := f.Future.Ptr()
	return Value(p.Struct()), err
}

type Service capnp.Client

// Service_TypeID is the unique identifier for the type Service.
const Service_TypeID = 0xf962138c05061549

func (c Service) Read(ctx context.Context, params func(Service_read_Params) error) (Service_read_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xf962138c05061549,
			MethodID:      0,
			InterfaceName: "pkg/logic/lang/primitive/value.capnp:Service",
			MethodName:    "read",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Service_read_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Service_read_Results_Future{Future: ans.Future()}, release

}

func (c Service) Write(ctx context.Context, params func(Service_write_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xf962138c05061549,
			MethodID:      1,
			InterfaceName: "pkg/logic/lang/primitive/value.capnp:Service",
			MethodName:    "write",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Service_write_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c Service) Close(ctx context.Context, params func(Service_close_Params) error) (Service_close_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xf962138c05061549,
			MethodID:      2,
			InterfaceName: "pkg/logic/lang/primitive/value.capnp:Service",
			MethodName:    "close",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Service_close_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Service_close_Results_Future{Future: ans.Future()}, release

}

func (c Service) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Service) String() string {
	return "Service(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Service) AddRef() Service {
	return Service(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Service) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Service) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Service) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Service) DecodeFromPtr(p capnp.Ptr) Service {
	return Service(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Service) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Service) IsSame(other Service) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Service) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Service) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Service_Server is a Service with a local implementation.
type Service_Server interface {
	Read(context.Context, Service_read) error

	Write(context.Context, Service_write) error

	Close(context.Context, Service_close) error
}

// Service_NewServer creates a new Server from an implementation of Service_Server.
func Service_NewServer(s Service_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Service_Methods(nil, s), s, c)
}

// Service_ServerToClient creates a new Client from an implementation of Service_Server.
// The caller is responsible for calling Release on the returned Client.
func Service_ServerToClient(s Service_Server) Service {
	return Service(capnp.NewClient(Service_NewServer(s)))
}

// Service_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Service_Methods(methods []server.Method, s Service_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 3)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xf962138c05061549,
			MethodID:      0,
			InterfaceName: "pkg/logic/lang/primitive/value.capnp:Service",
			MethodName:    "read",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Read(ctx, Service_read{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xf962138c05061549,
			MethodID:      1,
			InterfaceName: "pkg/logic/lang/primitive/value.capnp:Service",
			MethodName:    "write",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Write(ctx, Service_write{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xf962138c05061549,
			MethodID:      2,
			InterfaceName: "pkg/logic/lang/primitive/value.capnp:Service",
			MethodName:    "close",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Close(ctx, Service_close{call})
		},
	})

	return methods
}

// Service_read holds the state for a server call to Service.read.
// See server.Call for documentation.
type Service_read struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Service_read) Args() Service_read_Params {
	return Service_read_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Service_read) AllocResults() (Service_read_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_read_Results(r), err
}

// Service_write holds the state for a server call to Service.write.
// See server.Call for documentation.
type Service_write struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Service_write) Args() Service_write_Params {
	return Service_write_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Service_write) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// Service_close holds the state for a server call to Service.close.
// See server.Call for documentation.
type Service_close struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Service_close) Args() Service_close_Params {
	return Service_close_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Service_close) AllocResults() (Service_close_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_close_Results(r), err
}

// Service_List is a list of Service.
type Service_List = capnp.CapList[Service]

// NewService_List creates a new list of Service.
func NewService_List(s *capnp.Segment, sz int32) (Service_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Service](l), err
}

type Service_Callback capnp.Client

// Service_Callback_TypeID is the unique identifier for the type Service_Callback.
const Service_Callback_TypeID = 0xa74efdf40dae8bb7

func (c Service_Callback) Send(ctx context.Context, params func(Service_Callback_send_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xa74efdf40dae8bb7,
			MethodID:      0,
			InterfaceName: "pkg/logic/lang/primitive/value.capnp:Service.Callback",
			MethodName:    "send",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Service_Callback_send_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c Service_Callback) Done(ctx context.Context, params func(Service_Callback_done_Params) error) (Service_Callback_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xa74efdf40dae8bb7,
			MethodID:      1,
			InterfaceName: "pkg/logic/lang/primitive/value.capnp:Service.Callback",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Service_Callback_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Service_Callback_done_Results_Future{Future: ans.Future()}, release

}

func (c Service_Callback) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Service_Callback) String() string {
	return "Service_Callback(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Service_Callback) AddRef() Service_Callback {
	return Service_Callback(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Service_Callback) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Service_Callback) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Service_Callback) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Service_Callback) DecodeFromPtr(p capnp.Ptr) Service_Callback {
	return Service_Callback(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Service_Callback) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Service_Callback) IsSame(other Service_Callback) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Service_Callback) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Service_Callback) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Service_Callback_Server is a Service_Callback with a local implementation.
type Service_Callback_Server interface {
	Send(context.Context, Service_Callback_send) error

	Done(context.Context, Service_Callback_done) error
}

// Service_Callback_NewServer creates a new Server from an implementation of Service_Callback_Server.
func Service_Callback_NewServer(s Service_Callback_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Service_Callback_Methods(nil, s), s, c)
}

// Service_Callback_ServerToClient creates a new Client from an implementation of Service_Callback_Server.
// The caller is responsible for calling Release on the returned Client.
func Service_Callback_ServerToClient(s Service_Callback_Server) Service_Callback {
	return Service_Callback(capnp.NewClient(Service_Callback_NewServer(s)))
}

// Service_Callback_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Service_Callback_Methods(methods []server.Method, s Service_Callback_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xa74efdf40dae8bb7,
			MethodID:      0,
			InterfaceName: "pkg/logic/lang/primitive/value.capnp:Service.Callback",
			MethodName:    "send",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Send(ctx, Service_Callback_send{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xa74efdf40dae8bb7,
			MethodID:      1,
			InterfaceName: "pkg/logic/lang/primitive/value.capnp:Service.Callback",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, Service_Callback_done{call})
		},
	})

	return methods
}

// Service_Callback_send holds the state for a server call to Service_Callback.send.
// See server.Call for documentation.
type Service_Callback_send struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Service_Callback_send) Args() Service_Callback_send_Params {
	return Service_Callback_send_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Service_Callback_send) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// Service_Callback_done holds the state for a server call to Service_Callback.done.
// See server.Call for documentation.
type Service_Callback_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Service_Callback_done) Args() Service_Callback_done_Params {
	return Service_Callback_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Service_Callback_done) AllocResults() (Service_Callback_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_Callback_done_Results(r), err
}

// Service_Callback_List is a list of Service_Callback.
type Service_Callback_List = capnp.CapList[Service_Callback]

// NewService_Callback_List creates a new list of Service_Callback.
func NewService_Callback_List(s *capnp.Segment, sz int32) (Service_Callback_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Service_Callback](l), err
}

type Service_Callback_send_Params capnp.Struct

// Service_Callback_send_Params_TypeID is the unique identifier for the type Service_Callback_send_Params.
const Service_Callback_send_Params_TypeID = 0x898cc1561bcb3644

func NewService_Callback_send_Params(s *capnp.Segment) (Service_Callback_send_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Service_Callback_send_Params(st), err
}

func NewRootService_Callback_send_Params(s *capnp.Segment) (Service_Callback_send_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Service_Callback_send_Params(st), err
}

func ReadRootService_Callback_send_Params(msg *capnp.Message) (Service_Callback_send_Params, error) {
	root, err := msg.Root()
	return Service_Callback_send_Params(root.Struct()), err
}

func (s Service_Callback_send_Params) String() string {
	str, _ := text.Marshal(0x898cc1561bcb3644, capnp.Struct(s))
	return str
}

func (s Service_Callback_send_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Service_Callback_send_Params) DecodeFromPtr(p capnp.Ptr) Service_Callback_send_Params {
	return Service_Callback_send_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Service_Callback_send_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Service_Callback_send_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Service_Callback_send_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Service_Callback_send_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Service_Callback_send_Params) Value() (Value, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Value(p.Struct()), err
}

func (s Service_Callback_send_Params) HasValue() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Service_Callback_send_Params) SetValue(v Value) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewValue sets the value field to a newly
// allocated Value struct, preferring placement in s's segment.
func (s Service_Callback_send_Params) NewValue() (Value, error) {
	ss, err := NewValue(capnp.Struct(s).Segment())
	if err != nil {
		return Value{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Service_Callback_send_Params_List is a list of Service_Callback_send_Params.
type Service_Callback_send_Params_List = capnp.StructList[Service_Callback_send_Params]

// NewService_Callback_send_Params creates a new list of Service_Callback_send_Params.
func NewService_Callback_send_Params_List(s *capnp.Segment, sz int32) (Service_Callback_send_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Service_Callback_send_Params](l), err
}

// Service_Callback_send_Params_Future is a wrapper for a Service_Callback_send_Params promised by a client call.
type Service_Callback_send_Params_Future struct{ *capnp.Future }

func (f Service_Callback_send_Params_Future) Struct() (Service_Callback_send_Params, error) {
	p, err := f.Future.Ptr()
	return Service_Callback_send_Params(p.Struct()), err
}
func (p Service_Callback_send_Params_Future) Value() Value_Future {
	return Value_Future{Future: p.Future.Field(0, nil)}
}

type Service_Callback_done_Params capnp.Struct

// Service_Callback_done_Params_TypeID is the unique identifier for the type Service_Callback_done_Params.
const Service_Callback_done_Params_TypeID = 0xfb7261b7baa82337

func NewService_Callback_done_Params(s *capnp.Segment) (Service_Callback_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_Callback_done_Params(st), err
}

func NewRootService_Callback_done_Params(s *capnp.Segment) (Service_Callback_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_Callback_done_Params(st), err
}

func ReadRootService_Callback_done_Params(msg *capnp.Message) (Service_Callback_done_Params, error) {
	root, err := msg.Root()
	return Service_Callback_done_Params(root.Struct()), err
}

func (s Service_Callback_done_Params) String() string {
	str, _ := text.Marshal(0xfb7261b7baa82337, capnp.Struct(s))
	return str
}

func (s Service_Callback_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Service_Callback_done_Params) DecodeFromPtr(p capnp.Ptr) Service_Callback_done_Params {
	return Service_Callback_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Service_Callback_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Service_Callback_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Service_Callback_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Service_Callback_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Service_Callback_done_Params_List is a list of Service_Callback_done_Params.
type Service_Callback_done_Params_List = capnp.StructList[Service_Callback_done_Params]

// NewService_Callback_done_Params creates a new list of Service_Callback_done_Params.
func NewService_Callback_done_Params_List(s *capnp.Segment, sz int32) (Service_Callback_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Service_Callback_done_Params](l), err
}

// Service_Callback_done_Params_Future is a wrapper for a Service_Callback_done_Params promised by a client call.
type Service_Callback_done_Params_Future struct{ *capnp.Future }

func (f Service_Callback_done_Params_Future) Struct() (Service_Callback_done_Params, error) {
	p, err := f.Future.Ptr()
	return Service_Callback_done_Params(p.Struct()), err
}

type Service_Callback_done_Results capnp.Struct

// Service_Callback_done_Results_TypeID is the unique identifier for the type Service_Callback_done_Results.
const Service_Callback_done_Results_TypeID = 0xf914a6a0eaa16487

func NewService_Callback_done_Results(s *capnp.Segment) (Service_Callback_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_Callback_done_Results(st), err
}

func NewRootService_Callback_done_Results(s *capnp.Segment) (Service_Callback_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_Callback_done_Results(st), err
}

func ReadRootService_Callback_done_Results(msg *capnp.Message) (Service_Callback_done_Results, error) {
	root, err := msg.Root()
	return Service_Callback_done_Results(root.Struct()), err
}

func (s Service_Callback_done_Results) String() string {
	str, _ := text.Marshal(0xf914a6a0eaa16487, capnp.Struct(s))
	return str
}

func (s Service_Callback_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Service_Callback_done_Results) DecodeFromPtr(p capnp.Ptr) Service_Callback_done_Results {
	return Service_Callback_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Service_Callback_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Service_Callback_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Service_Callback_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Service_Callback_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Service_Callback_done_Results_List is a list of Service_Callback_done_Results.
type Service_Callback_done_Results_List = capnp.StructList[Service_Callback_done_Results]

// NewService_Callback_done_Results creates a new list of Service_Callback_done_Results.
func NewService_Callback_done_Results_List(s *capnp.Segment, sz int32) (Service_Callback_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Service_Callback_done_Results](l), err
}

// Service_Callback_done_Results_Future is a wrapper for a Service_Callback_done_Results promised by a client call.
type Service_Callback_done_Results_Future struct{ *capnp.Future }

func (f Service_Callback_done_Results_Future) Struct() (Service_Callback_done_Results, error) {
	p, err := f.Future.Ptr()
	return Service_Callback_done_Results(p.Struct()), err
}

type Service_read_Params capnp.Struct

// Service_read_Params_TypeID is the unique identifier for the type Service_read_Params.
const Service_read_Params_TypeID = 0xce868630baeecade

func NewService_read_Params(s *capnp.Segment) (Service_read_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Service_read_Params(st), err
}

func NewRootService_read_Params(s *capnp.Segment) (Service_read_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Service_read_Params(st), err
}

func ReadRootService_read_Params(msg *capnp.Message) (Service_read_Params, error) {
	root, err := msg.Root()
	return Service_read_Params(root.Struct()), err
}

func (s Service_read_Params) String() string {
	str, _ := text.Marshal(0xce868630baeecade, capnp.Struct(s))
	return str
}

func (s Service_read_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Service_read_Params) DecodeFromPtr(p capnp.Ptr) Service_read_Params {
	return Service_read_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Service_read_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Service_read_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Service_read_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Service_read_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Service_read_Params) Callback() Service_Callback {
	p, _ := capnp.Struct(s).Ptr(0)
	return Service_Callback(p.Interface().Client())
}

func (s Service_read_Params) HasCallback() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Service_read_Params) SetCallback(v Service_Callback) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().CapTable().Add(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

// Service_read_Params_List is a list of Service_read_Params.
type Service_read_Params_List = capnp.StructList[Service_read_Params]

// NewService_read_Params creates a new list of Service_read_Params.
func NewService_read_Params_List(s *capnp.Segment, sz int32) (Service_read_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Service_read_Params](l), err
}

// Service_read_Params_Future is a wrapper for a Service_read_Params promised by a client call.
type Service_read_Params_Future struct{ *capnp.Future }

func (f Service_read_Params_Future) Struct() (Service_read_Params, error) {
	p, err := f.Future.Ptr()
	return Service_read_Params(p.Struct()), err
}
func (p Service_read_Params_Future) Callback() Service_Callback {
	return Service_Callback(p.Future.Field(0, nil).Client())
}

type Service_read_Results capnp.Struct

// Service_read_Results_TypeID is the unique identifier for the type Service_read_Results.
const Service_read_Results_TypeID = 0xbc7a284636bd54b9

func NewService_read_Results(s *capnp.Segment) (Service_read_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_read_Results(st), err
}

func NewRootService_read_Results(s *capnp.Segment) (Service_read_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_read_Results(st), err
}

func ReadRootService_read_Results(msg *capnp.Message) (Service_read_Results, error) {
	root, err := msg.Root()
	return Service_read_Results(root.Struct()), err
}

func (s Service_read_Results) String() string {
	str, _ := text.Marshal(0xbc7a284636bd54b9, capnp.Struct(s))
	return str
}

func (s Service_read_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Service_read_Results) DecodeFromPtr(p capnp.Ptr) Service_read_Results {
	return Service_read_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Service_read_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Service_read_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Service_read_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Service_read_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Service_read_Results_List is a list of Service_read_Results.
type Service_read_Results_List = capnp.StructList[Service_read_Results]

// NewService_read_Results creates a new list of Service_read_Results.
func NewService_read_Results_List(s *capnp.Segment, sz int32) (Service_read_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Service_read_Results](l), err
}

// Service_read_Results_Future is a wrapper for a Service_read_Results promised by a client call.
type Service_read_Results_Future struct{ *capnp.Future }

func (f Service_read_Results_Future) Struct() (Service_read_Results, error) {
	p, err := f.Future.Ptr()
	return Service_read_Results(p.Struct()), err
}

type Service_write_Params capnp.Struct

// Service_write_Params_TypeID is the unique identifier for the type Service_write_Params.
const Service_write_Params_TypeID = 0x81c2716cd368082a

func NewService_write_Params(s *capnp.Segment) (Service_write_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Service_write_Params(st), err
}

func NewRootService_write_Params(s *capnp.Segment) (Service_write_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Service_write_Params(st), err
}

func ReadRootService_write_Params(msg *capnp.Message) (Service_write_Params, error) {
	root, err := msg.Root()
	return Service_write_Params(root.Struct()), err
}

func (s Service_write_Params) String() string {
	str, _ := text.Marshal(0x81c2716cd368082a, capnp.Struct(s))
	return str
}

func (s Service_write_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Service_write_Params) DecodeFromPtr(p capnp.Ptr) Service_write_Params {
	return Service_write_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Service_write_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Service_write_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Service_write_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Service_write_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Service_write_Params) Value() (Value, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Value(p.Struct()), err
}

func (s Service_write_Params) HasValue() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Service_write_Params) SetValue(v Value) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewValue sets the value field to a newly
// allocated Value struct, preferring placement in s's segment.
func (s Service_write_Params) NewValue() (Value, error) {
	ss, err := NewValue(capnp.Struct(s).Segment())
	if err != nil {
		return Value{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Service_write_Params_List is a list of Service_write_Params.
type Service_write_Params_List = capnp.StructList[Service_write_Params]

// NewService_write_Params creates a new list of Service_write_Params.
func NewService_write_Params_List(s *capnp.Segment, sz int32) (Service_write_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Service_write_Params](l), err
}

// Service_write_Params_Future is a wrapper for a Service_write_Params promised by a client call.
type Service_write_Params_Future struct{ *capnp.Future }

func (f Service_write_Params_Future) Struct() (Service_write_Params, error) {
	p, err := f.Future.Ptr()
	return Service_write_Params(p.Struct()), err
}
func (p Service_write_Params_Future) Value() Value_Future {
	return Value_Future{Future: p.Future.Field(0, nil)}
}

type Service_close_Params capnp.Struct

// Service_close_Params_TypeID is the unique identifier for the type Service_close_Params.
const Service_close_Params_TypeID = 0xed5ca6ff31b34c1f

func NewService_close_Params(s *capnp.Segment) (Service_close_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_close_Params(st), err
}

func NewRootService_close_Params(s *capnp.Segment) (Service_close_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_close_Params(st), err
}

func ReadRootService_close_Params(msg *capnp.Message) (Service_close_Params, error) {
	root, err := msg.Root()
	return Service_close_Params(root.Struct()), err
}

func (s Service_close_Params) String() string {
	str, _ := text.Marshal(0xed5ca6ff31b34c1f, capnp.Struct(s))
	return str
}

func (s Service_close_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Service_close_Params) DecodeFromPtr(p capnp.Ptr) Service_close_Params {
	return Service_close_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Service_close_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Service_close_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Service_close_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Service_close_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Service_close_Params_List is a list of Service_close_Params.
type Service_close_Params_List = capnp.StructList[Service_close_Params]

// NewService_close_Params creates a new list of Service_close_Params.
func NewService_close_Params_List(s *capnp.Segment, sz int32) (Service_close_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Service_close_Params](l), err
}

// Service_close_Params_Future is a wrapper for a Service_close_Params promised by a client call.
type Service_close_Params_Future struct{ *capnp.Future }

func (f Service_close_Params_Future) Struct() (Service_close_Params, error) {
	p, err := f.Future.Ptr()
	return Service_close_Params(p.Struct()), err
}

type Service_close_Results capnp.Struct

// Service_close_Results_TypeID is the unique identifier for the type Service_close_Results.
const Service_close_Results_TypeID = 0x999fdec074c4b82d

func NewService_close_Results(s *capnp.Segment) (Service_close_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_close_Results(st), err
}

func NewRootService_close_Results(s *capnp.Segment) (Service_close_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Service_close_Results(st), err
}

func ReadRootService_close_Results(msg *capnp.Message) (Service_close_Results, error) {
	root, err := msg.Root()
	return Service_close_Results(root.Struct()), err
}

func (s Service_close_Results) String() string {
	str, _ := text.Marshal(0x999fdec074c4b82d, capnp.Struct(s))
	return str
}

func (s Service_close_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Service_close_Results) DecodeFromPtr(p capnp.Ptr) Service_close_Results {
	return Service_close_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Service_close_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Service_close_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Service_close_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Service_close_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Service_close_Results_List is a list of Service_close_Results.
type Service_close_Results_List = capnp.StructList[Service_close_Results]

// NewService_close_Results creates a new list of Service_close_Results.
func NewService_close_Results_List(s *capnp.Segment, sz int32) (Service_close_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Service_close_Results](l), err
}

// Service_close_Results_Future is a wrapper for a Service_close_Results promised by a client call.
type Service_close_Results_Future struct{ *capnp.Future }

func (f Service_close_Results_Future) Struct() (Service_close_Results, error) {
	p, err := f.Future.Ptr()
	return Service_close_Results(p.Struct()), err
}

const schema_ad058c9d70413d98 = "x\xda\xa4T]h#U\x14>\xdf\xbdsg\xb2\xb0" +
	"!{wfQ\xebC\x14\xb7 \x0bi\x9aF\xb3(" +
	"\x88Y\xd6\x15,\xcb\xd2\xab\xb2\x0f\xb2\"\xb3\x93\xb1\xc6" +
	"\x9dMc\x92vq\xdf|i\x11+\xbeZA\xb4\x0f" +
	"V_\x14T\xa4Z\x14\xea\x1f\x85\xfa\x83\xbf\xd0J[" +
	"Zh\xa1\x8a\x15\x85\xbeT\x91\x91;i2\x11Ak" +
	"\xf6\xed\xf0\xdd{\xcf9\xdf\xb9\xdf\xf9\xfa\x1dV4r" +
	"\xc9\xe7Lb\xea\xac0\xc3\x13\x89\xc7\xbe\x0d\x9e\xf8\xe8" +
	")\x92\x19\x10\x09XD\xf9\x0c\xff\x06\x04\xfb\x14\xbf\x9b" +
	"\x10\xdeS\xf8\xec\xc6\xf3\x1fN>M\xb2\xd0\xbe\xe0\xf2" +
	"\xa3\x8c`?\x19]\xc8\xbc\xfbIc~\xed\xa5\xa9f" +
	"\x06C\x9fO\xf1\x1f@F8\xfb\xcc\x1b\xc9\xdd?\xcf" +
	"\xbdJ2\xc3\xc3\xfb\x8e\x99b\xd2\xbe\xb8G\x84\xfc\xb3" +
	"\xfc-\xd8\xafp\x8b\xc8\x9e\xe6\x13\xf6o:\x0a\xdf{" +
	"\xf0\x83\xc2\xbd\xb7^}\xbf#\xcf\xb2n\xc4\x08\x1f5" +
	"\x06{\xce\xfd~\xf5cR\xbdH\x84\xcf\xdfu\xaa\xfa" +
	"\xe2\xa4x\xbdy\xe5\x0b\xfe\x10\xec\x0d\x9d \xbf\xca\x17" +
	"@\x08\xd7\x16\x7f\x99\xeb\x1f\x1f\xff\xb2\x93\xd1\xb4X\xd4" +
	"\x8c\xde\x11\xba\xe1\xf4\xd9\xb7s\xe1\xcc\x85\x9d\xceB\"" +
	"*4Q\x9a\xfe\xe9\xe5\x19g\xaf\xc9\xb5\x99_\xf40" +
	"2\xe2\xeee/\x8f; \xe4?\x15\x8f\xc3^\x16\xd7" +
	"\x11\xd9[b\xc1~\xd8\xd4TN\xde\xf2\xda\xdc\xac[" +
	"\xfb\xa3#\xcf\x19\xf3(\xa3\x0ba\xf5\xd2p6\x18\x19" +
	".\x9b^6p+\xc3\xd9j\xad|\xb9\xdc(\x8f\xf9" +
	"\xd917\x18\xf5\xfb<\xb7Z\xa9\xde\xf9\x80_\x1b+" +
	"{~\xdf\x95Z\xb9\xe1\x1f\x1frk\xeee\xd4\x95\xc1" +
	"\x0d\"\x03D29@\xa4\x12\x1c\xcaaHG\x0fq" +
	"$\x9e\x12\x01G\x08\xedR\xd6\x81J\x9dv\x83\xe0\xa2" +
	"\xeb]\xea\xab\xfb\x95\xd2\xb5\x96<\x18;/\x18\xa9\xfb" +
	"\xc7\xef\xf7\xeb\xa3\x01o\xd4\xdb\x8f\xc5A\xfbMG\x0d" +
	"\x0f\x01*\xc1\x05Q[\xa9\xa8\xbc9\x7f%\xff\xc2#" +
	"S2w\x82\x98\xec\xb5\x80\xf6\x8f\xa0\xf5\xc5\xf2\x06}" +
	"\x96\xb4R\x9ao\x11\xa9\xd2H\xc5/b\x08\xff\x97D" +
	"\xcdwKM\x0e\x0d\xc4\x1c\x8c\x7f}{\xde\x0d\xf8\xa8" +
	"\xaf\x1b\xbf\xa9=\xdf\xaf{\x88\xd4\xe7\x1cj\x89A\x02" +
	"\x0e4\xf8\xbd\x06\xbf\xe2P+\x0c\x921\x07\x8cH." +
	"k\xf0;\x0e\xb5\xce 9w\xc0\x89\xe4\xaa\x06\x978" +
	"\xd4&\x834\x0c\x07\x06\x91\xdc\xd0\xe0\x0a\x87\xdaf\x90" +
	"B8\x10DrK\x83\xeb\x1c\xeag\x06i\x9a\x0eL" +
	"\"\xf9\xa3\x0679\xd4\xaf\x0c\xd2\xb2\x1c\xbd4rG" +
	"\x83\xdb\x1cj\x97\x81{\xfd8D\x0c\x87\x08\xdc\xcb\xc5" +
	"\xe1@\x1c\xe6\xe3\xf0\xb68\xbc=\x0e\x0bqx\xb2\x15" +
	"v3\xedH\x9cu\xa2Nu\x0e\x12\xa9\xc3\x1c\xeaz" +
	"\x86\xd0\xdb\x972\x11A\xc6&D\x80\xecR\xa3\xfb\xeb" +
	"\xd0\xedJim\xfdS\xe7\xc6\x7f%I\xe9,\xca\x00" +
	":\x8c\x14\x83\xe1\xe9\x98\x9e:\x1c\x09\xbf\xe5xhY" +
	"\xa8TZ\xdcg\xb4\xf0[\xfe\x1e/\xc5\x1d\x03\xc4d" +
	"\xc6\x02k\x1b!Z\x16.o\xd6g\xc7\xac\x94\x9es" +
	"\x11\xe9\xc8\x7f\x8aHGS\xf8\xfbvt3\x82\xfd1" +
	"\xfe\x15\x00\x00\xff\xff\xe0\xda\xe5\xc5"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_ad058c9d70413d98,
		Nodes: []uint64{
			0x81c2716cd368082a,
			0x898cc1561bcb3644,
			0x999fdec074c4b82d,
			0xa74efdf40dae8bb7,
			0xbc7a284636bd54b9,
			0xc37afa4e1a4a0466,
			0xce868630baeecade,
			0xed5ca6ff31b34c1f,
			0xf914a6a0eaa16487,
			0xf962138c05061549,
			0xfb7261b7baa82337,
		},
		Compressed: true,
	})
}
