package primitive

import (
	"fmt"

	capnp "capnproto.org/go/capnp/v3"
	"github.com/theapemachine/six/pkg/errnie"
	"github.com/theapemachine/six/pkg/numeric"
	config "github.com/theapemachine/six/pkg/system/core"
)

var (
	/*
		canonicalValueBasis is a 5-mark Golomb ruler projected into GF(257).
		Each set bit in the 257-core is treated as a basis coordinate that maps
		to one prime frequency (index k -> numeric.Primes[k] when projected in
		PhaseDial). The runtime stores only 0/1 occupancy for speed, but the
		algebra stays in prime-factor space: bitwise composition in companion
		operators (`OR`, `AND`, `Hole`) is interpreted as lattice operations over
		that prime basis.

		The basis uses unique pairwise deltas so byte projections remain sparse,
		structured, and rotation-friendly instead of collapsing into dense noise.
	*/
	canonicalValueBasis = [5]int{0, 1, 4, 9, 11}

	byteValueMultipliers = initByteValueMultipliers()

	bytePhaseScales = initBytePhaseScales()
	byteRouteHints  = initByteRouteHints()
)

/*
New allocates one fresh primitive Value in a standalone single-segment
Cap'n Proto message with a pre-sized data blob for all TotalBlocks words.
The returned value has independent storage and can be mutated safely by
callers without aliasing another value's backing segment.
*/
func New() (Value, error) {
	_, seg, err := capnp.NewMessage(capnp.SingleSegment(nil))

	if err != nil {
		return Value{}, errnie.Error(
			NewValueError(ValueErrorTypeAllocationFailed),
		)
	}

	value, err := NewValue(seg)

	if err != nil {
		return Value{}, errnie.Error(
			NewValueError(ValueErrorTypeAllocationFailed),
		)
	}

	if err := value.SetBlocks(make([]byte, config.TotalBlocks*8)); err != nil {
		return Value{}, errnie.Error(
			NewValueError(ValueErrorTypeAllocationFailed),
		)
	}

	return value, nil
}

/*
NeutralValue allocates a lexical-free native value. The value starts with an
identity affine operator so it behaves like a tiny local program even before
any lexical observable is projected onto it.
*/
func NeutralValue() Value {
	value, err := New()

	if err != nil {
		panic("NeutralValue: " + err.Error())
	}

	value.SetAffine(1, 0)

	return value
}

/*
BaseValue returns a deterministic 5-bit value for a byte value.
The value is generated by an affine transform of a sparse 5-mark basis
inside GF(257), so collisions remain structured and rotation-friendly
instead of behaving like arbitrary scatter.

Each selected core offset marks one prime-basis coordinate; downstream
bitwise operators can then treat overlap and cancellation as exact structural
signals over that basis instead of semantic symbols.
*/
func BaseValue(b byte) Value {
	value, err := New()

	if err != nil {
		panic("BaseValue: " + err.Error())
	}

	for _, off := range baseValueOffsets(b) {
		value.Set(off)
	}

	return value
}

/*
BaseValueInto writes the deterministic 5-bit projection for a byte into an
existing destination, avoiding allocation when callers can reuse storage.
*/
func BaseValueInto(b byte, destination *Value) {
	for i := range config.TotalBlocks {
		destination.setBlock(i, 0)
	}

	for _, off := range baseValueOffsets(b) {
		destination.Set(off)
	}
}

/*
BuildValue is a projection-plane helper that builds an observable lexical value
from raw bytes. It deliberately preserves byte shadowing for tests, decode
paths, and human-facing evaluation.

Do not use BuildValue for persistent storage. Production ingest should tokenize
into radix keys and then compile native operator cells via CompileSequenceCells,
letting the key carry lexical identity and the Value carry only local program
state.
*/
func BuildValue(payload []byte) (Value, error) {
	_, seg, err := capnp.NewMessage(capnp.SingleSegment(nil))
	if err != nil {
		return Value{}, err
	}

	value, err := NewRootValue(seg)
	if err != nil {
		return Value{}, err
	}

	if err := value.SetBlocks(make([]byte, config.TotalBlocks*8)); err != nil {
		return Value{}, err
	}

	var base, rolled, merged Value

	base, err = New()
	if err != nil {
		return Value{}, err
	}

	rolled, err = New()
	if err != nil {
		return Value{}, err
	}

	merged, err = New()
	if err != nil {
		return Value{}, err
	}

	for pos, b := range payload {
		BaseValueInto(b, &base)
		base.RollLeftInto(pos, &rolled)

		if err = value.ORInto(rolled, &merged); err != nil {
			return Value{}, err
		}

		value.CopyFrom(merged)
	}

	return value, nil
}

/*
baseValueOffsets computes five offsets using byteValueMultipliers[int(b)],
the additive (int(b)*17+1)%FieldPrime, and canonicalValueBasis. Distributes
values across the 8191-bit core to minimize accidental aliasing.
*/
func baseValueOffsets(b byte) [5]int {
	mul := byteValueMultipliers[int(b)]
	add := (int(b)*17 + 1) % int(numeric.FieldPrime)

	var offsets [5]int

	for i, base := range canonicalValueBasis {
		offsets[i] = (base*mul + add) % int(numeric.FieldPrime)
	}

	return offsets
}

/*
setBlock writes one 64-bit word into the requested block index (0..TotalBlocks-1).
Reads the backing Data slice and writes 8 bytes in little-endian order at the
correct offset. Cap'n Proto Data is a direct reference to segment memory, so
the write takes effect immediately without a second SetBlocks call.
*/
func (value Value) setBlock(i int, v uint64) (Value, error) {
	if i < 0 || i >= config.TotalBlocks {
		return value, NewValueError(ValueErrorTypeInvalidBlockIndex)
	}

	data, err := value.Blocks()

	if err != nil || len(data) < (i+1)*8 {
		return value, NewValueError(ValueErrorTypeInvalidBlockIndex)
	}

	off := i * 8
	data[off] = byte(v)
	data[off+1] = byte(v >> 8)
	data[off+2] = byte(v >> 16)
	data[off+3] = byte(v >> 24)
	data[off+4] = byte(v >> 32)
	data[off+5] = byte(v >> 40)
	data[off+6] = byte(v >> 48)
	data[off+7] = byte(v >> 56)

	return value, nil
}

/*
SetBlock is the exported variant of setBlock for cross-package callers that
need to reconstruct a Value from raw block data (e.g. MacroIndex rebuilding
a Value from an AffineKey).
*/
func (value *Value) SetBlock(i int, v uint64) error {
	_, err := value.setBlock(i, v)
	return err
}

/*
Block returns the raw 64-bit word at block index i. Reads 8 bytes from
the backing Data slice in little-endian order. Indices outside the valid
range return zero with a diagnostic warning.
*/
func (value Value) Block(i int) uint64 {
	if i < 0 || i >= config.TotalBlocks {
		errnie.Warn("block overflow", "index", i, "max", config.TotalBlocks)
		return 0
	}

	data, err := value.Blocks()

	if err != nil || len(data) < (i+1)*8 {
		return 0
	}

	off := i * 8

	return uint64(data[off]) |
		uint64(data[off+1])<<8 |
		uint64(data[off+2])<<16 |
		uint64(data[off+3])<<24 |
		uint64(data[off+4])<<32 |
		uint64(data[off+5])<<40 |
		uint64(data[off+6])<<48 |
		uint64(data[off+7])<<56
}

/*
CopyFrom copies all TotalBlocks words from src into the receiver.
*/
func (value *Value) CopyFrom(src Value) {
	for i := range config.TotalBlocks {
		value.setBlock(i, src.Block(i))
	}
}

/*
InitValueListElementStorage allocates the blocks blob for one Value struct
inside a composite Cap'n Proto Value_List. NewValue_List does not size inline
data, so CopyFrom would otherwise leave high-index words unset.
*/
func InitValueListElementStorage(v Value) error {
	return v.SetBlocks(make([]byte, config.TotalBlocks*8))
}

/*
ValueSliceToList packs a Go slice of Values into a Cap'n Proto Value_List.
*/
func ValueSliceToList(values []Value) (Value_List, error) {
	_, seg, err := capnp.NewMessage(capnp.MultiSegment(nil))
	if err != nil {
		return Value_List{}, err
	}

	state := errnie.NewState("primitive/value/valueSliceToList")

	list := errnie.Guard(state, func() (Value_List, error) {
		return NewValue_List(seg, int32(len(values)))
	})

	if state.Failed() {
		return Value_List{}, state.Err()
	}

	for i, cc := range values {
		dst := list.At(i)

		if err := InitValueListElementStorage(dst); err != nil {
			return Value_List{}, err
		}

		dst.CopyFrom(cc)
	}

	return list, nil
}

/*
ValueListToSlice copies each entry into a freshly allocated Value and returns the slice.
Each value gets its own message to avoid aliasing.
*/
func ValueListToSlice(list Value_List) ([]Value, error) {
	out := make([]Value, list.Len())

	for i := 0; i < list.Len(); i++ {
		src := list.At(i)

		value, err := New()
		if err != nil {
			return nil, err
		}

		value.CopyFrom(src)
		out[i] = value
	}

	return out, nil
}

/*
initByteValueMultipliers builds a 256-entry multiplier table using
modPow(primitiveRoot, b+1, FieldPrime).
*/
func initByteValueMultipliers() [256]int {
	var multipliers [256]int

	for b := range len(multipliers) {
		multipliers[b] = modPowField(int(numeric.FieldPrimitive), b+1)
	}

	return multipliers
}

/*
modPowField computes base^exp mod FieldPrime via binary exponentiation.
*/
func modPowField(base, exp int) int {
	result := 1
	base %= int(numeric.FieldPrime)

	for exp > 0 {
		if exp&1 == 1 {
			result = (result * base) % int(numeric.FieldPrime)
		}

		base = (base * base) % int(numeric.FieldPrime)
		exp >>= 1
	}

	return result
}

/*
initBytePhaseScales precomputes one GF(8191) phase scale per byte using the
field primitive generator. Keeps byte-local phase transforms deterministic
without doing modular exponentiation in hot paths.
*/
func initBytePhaseScales() [256]numeric.Phase {
	var scales [256]numeric.Phase

	for b := range len(scales) {
		scales[b] = numeric.Phase(
			modPowField(int(numeric.FieldPrimitive), b),
		)

		if scales[b] == 0 {
			scales[b] = 1
		}
	}

	return scales
}

/*
initByteRouteHints precomputes one compact routing hint per byte from its
BaseValue footprint. The hint is not semantic metadata; it is a cheap structural
summary derived from the prime-basis occupancy pattern.

Uses a single reusable Value to avoid 256 Cap'n Proto message allocations at
init time (~2.5MB saved).
*/
func initByteRouteHints() [256]uint8 {
	var hints [256]uint8

	scratch, err := New()

	if err != nil {
		panic("initByteRouteHints: " + err.Error())
	}

	for b := range len(hints) {
		BaseValueInto(byte(b), &scratch)
		hints[b] = uint8(scratch.Bin())
	}

	return hints
}

/*
CoreHash returns a 64-bit hash of the mathematical core only (blocks 0
through CoreBlocks-1). Shell metadata in blocks 128-130 is excluded so
routing mutations never alter the mathematical identity. Use this for
memoization, deduplication, and structural equality where the pure
geometric state must be invariant to control-plane changes.
*/
func (value Value) CoreHash() uint64 {
	var hash uint64

	for blockIndex := range config.CoreBlocks {
		word := value.Block(blockIndex)
		hash ^= word * (0x9e3779b185ebca87 + uint64(blockIndex)*0x6c62272e07bb0142)
		hash = (hash << 17) | (hash >> 47)
	}

	return hash
}

/*
CoreEqual reports whether two Values have identical mathematical cores,
ignoring all shell metadata. This is the correct equality predicate for
any context where routing, opcodes, or operator flags are irrelevant.
*/
func (value Value) CoreEqual(other Value) bool {
	for blockIndex := range config.CoreBlocks {
		if value.Block(blockIndex) != other.Block(blockIndex) {
			return false
		}
	}

	return true
}

/*
ValueErrorType enumerates stable value-construction and block-layout failures.
*/
type ValueErrorType string

const (
	ValueErrorTypeAllocationFailed   ValueErrorType = "allocation failed"
	ValueErrorTypeInvalidBlockIndex  ValueErrorType = "invalid block index"
	ValueErrorTypeInvalidDestination ValueErrorType = "invalid destination"
)

/*
ValueError carries a stable message and typed reason so callers can branch
on exact failure categories (allocation, block index) without string parsing.
*/
type ValueError struct {
	Message string
	Err     ValueErrorType
}

/*
NewValueError constructs a typed value error with a stable message and reason
enum so callers can branch on exact failure categories.
*/
func NewValueError(err ValueErrorType) *ValueError {
	return &ValueError{Message: string(err), Err: err}
}

/*
Error formats ValueError as a readable string for logs and returned errors.
*/
func (err ValueError) Error() string {
	return fmt.Sprintf("value error: %s: %s", err.Message, err.Err)
}
