package primitive

import (
	"fmt"

	capnp "capnproto.org/go/capnp/v3"
	"github.com/theapemachine/six/pkg/errnie"
	"github.com/theapemachine/six/pkg/numeric"
)

var (
	/*
		canonicalValueBasis is a 5-mark Golomb ruler projected into GF(257).
		Each set bit in the 257-core is treated as a basis coordinate that maps
		to one prime frequency (index k -> numeric.Primes[k] when projected in
		PhaseDial). The runtime stores only 0/1 occupancy for speed, but the
		algebra stays in prime-factor space: bitwise composition in companion
		operators (`OR`, `AND`, `Hole`) is interpreted as lattice operations over
		that prime basis.

		The basis uses unique pairwise deltas so byte projections remain sparse,
		structured, and rotation-friendly instead of collapsing into dense noise.
	*/
	canonicalValueBasis = [5]int{0, 1, 4, 9, 11}

	byteValueMultipliers = initByteValueMultipliers()

	bytePhaseScales = initBytePhaseScales()
	byteRouteHints  = initByteRouteHints()
)

/*
New allocates one fresh primitive Value in a standalone single-segment
Cap'n Proto message so the returned value has independent storage and can be
mutated safely by callers without aliasing another value's backing segment.
*/
func New() (Value, error) {
	_, seg, err := capnp.NewMessage(capnp.SingleSegment(nil))

	if err != nil {
		return Value{}, errnie.Error(
			NewValueError(ValueErrorTypeAllocationFailed),
		)
	}

	value, err := NewValue(seg)

	if err != nil {
		return Value{}, errnie.Error(
			NewValueError(ValueErrorTypeAllocationFailed),
		)
	}

	return value, nil
}

/*
NeutralValue allocates a lexical-free native value. The value starts with an
identity affine operator so it behaves like a tiny local program even before
any lexical observable is projected onto it.
*/
func NeutralValue() Value {
	state := errnie.NewState("primitive/value/neutralValue")

	value := errnie.Guard(state, func() (Value, error) {
		return New()
	})

	value.SetAffine(1, 0)

	return value
}

/*
BaseValue returns a deterministic 5-bit value for a byte value.
The value is generated by an affine transform of a sparse 5-mark basis
inside GF(257), so collisions remain structured and rotation-friendly
instead of behaving like arbitrary scatter.

Each selected core offset marks one prime-basis coordinate; downstream
bitwise operators can then treat overlap and cancellation as exact structural
signals over that basis instead of semantic symbols.
*/
func BaseValue(b byte) Value {
	state := errnie.NewState("primitive/value/baseValue")

	value := errnie.Guard(state, func() (Value, error) {
		return New()
	})

	for _, off := range baseValueOffsets(b) {
		value.Set(off)
	}

	return value
}

/*
baseValueOffsets computes five offsets using byteValueMultipliers[int(b)],
the additive (int(b)*17+1)%257, and canonicalValueBasis, and returns [5]int.
This keeps byte -> basis projection deterministic while distributing values
across the 257-bit core to minimize accidental aliasing.
*/
func baseValueOffsets(b byte) [5]int {
	mul := byteValueMultipliers[int(b)]
	add := (int(b)*17 + 1) % 257

	var offsets [5]int

	for i, base := range canonicalValueBasis {
		offsets[i] = (base*mul + add) % 257
	}

	return offsets
}

/*
setBlock writes one 64-bit word into the requested block index (0..7) and
returns an explicit error when the index is outside the primitive layout.
*/
func (value Value) setBlock(i int, v uint64) (Value, error) {
	switch i {
	case 0:
		value.SetC0(v)
	case 1:
		value.SetC1(v)
	case 2:
		value.SetC2(v)
	case 3:
		value.SetC3(v)
	case 4:
		value.SetC4(v)
	case 5:
		value.SetC5(v)
	case 6:
		value.SetC6(v)
	case 7:
		value.SetC7(v)
	default:
		return value, NewValueError(ValueErrorTypeInvalidBlockIndex)
	}

	return value, nil
}

/*
Block returns the raw 64-bit word at block index i. Indices outside 0..7 are
treated as invalid and return zero while emitting a warning for diagnostics.
*/
func (value Value) Block(i int) uint64 {
	switch i {
	case 0:
		return value.C0()
	case 1:
		return value.C1()
	case 2:
		return value.C2()
	case 3:
		return value.C3()
	case 4:
		return value.C4()
	case 5:
		return value.C5()
	case 6:
		return value.C6()
	case 7:
		return value.C7()
	default:
		errnie.Warn("block overflow, wrap around to 0", "index", i)
		return 0
	}
}

/*
CopyFrom copies all 8 words from src into the receiver.
Replaces the repeated SetC0..SetC7 call pattern at every call site.
*/
func (value *Value) CopyFrom(src Value) {
	for i := range 8 {
		value.setBlock(i, src.Block(i))
	}
}

/*
ValueSliceToList packs a Go slice of Values into a Cap'n Proto Value_List.
*/
func ValueSliceToList(values []Value) (Value_List, error) {
	_, seg, err := capnp.NewMessage(capnp.MultiSegment(nil))
	if err != nil {
		return Value_List{}, err
	}

	state := errnie.NewState("primitive/value/valueSliceToList")

	list := errnie.Guard(state, func() (Value_List, error) {
		return NewValue_List(seg, int32(len(values)))
	})

	if state.Failed() {
		return Value_List{}, state.Err()
	}

	for i, cc := range values {
		dst := list.At(i)
		dst.CopyFrom(cc)
	}

	return list, nil
}

/*
ValueListToSlice copies each entry into a freshly allocated Value and returns the slice.
*/
func ValueListToSlice(list Value_List) ([]Value, error) {
	out := make([]Value, list.Len())

	_, seg, err := capnp.NewMessage(capnp.MultiSegment(nil))
	if err != nil {
		return nil, err
	}

	state := errnie.NewState("primitive/value/valueListToSlice")

	for i := 0; i < list.Len(); i++ {
		src := list.At(i)

		value := errnie.Guard(state, func() (Value, error) {
			return NewValue(seg)
		})

		value.CopyFrom(src)
		out[i] = value
	}

	if state.Failed() {
		return nil, state.Err()
	}

	return out, nil
}

/*
initByteValueMultipliers builds a 256-entry multiplier table using
modPow257(3, b+1) and returns [256]int.
*/
func initByteValueMultipliers() [256]int {
	var multipliers [256]int

	for b := range len(multipliers) {
		multipliers[b] = modPow257(3, b+1)
	}

	return multipliers
}

/*
modPow257 computes modular exponentiation modulo 257 using exponentiation
by squaring and returns int. Parameters are base and exp.
*/
func modPow257(base, exp int) int {
	result := 1
	base %= 257

	for exp > 0 {
		if exp&1 == 1 {
			result = (result * base) % 257
		}
		base = (base * base) % 257
		exp >>= 1
	}

	return result
}

/*
initBytePhaseScales precomputes one GF(257) phase scale per byte using the
field primitive generator. This keeps byte-local phase transforms deterministic
without doing modular exponentiation in hot paths.
*/
func initBytePhaseScales() [256]numeric.Phase {
	var scales [256]numeric.Phase

	for b := range len(scales) {
		scales[b] = numeric.Phase(
			modPow257(int(numeric.FermatPrimitive), b),
		)

		if scales[b] == 0 {
			scales[b] = 1
		}
	}

	return scales
}

/*
initByteRouteHints precomputes one compact routing hint per byte from its
BaseValue footprint. The hint is not semantic metadata; it is a cheap structural
summary derived from the prime-basis occupancy pattern.
*/
func initByteRouteHints() [256]uint8 {
	var hints [256]uint8

	for b := range len(hints) {
		base := BaseValue(byte(b))
		hints[b] = uint8(base.Bin())
	}

	return hints
}

/*
ValueErrorType enumerates stable value-construction and block-layout failures.
*/
type ValueErrorType string

const (
	ValueErrorTypeAllocationFailed  ValueErrorType = "allocation failed"
	ValueErrorTypeInvalidBlockIndex ValueErrorType = "invalid block index"
)

type ValueError struct {
	Message string
	Err     ValueErrorType
}

/*
NewValueError constructs a typed value error with a stable message and reason
enum so callers can branch on exact failure categories.
*/
func NewValueError(err ValueErrorType) *ValueError {
	return &ValueError{Message: string(err), Err: err}
}

/*
Error formats ValueError as a readable string for logs and returned errors.
*/
func (err ValueError) Error() string {
	return fmt.Sprintf("value error: %s: %s", err.Message, err.Err)
}
