// Code generated by capnpc-go. DO NOT EDIT.

package primitive

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
)

type Value capnp.Struct

// Value_TypeID is the unique identifier for the type Value.
const Value_TypeID = 0xc37afa4e1a4a0466

func NewValue(s *capnp.Segment) (Value, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 64, PointerCount: 0})
	return Value(st), err
}

func NewRootValue(s *capnp.Segment) (Value, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 64, PointerCount: 0})
	return Value(st), err
}

func ReadRootValue(msg *capnp.Message) (Value, error) {
	root, err := msg.Root()
	return Value(root.Struct()), err
}

func (s Value) String() string {
	str, _ := text.Marshal(0xc37afa4e1a4a0466, capnp.Struct(s))
	return str
}

func (s Value) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Value) DecodeFromPtr(p capnp.Ptr) Value {
	return Value(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Value) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Value) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Value) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Value) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Value) C0() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s Value) SetC0(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s Value) C1() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s Value) SetC1(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s Value) C2() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s Value) SetC2(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

func (s Value) C3() uint64 {
	return capnp.Struct(s).Uint64(24)
}

func (s Value) SetC3(v uint64) {
	capnp.Struct(s).SetUint64(24, v)
}

func (s Value) C4() uint64 {
	return capnp.Struct(s).Uint64(32)
}

func (s Value) SetC4(v uint64) {
	capnp.Struct(s).SetUint64(32, v)
}

func (s Value) C5() uint64 {
	return capnp.Struct(s).Uint64(40)
}

func (s Value) SetC5(v uint64) {
	capnp.Struct(s).SetUint64(40, v)
}

func (s Value) C6() uint64 {
	return capnp.Struct(s).Uint64(48)
}

func (s Value) SetC6(v uint64) {
	capnp.Struct(s).SetUint64(48, v)
}

func (s Value) C7() uint64 {
	return capnp.Struct(s).Uint64(56)
}

func (s Value) SetC7(v uint64) {
	capnp.Struct(s).SetUint64(56, v)
}

// Value_List is a list of Value.
type Value_List = capnp.StructList[Value]

// NewValue creates a new list of Value.
func NewValue_List(s *capnp.Segment, sz int32) (Value_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 64, PointerCount: 0}, sz)
	return capnp.StructList[Value](l), err
}

// Value_Future is a wrapper for a Value promised by a client call.
type Value_Future struct{ *capnp.Future }

func (f Value_Future) Struct() (Value, error) {
	p, err := f.Future.Ptr()
	return Value(p.Struct()), err
}

const schema_ad058c9d70413d98 = "x\xdaD\xc8\xbfJ\xc3P\x14\x07\xe0\xf3;\xe7&\xb1" +
	"\x83\xe0\x81;urq\xd4X\xff\x82 \xe8\xea \xde" +
	"\xc5\xc1-\x84Z\x82\xb1\x06\xb1\x1d|\x06\x1f\xc0\xc5G" +
	"\xf0\x11\xc4A\xc4\xc5A\xc1B\x0b\x15*T\xa8\xa0\xe0" +
	"\xe0\xe4\x12\xb9\x83d\xfb\xf8fn\xb6Lc\xfa\x16\xc4" +
	"\xce\x06ayhv\xea\xbb\xbf\xe7w\xe4\xe60U^" +
	"nn\x17W\x17\xc15\x99\x88\xa8q\x7f\x00\x1dx\xf4" +
	"\x1e@\xf3eq\xd4\x8a\xf3\x93Vf\xd28O\xda\xad" +
	"\xb88\xcd\x8e\xb3\xb3\xac\xdb\x8c\xbbI\xdei.\xa4I" +
	"\xd1.6\xf6\x93\\:\xcd=\xc0\xcd\x8a!2 \xd2" +
	"\xe7:\x91{\x14\xb8>C\x01\x0b\x9f=\x9fO\x027" +
	"d(\xb3\x05\x13\xe9\xc0\xe7\x8b\xc0\x8d\x18*b!D" +
	"\xfa\xea\xb3/pc\x86\x1aca\x88\xf4\xcd\xe7P\xe0" +
	"&\x0c\x0d\x02\x8b\x80H\xdf}\x8e\x04\xee\x93\xa1ah" +
	"\x11\x12\xe9\x87\xcf\xb1\xc0}34\x8a,\"\"\xfd\xf2" +
	"9\x11\xb8\x1f\x86\xa4\x8b\xa8\x11\xa3F\x90\xb4Qq\xa9" +
	"\xe2r\xc5\x95\x8a\xab\x15\xd7*\xae\xff\xf3/\x00\x00\xff" +
	"\xff\xbb\x0eDe"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_ad058c9d70413d98,
		Nodes: []uint64{
			0xc37afa4e1a4a0466,
		},
		Compressed: true,
	})
}
