// Code generated by capnpc-go. DO NOT EDIT.

package process

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
	data "github.com/theapemachine/six/data"
)

type Token capnp.Struct

// Token_TypeID is the unique identifier for the type Token.
const Token_TypeID = 0xbe0e12773134c75d

func NewToken(s *capnp.Segment) (Token, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Token(st), err
}

func NewRootToken(s *capnp.Segment) (Token, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Token(st), err
}

func ReadRootToken(msg *capnp.Message) (Token, error) {
	root, err := msg.Root()
	return Token(root.Struct()), err
}

func (s Token) String() string {
	str, _ := text.Marshal(0xbe0e12773134c75d, capnp.Struct(s))
	return str
}

func (s Token) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Token) DecodeFromPtr(p capnp.Ptr) Token {
	return Token(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Token) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Token) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Token) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Token) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Token) Id() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s Token) SetId(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s Token) Chord() (data.Chord, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return data.Chord(p.Struct()), err
}

func (s Token) HasChord() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Token) SetChord(v data.Chord) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewChord sets the chord field to a newly
// allocated data.Chord struct, preferring placement in s's segment.
func (s Token) NewChord() (data.Chord, error) {
	ss, err := data.NewChord(capnp.Struct(s).Segment())
	if err != nil {
		return data.Chord{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Token_List is a list of Token.
type Token_List = capnp.StructList[Token]

// NewToken creates a new list of Token.
func NewToken_List(s *capnp.Segment, sz int32) (Token_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[Token](l), err
}

// Token_Future is a wrapper for a Token promised by a client call.
type Token_Future struct{ *capnp.Future }

func (f Token_Future) Struct() (Token, error) {
	p, err := f.Future.Ptr()
	return Token(p.Struct()), err
}
func (p Token_Future) Chord() data.Chord_Future {
	return data.Chord_Future{Future: p.Future.Field(0, nil)}
}

type Tokenizer capnp.Client

// Tokenizer_TypeID is the unique identifier for the type Tokenizer.
const Tokenizer_TypeID = 0x8a479c8a23a8e58a

func (c Tokenizer) Generate(ctx context.Context, params func(Tokenizer_generate_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x8a479c8a23a8e58a,
			MethodID:      0,
			InterfaceName: "process/tokenizer.capnp:Tokenizer",
			MethodName:    "generate",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Tokenizer_generate_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c Tokenizer) Done(ctx context.Context, params func(Tokenizer_done_Params) error) (Tokenizer_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x8a479c8a23a8e58a,
			MethodID:      1,
			InterfaceName: "process/tokenizer.capnp:Tokenizer",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Tokenizer_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Tokenizer_done_Results_Future{Future: ans.Future()}, release

}

func (c Tokenizer) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Tokenizer) String() string {
	return "Tokenizer(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Tokenizer) AddRef() Tokenizer {
	return Tokenizer(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Tokenizer) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Tokenizer) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Tokenizer) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Tokenizer) DecodeFromPtr(p capnp.Ptr) Tokenizer {
	return Tokenizer(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Tokenizer) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Tokenizer) IsSame(other Tokenizer) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Tokenizer) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Tokenizer) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Tokenizer_Server is a Tokenizer with a local implementation.
type Tokenizer_Server interface {
	Generate(context.Context, Tokenizer_generate) error

	Done(context.Context, Tokenizer_done) error
}

// Tokenizer_NewServer creates a new Server from an implementation of Tokenizer_Server.
func Tokenizer_NewServer(s Tokenizer_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Tokenizer_Methods(nil, s), s, c)
}

// Tokenizer_ServerToClient creates a new Client from an implementation of Tokenizer_Server.
// The caller is responsible for calling Release on the returned Client.
func Tokenizer_ServerToClient(s Tokenizer_Server) Tokenizer {
	return Tokenizer(capnp.NewClient(Tokenizer_NewServer(s)))
}

// Tokenizer_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Tokenizer_Methods(methods []server.Method, s Tokenizer_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x8a479c8a23a8e58a,
			MethodID:      0,
			InterfaceName: "process/tokenizer.capnp:Tokenizer",
			MethodName:    "generate",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Generate(ctx, Tokenizer_generate{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x8a479c8a23a8e58a,
			MethodID:      1,
			InterfaceName: "process/tokenizer.capnp:Tokenizer",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, Tokenizer_done{call})
		},
	})

	return methods
}

// Tokenizer_generate holds the state for a server call to Tokenizer.generate.
// See server.Call for documentation.
type Tokenizer_generate struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Tokenizer_generate) Args() Tokenizer_generate_Params {
	return Tokenizer_generate_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Tokenizer_generate) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// Tokenizer_done holds the state for a server call to Tokenizer.done.
// See server.Call for documentation.
type Tokenizer_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Tokenizer_done) Args() Tokenizer_done_Params {
	return Tokenizer_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Tokenizer_done) AllocResults() (Tokenizer_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Tokenizer_done_Results(r), err
}

// Tokenizer_List is a list of Tokenizer.
type Tokenizer_List = capnp.CapList[Tokenizer]

// NewTokenizer_List creates a new list of Tokenizer.
func NewTokenizer_List(s *capnp.Segment, sz int32) (Tokenizer_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Tokenizer](l), err
}

type Tokenizer_generate_Params capnp.Struct

// Tokenizer_generate_Params_TypeID is the unique identifier for the type Tokenizer_generate_Params.
const Tokenizer_generate_Params_TypeID = 0xddb30da464b249f7

func NewTokenizer_generate_Params(s *capnp.Segment) (Tokenizer_generate_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Tokenizer_generate_Params(st), err
}

func NewRootTokenizer_generate_Params(s *capnp.Segment) (Tokenizer_generate_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Tokenizer_generate_Params(st), err
}

func ReadRootTokenizer_generate_Params(msg *capnp.Message) (Tokenizer_generate_Params, error) {
	root, err := msg.Root()
	return Tokenizer_generate_Params(root.Struct()), err
}

func (s Tokenizer_generate_Params) String() string {
	str, _ := text.Marshal(0xddb30da464b249f7, capnp.Struct(s))
	return str
}

func (s Tokenizer_generate_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Tokenizer_generate_Params) DecodeFromPtr(p capnp.Ptr) Tokenizer_generate_Params {
	return Tokenizer_generate_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Tokenizer_generate_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Tokenizer_generate_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Tokenizer_generate_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Tokenizer_generate_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Tokenizer_generate_Params) Raw() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Tokenizer_generate_Params) HasRaw() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Tokenizer_generate_Params) SetRaw(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

// Tokenizer_generate_Params_List is a list of Tokenizer_generate_Params.
type Tokenizer_generate_Params_List = capnp.StructList[Tokenizer_generate_Params]

// NewTokenizer_generate_Params creates a new list of Tokenizer_generate_Params.
func NewTokenizer_generate_Params_List(s *capnp.Segment, sz int32) (Tokenizer_generate_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Tokenizer_generate_Params](l), err
}

// Tokenizer_generate_Params_Future is a wrapper for a Tokenizer_generate_Params promised by a client call.
type Tokenizer_generate_Params_Future struct{ *capnp.Future }

func (f Tokenizer_generate_Params_Future) Struct() (Tokenizer_generate_Params, error) {
	p, err := f.Future.Ptr()
	return Tokenizer_generate_Params(p.Struct()), err
}

type Tokenizer_done_Params capnp.Struct

// Tokenizer_done_Params_TypeID is the unique identifier for the type Tokenizer_done_Params.
const Tokenizer_done_Params_TypeID = 0xe20f9dd3c52ef08c

func NewTokenizer_done_Params(s *capnp.Segment) (Tokenizer_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Tokenizer_done_Params(st), err
}

func NewRootTokenizer_done_Params(s *capnp.Segment) (Tokenizer_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Tokenizer_done_Params(st), err
}

func ReadRootTokenizer_done_Params(msg *capnp.Message) (Tokenizer_done_Params, error) {
	root, err := msg.Root()
	return Tokenizer_done_Params(root.Struct()), err
}

func (s Tokenizer_done_Params) String() string {
	str, _ := text.Marshal(0xe20f9dd3c52ef08c, capnp.Struct(s))
	return str
}

func (s Tokenizer_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Tokenizer_done_Params) DecodeFromPtr(p capnp.Ptr) Tokenizer_done_Params {
	return Tokenizer_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Tokenizer_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Tokenizer_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Tokenizer_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Tokenizer_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Tokenizer_done_Params_List is a list of Tokenizer_done_Params.
type Tokenizer_done_Params_List = capnp.StructList[Tokenizer_done_Params]

// NewTokenizer_done_Params creates a new list of Tokenizer_done_Params.
func NewTokenizer_done_Params_List(s *capnp.Segment, sz int32) (Tokenizer_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Tokenizer_done_Params](l), err
}

// Tokenizer_done_Params_Future is a wrapper for a Tokenizer_done_Params promised by a client call.
type Tokenizer_done_Params_Future struct{ *capnp.Future }

func (f Tokenizer_done_Params_Future) Struct() (Tokenizer_done_Params, error) {
	p, err := f.Future.Ptr()
	return Tokenizer_done_Params(p.Struct()), err
}

type Tokenizer_done_Results capnp.Struct

// Tokenizer_done_Results_TypeID is the unique identifier for the type Tokenizer_done_Results.
const Tokenizer_done_Results_TypeID = 0xc8551af63575dc53

func NewTokenizer_done_Results(s *capnp.Segment) (Tokenizer_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Tokenizer_done_Results(st), err
}

func NewRootTokenizer_done_Results(s *capnp.Segment) (Tokenizer_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Tokenizer_done_Results(st), err
}

func ReadRootTokenizer_done_Results(msg *capnp.Message) (Tokenizer_done_Results, error) {
	root, err := msg.Root()
	return Tokenizer_done_Results(root.Struct()), err
}

func (s Tokenizer_done_Results) String() string {
	str, _ := text.Marshal(0xc8551af63575dc53, capnp.Struct(s))
	return str
}

func (s Tokenizer_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Tokenizer_done_Results) DecodeFromPtr(p capnp.Ptr) Tokenizer_done_Results {
	return Tokenizer_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Tokenizer_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Tokenizer_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Tokenizer_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Tokenizer_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Tokenizer_done_Results_List is a list of Tokenizer_done_Results.
type Tokenizer_done_Results_List = capnp.StructList[Tokenizer_done_Results]

// NewTokenizer_done_Results creates a new list of Tokenizer_done_Results.
func NewTokenizer_done_Results_List(s *capnp.Segment, sz int32) (Tokenizer_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Tokenizer_done_Results](l), err
}

// Tokenizer_done_Results_Future is a wrapper for a Tokenizer_done_Results promised by a client call.
type Tokenizer_done_Results_Future struct{ *capnp.Future }

func (f Tokenizer_done_Results_Future) Struct() (Tokenizer_done_Results, error) {
	p, err := f.Future.Ptr()
	return Tokenizer_done_Results(p.Struct()), err
}

const schema_ad058c9d70413d69 = "x\xda\x94\x8f=h\x14A\x1c\xc5\xdf\x9b\xd9u\x93b" +
	"\xbdL6\x81\x10\x90\x83x\x82'x\xc9y\xb1\x11%" +
	"g!\xa2\x85\xdc\xf8Q\x8a,w\x83\x1e\xea\xde1{" +
	"a!`-\x1e\xb1\xb1\x11\xc5t\x166\x16~\xd4b" +
	"a\xd0\xc6BlM#\xd8\x8aXh9\xb2\x17\xb3'" +
	"B\x8at\xf3\xf1\xff\xfd\x7f\xef-\x95\xd8\xf4\xea\xe1\xa2" +
	"\x0f\xa1O\xfa\xfb\xdc\xf0\xdb\xb3\x83\xc3'g\x87Ps" +
	"\xd2uO\x9d\xeeo\xac\xfb\xcf\x016\xee\x88iF\xf7" +
	"E\x00D\xf7\xc4\xddh+?\xb9\xab\xef\x97\xeb\xd9\xf4" +
	"\xfe7\xd0s\xe4x\xdcg>\xb6)~F\x9fF\xc0" +
	"G\x91\x81\xee\xd2\x97\xd5\xe3\xbf\xe6\xaf|\x80Z \xe0" +
	"\x05@\xa3*\xd7\x08\xcf\xfd>\xf7\xb2\xf34|\xb5\xb5" +
	"\xfd3\xa2\x1b\xb3\xf2\x01\xc1\xe8\x90\\\x01\xdd\xfa\x8f\xda" +
	"\xe6\xe7\x8d\xd2\xd7\x7f\xd03\xd2\x12\xd6\xf5m\xafm\xd2" +
	"tQ\x0ez7M\xd2]3\xb6\xd6\x8e\xfbI\xff\xc4" +
	"\xe5\xbfw\xda\x16\xa9'\xa4\x0f\x14\x1e&/\xdef\x8d" +
	"\xc7\xd7\x1e\xa9\xfay\x08U\x0d8Vp'\xa6:p" +
	"\x04B\xa9\xc0]7\x89\xb1\xf1\xc0\x00h\xb2\xd4\xe9%" +
	"\xa6\xc9\x16Y\xa8\xc5\xff\xea\xf2\xc8\xbd\xad\xf5\x00\x8f\x80" +
	"\xaa\xce\x03\xba\"\xa9\x97\x04\xc9\x19\xe6oG\x8f\x01\xfa" +
	"\xb0\xa4^\x16\x94\xdd\x0e'!8\x09\x96\xdb7z\xb6" +
	"\xc3)\xf7\xb0;{\xe1{\xfa\xfa\x1d@Na,\xf4" +
	"v\xebjky\xba\xca\xc5\x15\x93\xae\xde\x1a\xa4\x05\xe0" +
	"\xef\x0e\xec\x94\xab\xb4b\x1b\xdff\xaa\xbd\"r\xb8\x00" +
	"\xe8\x09I=#\x18\xd88c\x08\xc1p\x0f9Z\xe5" +
	"|g\xfa'\x00\x00\xff\xff\x88\x06\xb0\x96"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_ad058c9d70413d69,
		Nodes: []uint64{
			0x8a479c8a23a8e58a,
			0xbe0e12773134c75d,
			0xc8551af63575dc53,
			0xddb30da464b249f7,
			0xe20f9dd3c52ef08c,
		},
		Compressed: true,
	})
}
