package cortex

import (
	"github.com/theapemachine/six/console"
	"github.com/theapemachine/six/data"
	"github.com/theapemachine/six/geometry"
)

const hologramNoiseFloor = 2.0

func holographicProbe(summary data.Chord, pos int) (byte, float64) {
	bestByte := byte(0)
	bestScore := 0.0

	for b := range 256 {
		testChord := data.BaseChord(byte(b))
		testChord = testChord.RollLeft(pos)
		score := float64(data.ChordSimilarity(&testChord, &summary))
		if score > bestScore {
			bestScore = score
			bestByte = byte(b)
		}
	}

	return bestByte, bestScore
}

/*
Think is the top-level cortex execution.

Lifecycle:
 1. BIRTH   — Prompt chords are injected into the source node with
    Sequencer-driven topological events generating LAW tokens.
 2. SEED    — Expected reality / expected field are seeded into the sink
    as structural attractors.
 3. VIBRATE — The tick loop runs until convergence or timeout.
 4. EXTRACT — The converged sink hologram is probed position-by-position.
 5. COMMIT  — Surviving dense nodes are written back to the PrimeField.
 6. DEATH   — The graph dissolves. The chan is closed.

The returned channel emits generated bytes after the cortex reaches steady state.
*/
func (g *Graph) Think(prompt []data.Chord, expected *geometry.IcosahedralManifold) chan byte {
	out := make(chan byte, g.config.MaxOutput)

	go func() {
		defer close(out)

		g.InjectWithSequencer(prompt)

		if expected != nil {
			for i := range geometry.CubeFaces {
				if expected.Cubes[0][i].ActiveCount() > 0 {
					g.sink.Send(NewDataToken(expected.Cubes[0][i], -1))
				}
			}
		}

		if g.config.ExpectedField != nil {
			for cube := range 5 {
				for face := range geometry.CubeFaces {
					if g.config.ExpectedField.Precision[cube][face] > 0.0 {
						bc := data.BaseChord(byte(face % 256))
						g.sink.Send(NewDataToken(bc, -1))
					}
				}
			}
		}

		converged := false
		aborted := false
		for range g.config.MaxTicks {
			if g.stopped() {
				aborted = true
				break
			}
			if g.Tick() {
				converged = true
				break
			}
		}

		summary := g.sink.CubeChord()
		console.Info("cortex convergence reached",
			"converged", converged,
			"aborted", aborted,
			"ticks", g.tick,
			"nodes", len(g.nodes),
			"sinkEnergy", g.sink.Energy(),
			"summaryBits", summary.ActiveCount(),
		)

		if !aborted {
			for pos := 0; pos < g.config.MaxOutput; pos++ {
				bestByte, bestScore := holographicProbe(summary, pos)
				if bestScore < hologramNoiseFloor {
					break
				}

				out <- bestByte
				g.outputBytes++
			}
		}

		written := g.WriteSurvivors(0.1)

		snap := g.Snapshot()
		console.Info("cortex dissolved",
			"totalTicks", snap.TotalTicks,
			"finalNodes", snap.FinalNodes,
			"survivorCount", snap.SurvivorCount,
			"bedrockQueries", snap.BedrockQueries,
			"mitosisEvents", snap.MitosisEvents,
			"pruneEvents", snap.PruneEvents,
			"outputBytes", snap.OutputBytes,
			"survivorsWritten", written,
		)
	}()

	return out
}
