package cortex

import (
	"math"

	"github.com/theapemachine/six/console"
	"github.com/theapemachine/six/data"
	"github.com/theapemachine/six/geometry"
)

/*
Think is the top-level cortex execution.

Lifecycle:
 1. BIRTH   — Prompt chords are injected into the source node with
    Sequencer-driven topological events generating LAW tokens.
 2. SEED    — Expected reality / expected field are seeded into the sink
    as structural attractors.
 3. VIBRATE — The tick loop runs until convergence or timeout.
 4. EXTRACT — Output bytes are read from the sink via rotation-aware BestFace.
 5. REINJCT — Each extracted byte is re-injected into the source with
    continued Sequencer analysis (cascade auto-regression).
 6. COMMIT  — Surviving dense nodes are written back to the PrimeField.
 7. DEATH   — The graph dissolves. The chan is closed.

The returned channel emits generated bytes as they are produced.
*/
func (g *Graph) Think(prompt []data.Chord, expected *geometry.IcosahedralManifold) chan byte {
	out := make(chan byte, 1)

	go func() {
		defer close(out)

		// ── BIRTH: inject prompt with topological events ─────────────
		g.InjectWithSequencer(prompt)

		// ── SEED: structural attractors ──────────────────────────────
		// Seed expected reality into the sink to bias convergence.
		if expected != nil {
			for i := range geometry.CubeFaces {
				if expected.Cubes[0][i].ActiveCount() > 0 {
					g.sink.Send(NewDataToken(expected.Cubes[0][i], -1))
				}
			}
		}

		// Seed expected field (classification precision) into the sink.
		// Each non-zero precision face gets a weighted token injection.
		if g.config.ExpectedField != nil {
			for cube := range 5 {
				for face := range geometry.CubeFaces {
					if g.config.ExpectedField.Precision[cube][face] > 0.0 {
						// Create a chord with the face's base pattern weighted
						// by the precision value (more precise = denser chord).
						bc := data.BaseChord(byte(face % 256))
						g.sink.Send(NewDataToken(bc, -1))
					}
				}
			}
		}

		// ── VIBRATE: warmup ──────────────────────────────────────────
		warmup := g.config.MaxTicks / 4
		if warmup < 16 {
			warmup = 16
		}
		for range warmup {
			if g.stopped() {
				return
			}
			if g.Tick() {
				break
			}
		}

		console.Info("cortex warmup complete",
			"ticks", g.tick,
			"nodes", len(g.nodes),
			"sinkEnergy", g.sink.Energy(),
			"sourceEnergy", g.source.Energy(),
			"momentum", g.momentum,
		)

		// ── EXTRACT: cascade auto-regressive generation ──────────────
		reConvergeTicks := g.config.MaxTicks / g.config.MaxOutput
		if reConvergeTicks < 8 {
			reConvergeTicks = 8
		}

		// Momentum decay from Sequencer (ported from Runner).
		phiDecay := 1.0
		var phiThresh float64
		if g.config.Sequencer != nil {
			phiDecay = sequencerDecay(g.config.Sequencer.Phi())
			_, phiThresh = g.config.Sequencer.Phase()
		}

		for i := range g.config.MaxOutput {
			if g.stopped() {
				return
			}

			// Momentum check: exit if momentum drops below threshold.
			if phiThresh > 0 && g.momentum < phiThresh {
				console.Info("cortex stop: momentum exhausted",
					"momentum", g.momentum,
					"threshold", phiThresh,
					"bytesGenerated", i,
				)
				break
			}

			face := g.sink.BestFace()

			// Face 256 = delimiter → sequence complete.
			if face == 256 {
				console.Info("cortex stop: delimiter",
					"bytesGenerated", i,
					"totalTicks", g.tick,
				)
				break
			}

			// Reverse back to physical face to check if active.
			physicalFace := g.sink.Rot.Forward(face)
			if g.sink.Cube[physicalFace].ActiveCount() == 0 {
				console.Info("cortex stop: exhausted",
					"bytesGenerated", i,
					"totalTicks", g.tick,
				)
				break
			}

			// Emit the byte.
			out <- byte(face)
			g.outputBytes++

			// Clear the emitted face to prevent echo-loop.
			g.sink.Cube[physicalFace] = data.Chord{}

			// Decay momentum.
			g.momentum *= phiDecay

			// ── REINJECT: cascade output back as input with Sequencer ──
			reinjection := data.BaseChord(byte(face))
			g.source.Send(NewDataToken(reinjection, -1))

			// Continue Sequencer analysis on the generated output.
			if g.config.Sequencer != nil {
				reset, events := g.config.Sequencer.Analyze(int(g.seqPos), reinjection)
				g.accumulateMomentum(reinjection, events)
				for _, ev := range events {
					rot := geometry.EventRotation(ev)
					g.source.Send(NewRotationToken(rot, -1))
				}
				g.seqPos++
				if reset {
					g.seqPos = 0
					g.seqZ++
				}
			}

			// Let the graph re-converge with the new context.
			for range reConvergeTicks {
				if g.stopped() {
					return
				}
				if g.Tick() {
					break
				}
			}
		}

		// ── COMMIT: write survivors back to PrimeField ───────────────
		written := g.WriteSurvivors(0.1)

		snap := g.Snapshot()
		console.Info("cortex dissolved",
			"totalTicks", snap.TotalTicks,
			"finalNodes", snap.FinalNodes,
			"survivorCount", snap.SurvivorCount,
			"bedrockQueries", snap.BedrockQueries,
			"mitosisEvents", snap.MitosisEvents,
			"pruneEvents", snap.PruneEvents,
			"outputBytes", snap.OutputBytes,
			"survivorsWritten", written,
		)
	}()

	return out
}

func sequencerDecay(phi float64) float64 {
	if phi <= 0 {
		return 1.0
	}

	if phi > 1.0 {
		phi = 1.0 / phi
	}

	if phi <= 0 || phi >= 1.0 {
		return (math.Sqrt(5.0) - 1.0) / 2.0
	}

	return phi
}
